import { getPlanState, verifyToolAccess } from "/tool/frontend/tool-access.js?v=20260923";

const $=s=>document.querySelector(s);
const state={files:[],results:[],pro:false,limit:10,ratio:null};
const els={file:$("#file"),drop:$("#drop"),w:$("#w"),h:$("#h"),fit:$("#fit"),fmt:$("#fmt"),quality:$("#quality"),qv:$("#qv"),bg:$("#bg"),lock:$("#lock"),upscale:$("#upscale"),run:$("#run"),download:$("#download"),clear:$("#clear"),queue:$("#queue"),status:$("#status"),plan:$("#plan"),limit:$("#limit"),count:$("#count"),mode:$("#mode"),done:$("#done"),before:$("#totalBefore"),after:$("#totalAfter"),saved:$("#saved")};
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return `${v.toFixed(v>=100?0:v>=10?1:2)} ${u[i]}`}
function ext(type){return type==="image/jpeg"?"jpg":type==="image/png"?"png":"webp"}
function setStatus(t,error=false){els.status.textContent=t;els.status.className="status"+(error?" error":"")}
function renderQueue(){els.count.textContent=state.files.length;els.queue.innerHTML="";state.files.forEach((f,i)=>{const row=document.createElement("div");row.className="item";const img=document.createElement("img");img.className="thumb";img.src=URL.createObjectURL(f);const info=document.createElement("div");info.innerHTML=`<b>${f.name.replace(/[<>]/g,"")}</b><br><small>${bytes(f.size)}</small>`;const btn=document.createElement("button");btn.className="preset remove";btn.textContent="Remover";btn.onclick=()=>{state.files.splice(i,1);renderQueue()};row.append(img,info,btn);els.queue.append(row)})}
function setPlanUI(){els.plan.textContent=state.pro?"NEXAUREN PRO · 50/lote":"NEXAUREN FREE · 10/lote";els.plan.className="plan";els.limit.textContent=state.limit}
async function loadPlan(){const [plan,access]=await Promise.all([getPlanState({force:true}),verifyToolAccess("image-resizer")]);if(!plan?.authenticated||plan.pro===null||plan.status==="UNKNOWN")throw Error("Não foi possível confirmar o seu plano.");if(plan.pro===true){if(plan.plan?.toLowerCase()!=="pro"||plan.status?.toUpperCase()!=="ACTIVE"||access?.unlocked!==true||access?.error)throw Error("Não foi possível confirmar o acesso aos recursos Pro.");state.pro=true;state.limit=50}else{state.pro=false;state.limit=10}setPlanUI()}
function addFiles(list){const incoming=[...list].filter(f=>f.type.startsWith("image/"));const maxSize=state.pro?50:20;const valid=incoming.filter(f=>f.size<=maxSize*1024*1024);const rejected=incoming.length-valid.length;if(state.files.length+valid.length>state.limit){setStatus(`Este lote permite até ${state.limit} imagens.`,true);return}state.files.push(...valid);renderQueue();setStatus(rejected?`${rejected} ficheiro(s) ultrapassaram o limite de ${maxSize} MB.`:`${state.files.length} imagem(ns) na fila.`,rejected>0)}
els.drop.onclick=()=>els.file.click();els.file.onchange=e=>addFiles(e.target.files);["dragenter","dragover"].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.add("drag")}));["dragleave","drop"].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.remove("drag")}));els.drop.addEventListener("drop",e=>addFiles(e.dataTransfer.files));
els.quality.oninput=()=>els.qv.textContent=`${els.quality.value}%`;
els.fit.onchange=()=>els.mode.textContent=els.fit.value==="cover"?"Preencher":els.fit.value==="stretch"?"Esticar":"Proporção";
els.w.oninput=()=>{if(els.lock.checked&&state.ratio)els.h.value=Math.max(1,Math.round(Number(els.w.value)/state.ratio))};els.h.oninput=()=>{if(els.lock.checked&&state.ratio)els.w.value=Math.max(1,Math.round(Number(els.h.value)*state.ratio))};
els.file.addEventListener("change",async e=>{const f=e.target.files?.[0];if(f){try{const im=await NexaurenImage.loadImage(f);state.ratio=im.naturalWidth/im.naturalHeight;els.w.value=im.naturalWidth;els.h.value=im.naturalHeight}catch{}}});
document.querySelectorAll(".preset").forEach(b=>b.addEventListener("click",()=>{if(!b.dataset.w)return;els.w.value=b.dataset.w;els.h.value=b.dataset.h;els.lock.checked=false}));
async function resizeOne(file){const im=await NexaurenImage.loadImage(file);const W=Math.max(1,Number(els.w.value)||1),H=Math.max(1,Number(els.h.value)||1),max=state.pro?12000:6000;if(W>max||H>max)throw Error(`Dimensão máxima: ${max}px.`);if(!els.upscale.checked&&(im.naturalWidth<W||im.naturalHeight<H))return draw(im,Math.min(W,im.naturalWidth),Math.min(H,im.naturalHeight));return draw(im,W,H)}
async function draw(im,W,H){const c=NexaurenImage.canvas(W,H),x=c.getContext("2d");x.imageSmoothingEnabled=true;x.imageSmoothingQuality="high";const fit=els.fit.value;if(els.fmt.value==="image/jpeg"||els.bg.value!=="transparent"){x.fillStyle=els.bg.value==="transparent"?"#fff":els.bg.value;x.fillRect(0,0,W,H)}let dx=0,dy=0,dw=W,dh=H;if(fit!=="stretch"){const scale=fit==="cover"?Math.max(W/im.naturalWidth,H/im.naturalHeight):Math.min(W/im.naturalWidth,H/im.naturalHeight);dw=Math.max(1,Math.round(im.naturalWidth*scale));dh=Math.max(1,Math.round(im.naturalHeight*scale));dx=Math.round((W-dw)/2);dy=Math.round((H-dh)/2)}x.drawImage(im,dx,dy,dw,dh);return NexaurenImage.blob(c,els.fmt.value,Number(els.quality.value)/100)}
async function run(){if(!state.files.length)return setStatus("Adicione pelo menos uma imagem.",true);if(state.files.length>state.limit)return setStatus(`O seu plano permite até ${state.limit} imagens por lote.`,true);els.run.disabled=true;state.results=[];setStatus("A processar…");let before=0,after=0,done=0;try{for(const f of state.files){before+=f.size;const b=await resizeOne(f);after+=b.size;state.results.push({name:f.name,blob:b});done++;els.done.textContent=done;els.before.textContent=bytes(before);els.after.textContent=bytes(after);els.saved.textContent=before?`${Math.max(0,Math.round((1-after/before)*100))}%`:"—";await new Promise(r=>setTimeout(r,0))}els.download.disabled=!state.results.length;setStatus(`${done} imagem(ns) redimensionada(s) com sucesso.`)}catch(e){setStatus(e.message||"Não foi possível processar as imagens.",true)}finally{els.run.disabled=false}}
els.run.onclick=run;
els.download.onclick=()=>state.results.forEach((r,i)=>NexaurenImage.download(r.blob,`nexauren-${String(i+1).padStart(2,"0")}.${ext(r.blob.type)}`));
els.clear.onclick=()=>{state.files=[];state.results=[];els.file.value="";els.queue.innerHTML="";els.count.textContent="0";els.done.textContent="0";els.before.textContent="—";els.after.textContent="—";els.saved.textContent="—";els.download.disabled=true;setStatus("Adicione imagens para começar.")};
loadPlan().catch(e=>{els.plan.textContent="Conta não confirmada";setStatus(e.message||"Não foi possível confirmar o seu plano.",true);els.run.disabled=true});
