(()=>{"use strict";
const $=s=>document.querySelector(s);
const input=$("#pdfrotate-file"),drop=$("#pdfrotate-drop"),fileBar=$("#pdfrotate-filebar"),fileName=$("#pdfrotate-file-name"),fileSize=$("#pdfrotate-file-size");
const pages=$("#pdfrotate-pages"),range=$("#pdfrotate-range"),runBtn=$("#pdfrotate-run"),clearBtn=$("#pdfrotate-clear"),status=$("#pdfrotate-status"),progress=$("#pdfrotate-progress"),result=$("#pdfrotate-result"),download=$("#pdfrotate-download");
const total=$("#pdfrotate-total"),angleStat=$("#pdfrotate-angle-stat"),nameInput=$("#pdfrotate-name"),sheet=$("#pdfrotate-page-sheet"),previewMeta=$("#pdfrotate-preview-meta"),previewTitle=$("#pdfrotate-preview-title"),previewBody=$("#pdfrotate-preview-body"),langBtn=$("#pdfrotate-lang");
let language=new URLSearchParams(location.search).get("lang")==="en"?"en":"pt",angle=90,file=null,pdf=null,enginePromise=null,outputUrl=null;

const T={pt:{lead:"Gire todas as páginas ou apenas as páginas escolhidas. Veja a orientação antes de exportar e processe tudo localmente.",drop:"Adicionar PDF",sub:"Toque para selecionar um documento ou arraste-o para aqui",file:"Documento",rotation:"Rotação",pages:"Páginas",all:"Todas as páginas",range:"Intervalo personalizado",name:"Nome do ficheiro",summary:"Resumo",total:"Páginas",angle:"Ângulo",ready:"Pronto para receber um PDF.",preview:"Pré-visualização",previewReady:"Pronto para rodar",previewBody:"Escolha o ângulo e as páginas que deseja ajustar.",split:"Rodar PDF",clear:"Limpar",select:"Selecione um ficheiro PDF válido.",loading:"A carregar PDF",processing:"A rodar páginas",done:"PDF criado com sucesso.",error:"Não foi possível rodar o PDF.",engine:"O motor de PDF não conseguiu carregar.",download:"Baixar PDF",result:"PDF pronto",localTitle:"Rotation Lab",localBody:"A orientação é ajustada página a página sem sair do dispositivo.",flow:"Fluxo",flow1:"Escolher PDF",flow2:"Rodar",flow3:"Baixar",status:"Estado",translate:"English",back:"← PDF",footer:"Rodar PDF · Nexauren Tools",remove:"Remover",rangePlaceholder:"1-3,5,8-10"},
en:{lead:"Rotate all pages or only selected pages. Preview the orientation before exporting and process everything locally.",drop:"Add PDF",sub:"Tap to select a document or drag it here",file:"Document",rotation:"Rotation",pages:"Pages",all:"All pages",range:"Custom range",name:"File name",summary:"Summary",total:"Pages",angle:"Angle",ready:"Ready for a PDF.",preview:"Preview",previewReady:"Ready to rotate",previewBody:"Choose the angle and the pages you want to adjust.",split:"Rotate PDF",clear:"Clear",select:"Select a valid PDF file.",loading:"Loading PDF",processing:"Rotating pages",done:"PDF created successfully.",error:"Could not rotate the PDF.",engine:"The PDF engine could not be loaded.",download:"Download PDF",result:"PDF ready",localTitle:"Rotation Lab",localBody:"Orientation is adjusted page by page without leaving your device.",flow:"Flow",flow1:"Choose PDF",flow2:"Rotate",flow3:"Download",status:"Status",translate:"Português",back:"← PDF",footer:"Rotate PDF · Nexauren Tools",remove:"Remove",rangePlaceholder:"1-3,5,8-10"}};
const t=()=>T[language];
const msg=(v,e=false)=>{status.textContent=v;status.style.color=e?"var(--danger)":"var(--muted)"};
function set(s,v){const e=$(s);if(e)e.textContent=v}
function renderAngles(){document.querySelectorAll("[data-angle]").forEach(b=>b.classList.toggle("active",Number(b.dataset.angle)===angle));angleStat.textContent=angle+"°";sheet.style.transform="rotate("+angle+"deg)"}
function applyLanguage(){const x=t();document.documentElement.lang=language;set("#pdfrotate-lead",x.lead);set("#pdfrotate-drop-title",x.drop);set("#pdfrotate-drop-sub",x.sub);set("#pdfrotate-file-label",x.file);set("#pdfrotate-angle-label",x.rotation);set("#pdfrotate-pages-label",x.pages);set("#pdfrotate-all",x.all);set("#pdfrotate-range-option",x.range);set("#pdfrotate-preview-label",x.preview);set("#pdfrotate-preview-title",x.previewReady);set("#pdfrotate-preview-body",x.previewBody);set("#pdfrotate-name-label",x.name);set("#pdfrotate-quality-label",x.summary);set("#pdfrotate-total-label",x.total);set("#pdfrotate-angle-stat-label",x.angle);set("#pdfrotate-run",x.split);set("#pdfrotate-clear",x.clear);set("#pdfrotate-status",x.ready);set("#pdfrotate-result-label",x.result);set("#pdfrotate-download",x.download);set("#pdfrotate-side-title",x.localTitle);set("#pdfrotate-side-body",x.localBody);set("#pdfrotate-flow-title",x.flow);set("#pdfrotate-flow1",x.flow1);set("#pdfrotate-flow2",x.flow2);set("#pdfrotate-flow3",x.flow3);set("#pdfrotate-lang",x.translate);set(".pdfrotate-back",x.back);set(".pdfrotate-footer",x.footer);range.placeholder=x.rangePlaceholder;renderAngles()}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.async=true;s.onload=()=>window.PDFLib?.PDFDocument?resolve(window.PDFLib):reject(Error(t().engine));s.onerror=()=>reject(Error(t().engine));document.head.appendChild(s)})}
async function ensureEngine(){if(window.PDFLib?.PDFDocument)return window.PDFLib;if(enginePromise)return enginePromise;enginePromise=(async()=>{try{return await loadScript("https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js")}catch{}try{return await loadScript("https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js")}catch{}throw Error(t().engine)})();try{return await enginePromise}finally{enginePromise=null}}
function parseRange(v,max){const out=new Set();for(const raw of String(v||"").split(",")){const s=raw.trim();if(!s)continue;const m=s.match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw Error(language==="en"?"Invalid page range.":"Intervalo de páginas inválido.");const a=Number(m[1]),b=m[2]?Number(m[2]):a;if(a<1||b<1||a>max||b>max||a>b)throw Error(language==="en"?"The range is outside the PDF.":"O intervalo está fora do PDF.");for(let i=a;i<=b;i++)out.add(i)}return [...out].sort((a,b)=>a-b)}
function getPages(totalPages){if(pages.value==="all")return Array.from({length:totalPages},(_,i)=>i+1);return parseRange(range.value,totalPages)}
async function openFile(f){if(!f||(!/application\/pdf/i.test(f.type)&&!/\.pdf$/i.test(f.name))){msg(t().select,true);return}file=f;pdf=null;fileBar.hidden=false;fileName.textContent=f.name;fileSize.textContent=bytes(f.size);runBtn.disabled=true;total.textContent="…";previewMeta.textContent="";msg(t().loading+"…");try{const lib=await ensureEngine();pdf=await lib.PDFDocument.load(await f.arrayBuffer());total.textContent=String(pdf.getPageCount());previewMeta.textContent=pdf.getPageCount()+" "+t().pages.toLowerCase();runBtn.disabled=false;msg(t().ready)}catch(e){msg(e?.message||t().error,true)}}
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]}
async function rotate(){if(!pdf){msg(t().select,true);return}runBtn.disabled=true;clearBtn.disabled=true;progress.style.width="0%";result.hidden=true;try{const lib=await ensureEngine(),target=getPages(pdf.getPageCount()),out=await lib.PDFDocument.create();const copied=await out.copyPages(pdf,pdf.getPageIndices());const setPages=new Set(target);copied.forEach((p,i)=>{if(setPages.has(i+1))p.setRotation(lib.degrees(angle));out.addPage(p)});progress.style.width="80%";msg(t().processing+"…");const data=await out.save({useObjectStreams:false});if(outputUrl)URL.revokeObjectURL(outputUrl);const blob=new Blob([data],{type:"application/pdf"});outputUrl=URL.createObjectURL(blob);const safe=((nameInput.value.trim().replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"pdf-rodado")+".pdf");download.href=outputUrl;download.download=safe;document.querySelector("#pdfrotate-result-name").textContent=safe;document.querySelector("#pdfrotate-result-meta").textContent=bytes(blob.size)+" · "+target.length+" "+t().pages.toLowerCase();result.hidden=false;progress.style.width="100%";msg(t().done)}catch(e){msg(e?.message||t().error,true)}finally{runBtn.disabled=!pdf;clearBtn.disabled=false}}
window.__nexaurenRotatePdf=rotate;
input.addEventListener("change",e=>{openFile(e.target.files?.[0]);input.value=""});
drop.addEventListener("click",e=>{if(e.target!==input)input.click()});
drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});
drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));
drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");openFile(e.dataTransfer.files?.[0])});
document.querySelectorAll("[data-angle]").forEach(b=>b.addEventListener("click",()=>{angle=Number(b.dataset.angle);renderAngles()}));
pages.addEventListener("change",()=>{range.disabled=pages.value!=="range";if(pdf)msg(t().ready)});
clearBtn.addEventListener("click",()=>{file=null;pdf=null;runBtn.disabled=true;fileBar.hidden=true;total.textContent="0";previewMeta.textContent="";result.hidden=true;progress.style.width="0%";if(outputUrl){URL.revokeObjectURL(outputUrl);outputUrl=null}msg(t().ready)});
langBtn.addEventListener("click",()=>{language=language==="en"?"pt":"en";const u=new URL(location.href);if(language==="en")u.searchParams.set("lang","en");else u.searchParams.delete("lang");history.replaceState(null,"",u.pathname+(u.search||""));applyLanguage();msg(t().ready)});
pages.dispatchEvent(new Event("change"));applyLanguage();renderAngles();
})();