(() => {
  const root=document.querySelector("[data-account-app]"),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
  const api=async(path,opt={})=>{const r=await fetch(path,{credentials:"same-origin",...opt,headers:{"content-type":"application/json",...(opt.headers||{})}});const d=await r.json().catch(()=>({ok:false,error:"Resposta inválida."}));if(!r.ok){const e=new Error(d.error||"Pedido não concluído.");e.code=d.code;throw e}return d};
  function tabs(active){return '<div class="account-tabs"><button type="button" data-tab="login" class="'+(active==="login"?"active":"")+'">Entrar</button><button type="button" data-tab="register" class="'+(active==="register"?"active":"")+'">Criar conta</button></div>'}
  function loginView(){root.innerHTML=tabs("login")+'<form id="login-form"><label>Email<input id="email" type="email" autocomplete="email" required></label><label>Palavra-passe<input id="password" type="password" autocomplete="current-password" minlength="8" required></label><button class="primary" type="submit">Entrar</button><div class="error" id="error"></div><p class="hint">A conta é independente da área administrativa.</p></form>';wireTabs()}
  function registerView(){root.innerHTML=tabs("register")+'<form id="register-form"><label>Nome<input id="name" type="text" autocomplete="name" maxlength="80" required></label><label>Email<input id="email" type="email" autocomplete="email" required></label><label>Palavra-passe<input id="password" type="password" autocomplete="new-password" minlength="8" maxlength="128" required></label><label>Confirmar palavra-passe<input id="confirm" type="password" autocomplete="new-password" minlength="8" maxlength="128" required></label><button class="primary" type="submit">Criar conta</button><div class="error" id="error"></div><p class="hint">O cadastro básico já está preparado; recursos de verificação por email e recuperação podem ser ligados depois a um provedor de email.</p></form>';wireTabs()}
  function userView(a){root.innerHTML='<div class="account-user"><div class="eyebrow">CONTA ATIVA</div><div class="user-box"><div class="user-name">'+esc(a.display_name)+'</div><div class="user-email">'+esc(a.email)+'</div></div><div class="success">A sua sessão está ativa. Futuras ferramentas poderão usar esta conta para preferências, histórico e recursos personalizados.</div><button class="logout" id="logout">Terminar sessão</button></div>';document.getElementById("logout").onclick=async()=>{try{await api("/api/account/logout",{method:"POST",body:"{}"});location.reload()}catch(e){alert(e.message)}}}
  function wireTabs(){root.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>b.dataset.tab==="login"?loginView():registerView());
    document.getElementById("login-form")?.addEventListener("submit",async e=>{e.preventDefault();const er=document.getElementById("error");er.textContent="";try{await api("/api/account/login",{method:"POST",body:JSON.stringify({email:document.getElementById("email").value,password:document.getElementById("password").value})});location.reload()}catch(x){er.textContent=x.message}});
    document.getElementById("register-form")?.addEventListener("submit",async e=>{e.preventDefault();const er=document.getElementById("error");er.textContent="";const pw=document.getElementById("password").value,cf=document.getElementById("confirm").value;if(pw!==cf){er.textContent="As palavras-passe não coincidem.";return}try{await api("/api/account/register",{method:"POST",body:JSON.stringify({display_name:document.getElementById("name").value,email:document.getElementById("email").value,password:pw})});location.reload()}catch(x){er.textContent=x.message}});
  }
  async function init(){try{const d=await api("/api/account/me");if(d.authenticated)userView(d.account);else loginView()}catch(e){root.innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
  init();
})();