import { auth,onAuthStateChanged,getPlanState,verifyToolAccess } from "/tool/frontend/tool-access.js?v=20260925-converter4";
const $=s=>document.querySelector(s), state={files:[],results:[],pro:false,planReady:false,urls:[]};
const LIMITS={free:{batch:10,maxMB:15,maxMP:24,maxEdge:10000},pro:{batch:50,maxMB:75,maxMP:60,maxEdge:14000}};
const PRESETS={balanced:["image/webp",84,2560,2560],web:["image/webp",78,1920,1920],quality:["image/avif",92,3200,3200],small:["image/webp",68,1600,1600]};
const e={files:$("#files"),drop:$("#drop"),format:$("#format"),preset:$("#preset"),quality:$("#quality"),qualityOut:$("#qualityOut"),mw:$("#maxWidth"),mh:$("#maxHeight"),bg:$("#background"),naming:$("#naming"),fit:$("#fit"),rotation:$("#rotation"),flip:$("#flip"),effect:$("#effect"),removeBg:$("#removeBg"),tolerance:$("#tolerance"),toleranceOut:$("#toleranceOut"),convert:$("#convert"),downloadAll:$("#downloadAll"),clear:$("#clear"),status:$("#status"),queue:$("#queue"),results:$("#resultList"),count:$("#count"),formatStat:$("#formatStat"),qualityStat:$("#qualityStat"),limitStat:$("#limitStat"),sizeStat:$("#sizeStat"),transformStat:$("#transformStat"),plan:$("#plan"),planName:$("#planName"),planLimit:$("#planLimit")};
const lim=()=>state.pro?LIMITS.pro:LIMITS.free;
const ext=t=>t==="image/jpeg"?"jpg":t==="image/png"?"png":t==="image/avif"?"avif":"webp";
const bytes=n=>{if(!Number.isFinite(n))return "—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return `${v.toFixed(v>=100?0:v>=10?1:2)} ${u[i]}`};
const name=s=>String(s||"imagem").replace(/\.[^.]+$/i,"").replace(/[^a-zA-Z0-9À-ÿ _-]/g,"-").replace(/\s+/g,"-").replace(/-+/g,"-").slice(0,90)||"imagem";
function msg(t,error=false){e.status.textContent=t;e.status.style.color=error?"var(--forge-danger)":""}
function setPlan(){const x=lim();e.plan.classList.toggle("pro",state.pro);e.planName.textContent=state.pro?"NEXAUREN PRO":"NEXAUREN FREE";e.planLimit.textContent=`Até ${x.batch} imagens · ${x.maxMB} MB/ficheiro`;e.limitStat.textContent=`${x.batch} / lote`;e.sizeStat.textContent=`${x.maxMB} MB`}
function stats(){e.formatStat.textContent=ext(e.format.value).toUpperCase();e.qualityStat.textContent=e.quality.value+"%";const a=[];if(+e.rotation.value)a.push(e.rotation.value+"°");if(e.flip.value!=="none")a.push(e.flip.value==="h"?"Espelho H":e.flip.value==="v"?"Espelho V":"Espelho HV");if(e.effect.value==="grayscale")a.push("Cinza");if(e.removeBg.value!=="none")a.push("Fundo removido");e.transformStat.textContent=a.join(" · ")||"Original"}
async function plan(){try{const [p,a]=await Promise.all([getPlanState({force:true}),verifyToolAccess("image-converter")]);if(p?.pro===true){if(String(p.plan||"").toLowerCase()!=="pro"||String(p.status||"").toUpperCase()!=="ACTIVE"||a?.unlocked!==true||a?.error)throw Error("Não foi possível confirmar os recursos Pro.");state.pro=true}else state.pro=false;state.planReady=true;setPlan();e.convert.disabled=!state.files.length;msg(state.pro?"Pro ativo. Até 50 imagens por lote.":"Pronto. Até 10 imagens por lote.")}catch(x){state.planReady=false;e.convert.disabled=true;e.planName.textContent="Conta";e.planLimit.textContent="Não foi possível confirmar os recursos";e.limitStat.textContent="—";e.sizeStat.textContent="—";msg(x.message||"Não foi possível confirmar o plano.",true)}}
function clearUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function rebuild(){clearUrls();state.urls=state.files.map(f=>URL.createObjectURL(f))}
function renderQueue(){e.count.textContent=state.files.length;e.queue.replaceChildren();if(!state.files.length){e.queue.innerHTML='<div class="forge-empty">Nenhuma imagem selecionada.</div>';e.convert.disabled=true;return}state.files.forEach((f,i)=>{const r=document.createElement("div");r.className="forge-item";const im=document.createElement("img");im.className="forge-thumb";im.alt="";im.src=state.urls[i];const inf=document.createElement("div"),b=document.createElement("b"),s=document.createElement("small"),bt=document.createElement("button");b.textContent=f.name;s.textContent=`${bytes(f.size)} · ${f.type||"imagem"}`;inf.append(b,s);bt.className="forge-remove";bt.type="button";bt.textContent="Remover";bt.onclick=()=>{state.files.splice(i,1);rebuild();renderQueue()};r.append(im,inf,bt);e.queue.append(r)});e.convert.disabled=!state.planReady}
function add(list){const x=[...list].filter(f=>f&&(f.type?.startsWith("image/")||/\.(jpe?g|png|webp|avif|gif|bmp|heic|heif|tiff?)$/i.test(f.name||"")));if(!x.length)return msg("Selecione ficheiros de imagem válidos.",true);const L=lim(),room=Math.max(0,L.batch-state.files.length);if(room<=0)return msg(`O plano atual permite até ${L.batch} imagens por lote.`,true);let big=0,dup=0;const existing=new Set(state.files.map(f=>`${f.name}\u0000${f.size}\u0000${f.lastModified}`));for(const file of x.slice(0,room)){const key=`${file.name}\u0000${file.size}\u0000${file.lastModified}`;if(existing.has(key)){dup++;continue}existing.add(key);if(file.size>L.maxMB*1048576){big++;continue}state.files.push(file)}rebuild();renderQueue();const parts=[];if(big)parts.push(`${big} ficheiro(s) acima de ${L.maxMB} MB foram ignorados`);if(dup)parts.push(`${dup} duplicado(s) ignorado(s)`);msg(parts.length?parts.join(" · ")+".":`${state.files.length} imagem(ns) na fila.`,!!big)}
async function load(file){if(typeof createImageBitmap==="function"){try{return await createImageBitmap(file,{imageOrientation:"from-image",colorSpaceConversion:"default"})}catch{}try{return await createImageBitmap(file)}catch{}}return new Promise((ok,no)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);ok(im)};im.onerror=()=>{URL.revokeObjectURL(u);const r=new FileReader();r.onload=()=>{const z=new Image();z.onload=()=>ok(z);z.onerror=()=>no(Error("O navegador não conseguiu descodificar esta imagem. O ficheiro pode usar um PNG/codec que este navegador não suporta."));z.src=r.result};r.onerror=()=>no(Error("Não foi possível ler a imagem. O navegador recusou o acesso ao ficheiro."));try{r.readAsDataURL(file)}catch(x){no(Error("Não foi possível ler a imagem: "+(x?.message||"erro de leitura")))}};im.src=u})}
function target(w,h,mw,mh){const s=Math.min(1,mw/w,mh/h);return [Math.max(1,Math.round(w*s)),Math.max(1,Math.round(h*s))]}
function canvas(w,h){if(w*h>32000000)throw Error("A dimensão final excede a capacidade segura deste dispositivo. Reduza a largura ou altura máxima.");const c=document.createElement("canvas");c.width=w;c.height=h;return c}
function blob(c,t,q){return new Promise((ok,no)=>{try{c.toBlob(b=>b?ok(b):no(Error("Formato não suportado neste navegador.")),t,q)}catch(x){no(x)}})}
async function encode(c,t,q){try{return await blob(c,t,q)}catch(x){if(t==="image/avif")return await blob(c,"image/webp",q);if(t==="image/webp")return await blob(c,"image/png",q);throw x}}
function removeBackground(ctx,w,h,tolerance){const image=ctx.getImageData(0,0,w,h),d=image.data,seen=new Uint8Array(w*h),queue=[];const samples=[];for(const [x,y] of [[0,0],[w-1,0],[0,h-1],[w-1,h-1]]){const i=(y*w+x)*4;samples.push([d[i],d[i+1],d[i+2]])}const bg=samples.reduce((a,v)=>[a[0]+v[0],a[1]+v[1],a[2]+v[2]],[0,0,0]).map(v=>v/4);const threshold=Math.max(8,Number(tolerance)||32)*2.2;const similar=i=>Math.hypot(d[i]-bg[0],d[i+1]-bg[1],d[i+2]-bg[2])<=threshold;const seed=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return;const p=y*w+x;if(seen[p]||!similar(p*4))return;seen[p]=1;queue.push(p)};for(const [x,y] of [[0,0],[w-1,0],[0,h-1],[w-1,h-1]])seed(x,y);while(queue.length){const p=queue.pop(),x=p%w,y=(p-x)/w;d[p*4+3]=0;seed(x+1,y);seed(x-1,y);seed(x,y+1);seed(x,y-1)}ctx.putImageData(image,0,0)}
async function convert(file){const L=lim();if(file.size>L.maxMB*1048576)throw Error(`Ficheiro acima de ${L.maxMB} MB.`);const im=await load(file);try{const w0=im.width||im.naturalWidth,h0=im.height||im.naturalHeight;if(!w0||!h0)throw Error("Não foi possível obter as dimensões da imagem.");const mp=w0*h0/1e6;if(mp>L.maxMP)throw Error(`Imagem com ${mp.toFixed(1)} MP; limite do plano: ${L.maxMP} MP.`);if(Math.max(w0,h0)>L.maxEdge)throw Error(`Dimensão original acima de ${L.maxEdge}px.`);const [bw,bh]=target(w0,h0,Math.min(L.maxEdge,+e.mw.value||2560),Math.min(L.maxEdge,+e.mh.value||2560));const rot=+e.rotation.value||0,swap=rot===90||rot===270,w=swap?bh:bw,h=swap?bw:bh,c=canvas(w,h),ctx=c.getContext("2d",{willReadFrequently:e.removeBg.value!=="none"});if(!ctx)throw Error("O navegador não conseguiu iniciar o processamento.");const type=e.format.value;if(type==="image/jpeg"){ctx.fillStyle=e.bg.value==="#000000"?"#000000":"#ffffff";ctx.fillRect(0,0,w,h)}ctx.save();ctx.translate(w/2,h/2);ctx.rotate(rot*Math.PI/180);ctx.scale(e.flip.value==="h"||e.flip.value==="both"?-1:1,e.flip.value==="v"||e.flip.value==="both"?-1:1);if(e.effect.value==="grayscale")ctx.filter="grayscale(1)";ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(im,-bw/2,-bh/2,bw,bh);ctx.restore();if(e.removeBg.value!=="none")removeBackground(ctx,w,h,e.tolerance.value);const b=await encode(c,type,+e.quality.value/100);const actual=b.type||type;let n=name(file.name);if(e.naming.value==="suffix")n+="-nexauren";if(e.naming.value==="converted")n+="-converted";if(e.removeBg.value!=="none")n+="-sem-fundo";return {blob:b,name:`${n}.${ext(actual)}`,w,h,fallback:actual!==type}}finally{im.close?.()}}
function renderResults(){e.downloadAll.disabled=!state.results.length;e.results.replaceChildren();if(!state.results.length){e.results.innerHTML='<div class="forge-empty">Os resultados aparecerão aqui.</div>';return}state.results.forEach(r=>{const row=document.createElement("div");row.className="forge-result";const info=document.createElement("div"),b=document.createElement("b"),s=document.createElement("small"),bt=document.createElement("button");b.textContent=r.name;s.textContent=`${r.w}×${r.h} · ${bytes(r.blob.size)}${r.fallback?" · WebP fallback":""}`;info.append(b,s);bt.className="forge-btn";bt.textContent="Baixar";bt.onclick=()=>download(r);row.append(info,bt);e.results.append(row)})}
function download(r){const u=URL.createObjectURL(r.blob),a=document.createElement("a");a.href=u;a.download=r.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
async function run(){if(!state.planReady)return msg("Aguarde a confirmação da conta.",true);if(!state.files.length)return msg("Adicione uma imagem.",true);state.results=[];const errors=[];renderResults();e.convert.disabled=true;msg(`A processar 0/${state.files.length}…`);for(let i=0;i<state.files.length;i++){const file=state.files[i];try{state.results.push(await convert(file))}catch(x){errors.push(`${file.name}: ${x?.message||"falha desconhecida"}`)}renderResults();msg(`A processar ${i+1}/${state.files.length}…`);await new Promise(requestAnimationFrame)}e.convert.disabled=false;if(state.results.length&&errors.length)msg(`${state.results.length} convertida(s) · ${errors.length} falha(s): ${errors.join(" | ")}`,true);else if(state.results.length)msg(`${state.results.length} imagem(ns) convertida(s) com sucesso.`);else msg(errors.length?errors.join(" | "):"Nenhuma imagem pôde ser convertida.",true)}
function preset(){const p=PRESETS[e.preset.value];if(!p)return;e.format.value=p[0];e.quality.value=p[1];e.qualityOut.textContent=p[1]+"%";e.mw.value=p[2];e.mh.value=p[3];stats()}
e.files.onchange=x=>{add(x.target.files);x.target.value=""};e.drop.ondragover=x=>{x.preventDefault();e.drop.classList.add("drag")};e.drop.ondragleave=()=>e.drop.classList.remove("drag");e.drop.ondrop=x=>{x.preventDefault();e.drop.classList.remove("drag");add(x.dataTransfer.files)};e.preset.onchange=()=>{if(e.preset.value!=="custom")preset()};e.quality.oninput=()=>{e.qualityOut.textContent=e.quality.value+"%";e.preset.value="custom";stats()};e.tolerance.oninput=()=>{e.toleranceOut.textContent=e.tolerance.value;stats()};["format","mw","mh","bg","naming","fit","rotation","flip","effect","removeBg"].forEach(k=>e[k].onchange=()=>{if(k!=="format")e.preset.value="custom";stats()});e.convert.onclick=run;e.downloadAll.onclick=()=>state.results.forEach((r,i)=>setTimeout(()=>download(r),i*160));e.clear.onclick=()=>{state.files=[];state.results=[];clearUrls();renderQueue();renderResults();msg("Lote limpo.")};window.addEventListener("beforeunload",clearUrls);stats();preset();onAuthStateChanged(auth,async u=>{if(!u){state.planReady=false;state.pro=false;setPlan();e.convert.disabled=true;msg("Entre na sua conta para usar o Image Forge.",true);return}await plan()});