(()=>{
"use strict";
const $=s=>document.querySelector(s);
const q=new URLSearchParams(location.search).get("lang");
const language=q==="en"?"en":"pt";
const ui=language==="en"?{lang:"Português",lead:"Combine one or more PNG images into a single PDF. Adjust page, margins, orientation and quality directly in your browser.",local:"LOCAL",localCopy:"Browser processing",add:"Add PNGs",sub:"Tap to choose images or drag them here",page:"Page",orientation:"Orientation",auto:"Automatic",portrait:"Portrait",landscape:"Landscape",fit:"Fit",contain:"Fit inside",cover:"Fill page",original:"Original size",margin:"Margin",quality:"Quality",name:"PDF name",create:"Create PDF",clear:"Clear queue",ready:"Ready.",empty:"No PNG images selected.",result:"PDF ready",download:"Download PDF",panel:"Panel",images:"Images",pages:"Pages",pdf:"PDF",privacy:"Privacy",privacyBody:"Images are processed locally on your device.",tip:"Tip",tipBody:"Use Original size when you want to preserve the image dimensions.",processing:"Processing",done:"PDF created successfully.",select:"Select PNG files.",invalid:"Invalid PNG image.",error:"Could not create the PDF."}:{lang:"English",lead:"Junte uma ou várias imagens PNG num único PDF. Ajuste página, margem, orientação e qualidade diretamente no navegador.",local:"LOCAL",localCopy:"Processamento no navegador",add:"Adicionar PNGs",sub:"Toque para escolher imagens ou arraste-as para aqui",page:"Página",orientation:"Orientação",auto:"Automática",portrait:"Retrato",landscape:"Paisagem",fit:"Ajuste",contain:"Encaixar",cover:"Preencher",original:"Tamanho original",margin:"Margem",quality:"Qualidade",name:"Nome do PDF",create:"Criar PDF",clear:"Limpar fila",ready:"Pronto.",empty:"Nenhuma imagem PNG selecionada.",result:"PDF pronto",download:"Baixar PDF",panel:"Painel",images:"Imagens",pages:"Páginas",pdf:"PDF",privacy:"Privacidade",privacyBody:"As imagens são processadas localmente no dispositivo.",tip:"Dica",tipBody:"Use Tamanho original quando quiser preservar as dimensões da imagem.",processing:"A processar",done:"PDF criado com sucesso.",select:"Selecione ficheiros PNG.",invalid:"Imagem PNG inválida.",error:"Não foi possível criar o PDF."};
const fileInput=$("#pngpdf-files"),drop=$(".pngpdf-upload"),create=$("#pngpdf-create"),clear=$("#pngpdf-clear"),status=$("#pngpdf-status"),queue=$("#pngpdf-queue"),count=$("#pngpdf-count"),pages=$("#pngpdf-pages"),size=$("#pngpdf-size"),margin=$("#pngpdf-margin"),marginOut=$("#pngpdf-margin-out"),quality=$("#pngpdf-quality"),qualityOut=$("#pngpdf-quality-out"),pageSize=$("#pngpdf-page"),orientation=$("#pngpdf-orientation"),fit=$("#pngpdf-fit"),name=$("#pngpdf-name"),progress=$("#pngpdf-progress"),result=$("#pngpdf-result"),resultName=$("#pngpdf-result-name"),resultSize=$("#pngpdf-result-size"),download=$("#pngpdf-download"),app=$("#pngpdf-app");
let files=[],urls=[],output=null;
function set(id,v){const e=$(id);if(e)e.textContent=v}
function apply(){document.documentElement.lang=language;set("#pngpdf-lang",ui.lang);set("#pngpdf-lead",ui.lead);set("#pngpdf-badge-title",ui.local);set("#pngpdf-badge-copy",ui.localCopy);set("#pngpdf-drop-title",ui.add);set("#pngpdf-drop-sub",ui.sub);set("#pngpdf-page-label",ui.page);set("#pngpdf-orientation-label",ui.orientation);set("#pngpdf-fit-label",ui.fit);set("#pngpdf-margin-label",ui.margin+" ");set("#pngpdf-quality-label",ui.quality+" ");set("#pngpdf-name-label",ui.name);set("#pngpdf-create",ui.create);set("#pngpdf-clear",ui.clear);set("#pngpdf-status",ui.ready);set("#pngpdf-empty",ui.empty);set("#pngpdf-result-label",ui.result);set("#pngpdf-download",ui.download);set("#pngpdf-side-title",ui.panel);set("#pngpdf-count-label",ui.images);set("#pngpdf-pages-label",ui.pages);set("#pngpdf-size-label",ui.pdf);set("#pngpdf-note-title",ui.privacy);set("#pngpdf-note-body",ui.privacyBody);set("#pngpdf-hint-title",ui.tip);set("#pngpdf-hint-body",ui.tipBody);set("#pngpdf-orientation-auto",ui.auto);set("#pngpdf-orientation-portrait",ui.portrait);set("#pngpdf-orientation-landscape",ui.landscape);set("#pngpdf-fit-contain",ui.contain);set("#pngpdf-fit-cover",ui.cover);set("#pngpdf-fit-original",ui.original);marginOut.textContent=margin.value+" pt";qualityOut.textContent=quality.value+"%"}
function msg(v,err=false){status.textContent=v;status.style.color=err?"var(--danger)":"var(--muted)"}
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0;while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(n>=100?0:n>=10?1:2)+" "+u[i]}
function clean(){urls.forEach(URL.revokeObjectURL);urls=[]}
function render(){clean();urls=files.map(f=>URL.createObjectURL(f));queue.replaceChildren();count.textContent=files.length;pages.textContent=files.length;create.disabled=!files.length;if(!files.length){const d=document.createElement("div");d.className="pngpdf-empty";d.textContent=ui.empty;queue.append(d);return}files.forEach((f,i)=>{const row=document.createElement("div");row.className="pngpdf-item";const im=document.createElement("img");im.className="pngpdf-thumb";im.src=urls[i];im.alt=f.name;const info=document.createElement("div"),b=document.createElement("b"),s=document.createElement("small");b.textContent=f.name;s.textContent=bytes(f.size);info.append(b,s);const rm=document.createElement("button");rm.className="pngpdf-remove";rm.type="button";rm.textContent=language==="en"?"Remove":"Remover";rm.onclick=()=>{files.splice(i,1);render();msg(files.length?ui.ready:ui.empty)};row.append(im,info,rm);queue.append(row)})}
function add(list){const a=[...list].filter(f=>f&&(/\.png$/i.test(f.name)||f.type==="image/png"));if(!a.length){msg(ui.select,true);return}files.push(...a);render();msg(ui.ready)}
function load(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=()=>{URL.revokeObjectURL(u);rej(Error(ui.invalid))};im.src=u})}
function box(w,h){let b=pageSize.value==="letter"?{w:612,h:792}:{w:595.28,h:841.89};if(pageSize.value==="original")return{w:Math.max(72,Math.min(1440,w*.75)),h:Math.max(72,Math.min(1440,h*.75))};if(orientation.value==="landscape"||(orientation.value==="auto"&&w>h))b={w:b.h,h:b.w};return b}
function jpeg(im){return new Promise((res,rej)=>{const c=document.createElement("canvas");c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext("2d");if(!x)return rej(Error(ui.error));x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0);c.toBlob(async b=>b?res({data:new Uint8Array(await b.arrayBuffer()),w:c.width,h:c.height}):rej(Error(ui.error)),"image/jpeg",+quality.value/100)})}
const enc=s=>new TextEncoder().encode(s);
function join(a){let n=0;a.forEach(x=>n+=x.length);const o=new Uint8Array(n);let p=0;a.forEach(x=>{o.set(x,p);p+=x.length});return o}
function makePDF(items){const objs=[{n:1,t:"<< /Type /Catalog /Pages 2 0 R >>"}],ids=[];items.forEach((im,i)=>{const p=3+i*3,x=4+i*3,c=5+i*3;ids.push(p);const stream=`q\n${im.dw.toFixed(2)} 0 0 ${im.dh.toFixed(2)} ${im.dx.toFixed(2)} ${im.dy.toFixed(2)} cm\n/Im0 Do\nQ\n`;objs.push({n:p,t:`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${im.pw.toFixed(2)} ${im.ph.toFixed(2)}] /Resources << /XObject << /Im0 ${x} 0 R >> >> /Contents ${c} 0 R >>`},{n:x,img:im.data,w:im.w,h:im.h},{n:c,s:stream})});objs.splice(1,0,{n:2,t:`<< /Type /Pages /Kids [${ids.map(x=>x+" 0 R").join(" ")}] /Count ${ids.length} >>`});let parts=[enc("%PDF-1.4\n%Nexauren PNG Lab\n")],pos=parts[0].length,off=[];for(const o of objs){off[o.n]=pos;let h=enc(o.n+" 0 obj\n");parts.push(h);pos+=h.length;if(o.img){const d=enc(`<< /Type /XObject /Subtype /Image /Width ${o.w} /Height ${o.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${o.img.length} >>\nstream\n`),z=enc("\nendstream\nendobj\n");parts.push(d,o.img,z);pos+=d.length+o.img.length+z.length}else if(o.s){const d=enc(`<< /Length ${enc(o.s).length} >>\nstream\n`),s=enc(o.s),z=enc("endstream\nendobj\n");parts.push(d,s,z);pos+=d.length+s.length+z.length}else{const b=enc(o.t+"\nendobj\n");parts.push(b);pos+=b.length}}const start=pos,sz=objs.length+1;let x="xref\n0 "+sz+"\n0000000000 65535 f \n";for(let i=1;i<sz;i++)x+=String(off[i]).padStart(10,"0")+" 00000 n \n";x+=`trailer\n<< /Size ${sz} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`;parts.push(enc(x));return new Blob([join(parts)],{type:"application/pdf"})}
function filename(){return (name.value.trim().replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"png-to-pdf")+".pdf"}
function save(blob,n){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=n;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function build(){if(!files.length){msg(ui.empty,true);return}create.disabled=true;clear.disabled=true;result.hidden=true;progress.style.width="0%";try{const items=[];for(let i=0;i<files.length;i++){msg(`${ui.processing} ${i+1}/${files.length}…`);const im=await load(files[i]),j=await jpeg(im),p=box(j.w,j.h),m=pageSize.value==="original"?0:+margin.value,fw=p.w-m*2,fh=p.h-m*2;let dw=j.w*.75,dh=j.h*.75,s=fit.value==="cover"?Math.max(fw/dw,fh/dh):Math.min(fw/dw,fh/dh);if(fit.value==="original")s=Math.min(1,fw/dw,fh/dh);dw*=s;dh*=s;items.push({data:j.data,w:j.w,h:j.h,pw:p.w,ph:p.h,dw,dh,dx:(p.w-dw)/2,dy:(p.h-dh)/2});progress.style.width=Math.round((i+1)/files.length*80)+"%";await new Promise(requestAnimationFrame)}output=makePDF(items);const n=filename();resultName.textContent=n;resultSize.textContent=bytes(output.size);size.textContent=bytes(output.size);progress.style.width="100%";result.hidden=false;download.onclick=()=>save(output,n);msg(ui.done)}catch(e){msg(e.message||ui.error,true)}finally{create.disabled=!files.length;clear.disabled=false}}
fileInput.onchange=e=>{add(e.target.files);fileInput.value=""};drop.ondragover=e=>{e.preventDefault();drop.classList.add("drag")};drop.ondragleave=()=>drop.classList.remove("drag");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("drag");add(e.dataTransfer.files)};create.onclick=build;clear.onclick=()=>{files=[];output=null;clean();render();result.hidden=true;size.textContent="—";progress.style.width="0%";msg(ui.empty)};margin.oninput=()=>marginOut.textContent=margin.value+" pt";quality.oninput=()=>qualityOut.textContent=quality.value+"%";
apply();app.classList.remove("pngpdf-hide");create.disabled=true;
})();