import {auth,onAuthStateChanged} from "/tool/frontend/tool-access.js?v=20260926-free-1";
(()=>{
"use strict";
const language=(()=>{const q=new URLSearchParams(location.search).get("lang");if(q==="en")return"en";try{return localStorage.getItem("ns_lang")==="en"?"en":"pt"}catch{return"pt"}})();
const ui=language==="en"?{back:"← PDF",translate:"Português",lead:"Combine one or more PNG images into a single PDF. Adjust page, margins, orientation, and quality without uploading files to a server.",local:"LOCAL",localCopy:"Browser processing",add:"Add PNGs",sub:"Tap to choose images or drag them here",page:"Page",orientation:"Orientation",auto:"Automatic",portrait:"Portrait",landscape:"Landscape",fit:"Fit",contain:"Fit inside",cover:"Fill page",original:"Original size",margin:"Margin",quality:"Quality",name:"PDF name",create:"Create PDF",clear:"Clear queue",ready:"Ready.",empty:"No PNG images selected.",result:"PDF ready",download:"Download PDF",summary:"Panel",images:"Images",pages:"Pages",pdf:"PDF",privacy:"Privacy",privacyBody:"Images are processed locally on your device.",tip:"Tip",tipBody:"Use “Original size” when you want to keep the image dimensions.",processing:"Processing",done:"PDF created successfully.",error:"Could not create the PDF.",account:"Sign in to use this tool",accountBody:"Nexauren tools are available to authenticated users.",signIn:"Sign in or create an account"}:{back:"← PDF",translate:"English",lead:"Junte uma ou várias imagens PNG num único PDF. Ajuste página, margem, orientação e qualidade sem enviar os ficheiros para um servidor.",local:"LOCAL",localCopy:"Processamento no navegador",add:"Adicionar PNGs",sub:"Toque para escolher imagens ou arraste-as para aqui",page:"Página",orientation:"Orientação",auto:"Automática",portrait:"Retrato",landscape:"Paisagem",fit:"Ajuste",contain:"Encaixar",cover:"Preencher",original:"Tamanho original",margin:"Margem",quality:"Qualidade",name:"Nome do PDF",create:"Criar PDF",clear:"Limpar fila",ready:"Pronto.",empty:"Nenhuma imagem PNG selecionada.",result:"PDF pronto",download:"Baixar PDF",summary:"Painel",images:"Imagens",pages:"Páginas",pdf:"PDF",privacy:"Privacidade",privacyBody:"As imagens são processadas localmente no dispositivo.",tip:"Dica",tipBody:"Use “Tamanho original” quando quiser manter o desenho no tamanho da imagem.",processing:"A processar",done:"PDF criado com sucesso.",error:"Não foi possível criar o PDF.",account:"Entre para usar esta ferramenta",accountBody:"As ferramentas Nexauren estão disponíveis para utilizadores autenticados.",signIn:"Entrar ou criar conta"};
const $=s=>document.querySelector(s),fileInput=$("#pngpdf-files"),drop=$(".pngpdf-upload"),app=$("#pngpdf-app"),gate=$("#pngpdf-gate"),langBtn=$("#pngpdf-lang"),create=$("#pngpdf-create"),clear=$("#pngpdf-clear"),status=$("#pngpdf-status"),queue=$("#pngpdf-queue"),count=$("#pngpdf-count"),pageCount=$("#pngpdf-pages"),sizeStat=$("#pngpdf-size"),margin=$("#pngpdf-margin"),marginOut=$("#pngpdf-margin-out"),quality=$("#pngpdf-quality"),qualityOut=$("#pngpdf-quality-out"),pageSize=$("#pngpdf-page"),orientation=$("#pngpdf-orientation"),fit=$("#pngpdf-fit"),nameInput=$("#pngpdf-name"),progress=$("#pngpdf-progress"),result=$("#pngpdf-result"),resultName=$("#pngpdf-result-name"),resultSize=$("#pngpdf-result-size"),downloadBtn=$("#pngpdf-download");
let state={files:[],ready:false,output:null,urls:[]};
function set(id,v){const e=$(id);if(e)e.textContent=v}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[m]))}
function msg(v,error=false){status.textContent=v;status.style.color=error?"var(--danger)":"var(--muted)"}
function applyLanguage(){document.documentElement.lang=language;set("#pngpdf-back",ui.back);set("#pngpdf-lang",ui.translate);set("#pngpdf-lead",ui.lead);set("#pngpdf-badge-title",ui.local);set("#pngpdf-badge-copy",ui.localCopy);set("#pngpdf-drop-title",ui.add);set("#pngpdf-drop-sub",ui.sub);set("#pngpdf-page-label",ui.page);set("#pngpdf-orientation-label",ui.orientation);set("#pngpdf-fit-label",ui.fit);set("#pngpdf-margin-label",ui.margin+" ");set("#pngpdf-quality-label",ui.quality+" ");set("#pngpdf-name-label",ui.name);set("#pngpdf-create",ui.create);set("#pngpdf-clear",ui.clear);set("#pngpdf-status",ui.ready);set("#pngpdf-empty",ui.empty);set("#pngpdf-result-label",ui.result);set("#pngpdf-download",ui.download);set("#pngpdf-side-title",ui.summary);set("#pngpdf-count-label",ui.images);set("#pngpdf-pages-label",ui.pages);set("#pngpdf-size-label",ui.pdf);set("#pngpdf-note-title",ui.privacy);set("#pngpdf-note-body",ui.privacyBody);set("#pngpdf-hint-title",ui.tip);set("#pngpdf-hint-body",ui.tipBody);set("#pngpdf-page-a4","A4");set("#pngpdf-page-letter","Letter");set("#pngpdf-page-original","Original");set("#pngpdf-orientation-auto",ui.auto);set("#pngpdf-orientation-portrait",ui.portrait);set("#pngpdf-orientation-landscape",ui.landscape);set("#pngpdf-fit-contain",ui.contain);set("#pngpdf-fit-cover",ui.cover);set("#pngpdf-fit-original",ui.original);updateReadouts()}
function updateReadouts(){marginOut.textContent=margin.value+" pt";qualityOut.textContent=quality.value+"%"}
function setGate(){gate.hidden=false;gate.innerHTML='<h2>'+esc(ui.account)+'</h2><p>'+esc(ui.accountBody)+'</p><a class="pngpdf-btn primary" href="/account">'+esc(ui.signIn)+'</a>';app.classList.add("pngpdf-hide")}
function openApp(){gate.hidden=true;app.classList.remove("pngpdf-hide")}
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]}
function cleanUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function rebuildUrls(){cleanUrls();state.urls=state.files.map(f=>URL.createObjectURL(f))}
function renderQueue(){count.textContent=String(state.files.length);queue.replaceChildren();if(!state.files.length){const d=document.createElement("div");d.className="pngpdf-empty";d.textContent=ui.empty;queue.append(d);create.disabled=!state.ready;return}state.files.forEach((f,i)=>{const row=document.createElement("div");row.className="pngpdf-item";const im=document.createElement("img");im.className="pngpdf-thumb";im.src=state.urls[i];im.alt=f.name;const info=document.createElement("div");const b=document.createElement("b"),s=document.createElement("small");b.textContent=f.name;s.textContent=bytes(f.size);info.append(b,s);const rm=document.createElement("button");rm.className="pngpdf-remove";rm.type="button";rm.textContent=language==="en"?"Remove":"Remover";rm.onclick=()=>{state.files.splice(i,1);rebuildUrls();renderQueue();msg(state.files.length?ui.ready:ui.empty)};row.append(im,info,rm);queue.append(row)})}
function add(list){const incoming=[...(list||[])].filter(f=>f&&(/\.png$/i.test(f.name)||f.type==="image/png"));if(!incoming.length){msg(language==="en"?"Select PNG files.":"Selecione ficheiros PNG.",true);return}state.files=[...state.files,...incoming];rebuildUrls();renderQueue();msg(ui.ready)}
function loadImage(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);resolve(im)};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error(language==="en"?"Invalid PNG image.":"Imagem PNG inválida."))};im.src=u})}
function pageBox(w,h){const unit=72/96;let box;if(pageSize.value==="original"){box={w:Math.max(72,Math.min(1440,w*unit)),h:Math.max(72,Math.min(1440,h*unit))}}else{box=pageSize.value==="letter"?{w:612,h:792}:{w:595.28,h:841.89};const landscape=orientation.value==="landscape"||(orientation.value==="auto"&&w>h);if(landscape)box={w:box.h,h:box.w}}return box}
function layout(w,h){const mb=pageBox(w,h),m=pageSize.value==="original"?0:Math.max(0,Math.min(72,+margin.value||0));const fw=Math.max(1,mb.w-m*2),fh=Math.max(1,mb.h-m*2);let dw=w*72/96,dh=h*72/96;if(fit.value==="original"){const s=Math.min(1,fw/dw,fh/dh);dw*=s;dh*=s}else if(fit.value==="cover"){const s=Math.max(fw/dw,fh/dh);dw*=s;dh*=s}else{const s=Math.min(fw/dw,fh/dh);dw*=s;dh*=s}return{mediaBox:mb,draw:{w:dw,h:dh,x:(mb.w-dw)/2,y:(mb.h-dh)/2}}}
function canvasJpeg(image,q){const w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h)throw Error(language==="en"?"Could not read image dimensions.":"Não foi possível ler as dimensões da imagem.");const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:false});if(!ctx)throw Error(language==="en"?"Canvas is unavailable.":"O navegador não conseguiu iniciar o processamento.");ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(image,0,0,w,h);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve({blob:b,w,h}):reject(new Error(language==="en"?"Could not encode image.":"Não foi possível processar a imagem.")),"image/jpeg",q))}
function textBytes(s){return new TextEncoder().encode(s)}
function concat(parts){const total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total);let p=0;for(const x of parts){out.set(x,p);p+=x.length}return out}
function pdfFromImages(images){const objects=[{num:1,text:"<< /Type /Catalog /Pages 2 0 R >>"}],pageIds=[];images.forEach((im,i)=>{const p=3+i*3,x=4+i*3,c=5+i*3;pageIds.push(p);const stream="q\n"+im.draw.w.toFixed(2)+" 0 0 "+im.draw.h.toFixed(2)+" "+im.draw.x.toFixed(2)+" "+im.draw.y.toFixed(2)+" cm\n/Im0 Do\nQ\n";objects.push({num:p,text:"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "+im.mediaBox.w.toFixed(2)+" "+im.mediaBox.h.toFixed(2)+"] /Resources << /XObject << /Im0 "+x+" 0 R >> >> /Contents "+c+" 0 R >>"});objects.push({num:x,image:im.jpeg,w:im.w,h:im.h});objects.push({num:c,stream})});objects.splice(1,0,{num:2,text:"<< /Type /Pages /Kids ["+pageIds.map(n=>n+" 0 R").join(" ")+"] /Count "+pageIds.length+" >>"});const chunks=[textBytes("%PDF-1.4\n%Nexauren PNG Lab\n")],offsets=[],header=chunks[0];let pos=header.length;for(const o of objects){offsets[o.num]=pos;const head=textBytes(o.num+" 0 obj\n");chunks.push(head);pos+=head.length;if(o.image){const dict=textBytes("<<\n/Type /XObject\n/Subtype /Image\n/Width "+o.w+"\n/Height "+o.h+"\n/ColorSpace /DeviceRGB\n/BitsPerComponent 8\n/Filter /DCTDecode\n/Length "+o.image.length+"\n>>\nstream\n"),tail=textBytes("\nendstream\nendobj\n");chunks.push(dict,o.image,tail);pos+=dict.length+o.image.length+tail.length}else if(o.stream){const data=textBytes(o.stream),dict=textBytes("<< /Length "+data.length+" >>\nstream\n"),tail=textBytes("endstream\nendobj\n");chunks.push(dict,data,tail);pos+=dict.length+data.length+tail.length}else{const body=textBytes(o.text+"\nendobj\n");chunks.push(body);pos+=body.length}}const xrefPos=pos,size=objects.length+1;let xref="xref\n0 "+size+"\n0000000000 65535 f \n";for(let i=1;i<size;i++)xref+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";xref+="trailer\n<< /Size "+size+" /Root 1 0 R >>\nstartxref\n"+xrefPos+"\n%%EOF\n";chunks.push(textBytes(xref));return new Blob([concat(chunks)],{type:"application/pdf"})}
function safeName(v){return String(v||"png-to-pdf").replace(/[^a-z0-9_-]+/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"png-to-pdf"}
function save(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function build(){if(!state.ready)return msg(language==="en"?"Access is not ready yet.":"O acesso ainda não está pronto.",true);if(!state.files.length)return msg(ui.empty,true);create.disabled=true;clear.disabled=true;result.hidden=true;progress.style.width="0%";try{const imgs=[];for(let i=0;i<state.files.length;i++){msg(ui.processing+" "+(i+1)+"/"+state.files.length+"…");const image=await loadImage(state.files[i]),enc=await canvasJpeg(image,+quality.value/100),spec=layout(enc.w,enc.h),jpeg=new Uint8Array(await enc.blob.arrayBuffer());imgs.push({jpeg,w:enc.w,h:enc.h,mediaBox:spec.mediaBox,draw:spec.draw});progress.style.width=Math.round((i+1)/state.files.length*75)+"%";await new Promise(requestAnimationFrame)}const pdf=pdfFromImages(imgs),filename=safeName(nameInput.value)+".pdf";state.output={blob:pdf,name:filename};resultName.textContent=filename;resultSize.textContent=bytes(pdf.size);sizeStat.textContent=bytes(pdf.size);pageCount.textContent=String(state.files.length);progress.style.width="100%";downloadBtn.onclick=()=>save(pdf,filename);result.hidden=false;msg(ui.done)}catch(e){msg(e?.message||ui.error,true);progress.style.width="0%"}finally{create.disabled=!state.ready;clear.disabled=false}}
fileInput.addEventListener("change",e=>{add(e.target.files);fileInput.value=""});
drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");add(e.dataTransfer.files)});
margin.addEventListener("input",updateReadouts);quality.addEventListener("input",updateReadouts);
clear.addEventListener("click",()=>{state.files=[];state.output=null;cleanUrls();queue.replaceChildren();const d=document.createElement("div");d.className="pngpdf-empty";d.textContent=ui.empty;queue.append(d);count.textContent="0";pageCount.textContent="0";sizeStat.textContent="—";result.hidden=true;progress.style.width="0%";msg(ui.empty);create.disabled=!state.ready});
langBtn.addEventListener("click",()=>{try{localStorage.setItem("ns_lang",language==="en"?"pt":"en")}catch{}const u=new URL(location.href);if(language==="en")u.searchParams.delete("lang");else u.searchParams.set("lang","en");location.href=u.pathname+u.search});
applyLanguage();
onAuthStateChanged(auth,user=>{if(!user){state.ready=false;create.disabled=true;setGate();return}openApp();state.ready=true;create.disabled=!state.files.length;msg(ui.ready)});
})();