(()=>{"use strict";
const $=s=>document.querySelector(s);
const state={file:null,img:null,url:null,thickness:24,padding:24,radius:0,border:"#1f2937",bg:"#f7f5ef",style:"solid",transparent:false,result:null};
const e={file:$("#file"),drop:$("#drop"),state:$("#state"),row:$("#file-row"),fileName:$("#file-name"),fileMeta:$("#file-meta"),clear:$("#clear"),canvas:$("#canvas"),empty:$("#empty"),dimension:$("#dimension"),thickness:$("#thickness"),thicknessValue:$("#thickness-value"),padding:$("#padding"),paddingValue:$("#padding-value"),radius:$("#radius"),radiusValue:$("#radius-value"),border:$("#border-color"),borderHex:$("#border-hex"),bg:$("#bg-color"),bgHex:$("#bg-hex"),style:$("#style"),transparent:$("#transparent"),reset:$("#reset"),format:$("#format"),download:$("#download"),download2:$("#download-2"),status:$("#status"),result:$("#result"),resultName:$("#result-name"),resultMeta:$("#result-meta"),swatch:$("#swatch"),sizeReadout:$("#size-readout"),toast:$("#toast")};
function toast(msg,error){e.toast.textContent=msg;e.toast.className="ab-toast show"+(error?" error":"");clearTimeout(window.__abToast);window.__abToast=setTimeout(()=>e.toast.className="ab-toast",2400)}
function bytes(n){if(!Number.isFinite(n)||n<=0)return"—";const u=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return(n/Math.pow(1024,i)).toFixed(i?2:0)+" "+u[i]}
function hex(v){return v.toUpperCase()}
function roundedRect(ctx,x,y,w,h,r){const rr=Math.min(r,Math.min(w,h)/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function drawPreview(){if(!state.img)return;const scale=Math.min(1,1500/state.img.naturalWidth,1500/state.img.naturalHeight),iw=Math.max(1,Math.round(state.img.naturalWidth*scale)),ih=Math.max(1,Math.round(state.img.naturalHeight*scale)),pad=Math.round(state.padding*scale),border=Math.max(1,Math.round(state.thickness*scale)),W=iw+pad*2+border*2,H=ih+pad*2+border*2; e.canvas.width=W;e.canvas.height=H;const ctx=e.canvas.getContext("2d");ctx.clearRect(0,0,W,H);const outerR=Math.min(state.radius*scale,(W/2)-1,(H/2)-1);if(!state.transparent){ctx.fillStyle=state.bg;roundedRect(ctx,0,0,W,H,outerR);ctx.fill()}if(state.style==="double"){const inset=Math.max(1,border/3);ctx.strokeStyle=state.border;ctx.lineWidth=Math.max(1,border/3);roundedRect(ctx,inset,inset,W-inset*2,H-inset*2,Math.max(0,outerR-inset));ctx.stroke();ctx.save();ctx.setLineDash([]);ctx.strokeStyle=state.border;ctx.lineWidth=Math.max(1,border/3);const inset2=inset*3;roundedRect(ctx,inset2,inset2,W-inset2*2,H-inset2*2,Math.max(0,outerR-inset2));ctx.stroke();ctx.restore()}else{ctx.strokeStyle=state.border;ctx.lineWidth=border;ctx.setLineDash(state.style==="dashed"?[border*2,border]:state.style==="dotted"?[Math.max(2,border*.35),Math.max(3,border*.9)]:[]);roundedRect(ctx,border/2,border/2,W-border,H-border,Math.max(0,outerR-border/2));ctx.stroke();ctx.setLineDash([])}ctx.save();ctx.beginPath();roundedRect(ctx,border+pad,border+pad,iw,ih,Math.max(0,Math.min(state.radius*scale-border/2,Math.min(iw,ih)/2)));ctx.clip();ctx.drawImage(state.img,border+pad,border+pad,iw,ih);ctx.restore();e.empty.hidden=true;e.dimension.textContent=W+" × "+H+" px";e.swatch.style.background=state.border;e.sizeReadout.textContent=state.thickness+" px"}
function loadFile(file){if(!file||!file.type.startsWith("image/")){toast("Escolha um ficheiro de imagem.",true);return}if(state.url)URL.revokeObjectURL(state.url);state.file=file;state.url=URL.createObjectURL(file);const img=new Image();e.state.textContent="LOADING";e.status.textContent="A carregar…";e.download.disabled=true;img.onload=()=>{state.img=img;state.result=null;e.fileName.textContent=file.name;e.fileMeta.textContent=bytes(file.size)+" · "+(file.type||"imagem");e.row.hidden=false;e.state.textContent="READY";e.status.textContent="Imagem carregada. Ajuste a moldura.";e.reset.disabled=false;e.download.disabled=false;drawPreview()};img.onerror=()=>{e.state.textContent="ERROR";toast("Não foi possível abrir esta imagem.",true)};img.src=state.url}
function sync(){state.thickness=Number(e.thickness.value);state.padding=Number(e.padding.value);state.radius=Number(e.radius.value);state.border=e.border.value;state.bg=e.bg.value;state.style=e.style.value;state.transparent=e.transparent.checked;e.thicknessValue.textContent=state.thickness+" px";e.paddingValue.textContent=state.padding+" px";e.radiusValue.textContent=state.radius+" px";e.borderHex.textContent=hex(state.border);e.bgHex.textContent=hex(state.bg);e.swatch.style.background=state.border;e.sizeReadout.textContent=state.thickness+" px";if(state.img)drawPreview()}
function exportBlob(){return new Promise((resolve,reject)=>{const c=document.createElement("canvas");const scale=1,iw=state.img.naturalWidth,ih=state.img.naturalHeight,pad=state.padding,b=state.thickness,W=iw+pad*2+b*2,H=ih+pad*2+b*2;c.width=W;c.height=H;const ctx=c.getContext("2d"),r=Math.min(state.radius,W/2-1,H/2-1);if(!state.transparent){ctx.fillStyle=state.bg;roundedRect(ctx,0,0,W,H,r);ctx.fill()}if(state.style==="double"){ctx.strokeStyle=state.border;ctx.lineWidth=Math.max(1,b/3);roundedRect(ctx,b/2,b/2,W-b,H-b,r);ctx.stroke();const i=b*1.7;ctx.lineWidth=Math.max(1,b/3);roundedRect(ctx,i,i,W-i*2,H-i*2,Math.max(0,r-i));ctx.stroke()}else{ctx.strokeStyle=state.border;ctx.lineWidth=b;ctx.setLineDash(state.style==="dashed"?[b*2,b]:state.style==="dotted"?[Math.max(2,b*.35),Math.max(3,b*.9)]:[]);roundedRect(ctx,b/2,b/2,W-b,H-b,r);ctx.stroke();ctx.setLineDash([])}ctx.save();ctx.beginPath();roundedRect(ctx,b+pad,b+pad,iw,ih,Math.max(0,Math.min(state.radius-b/2,Math.min(iw,ih)/2)));ctx.clip();ctx.drawImage(state.img,b+pad,b+pad,iw,ih);ctx.restore();c.toBlob(blob=>blob?resolve(blob):reject(new Error("toBlob falhou")),e.format.value,e.format.value==="image/png"?undefined:.92)})}
async function downloadImage(){if(!state.img)return;e.state.textContent="PROCESS";e.status.textContent="A preparar o ficheiro…";e.download.disabled=true;try{state.result=await exportBlob();const ext=e.format.value==="image/jpeg"?"jpg":e.format.value==="image/webp"?"webp":"png";e.resultName.textContent="nexauren-moldura."+ext;e.resultMeta.textContent=bytes(state.result.size)+" · "+e.canvas.width+" × "+e.canvas.height+" px";e.result.hidden=false;e.download.disabled=false;e.download2.disabled=false;e.status.textContent="Imagem pronta para download.";e.state.textContent="READY"}catch(err){console.error(err);e.state.textContent="ERROR";e.status.textContent="Não foi possível exportar.";toast("Falha ao gerar a imagem.",true)}}
function downloadResult(){if(!state.result)return;const url=URL.createObjectURL(state.result),a=document.createElement("a");a.href=url;a.download=e.resultName.textContent;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),900)}
const presets={clean:{t:10,p:18,r:4,b:"#3157d6",bg:"#ffffff",s:"solid"},bold:{t:24,p:24,r:0,b:"#1f2937",bg:"#f7f5ef",s:"solid"},soft:{t:18,p:28,r:36,b:"#e9a53b",bg:"#fffaf0",s:"solid"},mono:{t:16,p:18,r:0,b:"#111111",bg:"#ffffff",s:"double"}};
document.querySelectorAll("[data-preset]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-preset]").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const p=presets[btn.dataset.preset];e.thickness.value=p.t;e.padding.value=p.p;e.radius.value=p.r;e.border.value=p.b;e.bg.value=p.bg;e.style.value=p.s;e.transparent.checked=false;sync()}));
[e.thickness,e.padding,e.radius,e.border,e.bg,e.style,e.transparent].forEach(x=>x.addEventListener("input",sync));
e.transparent.addEventListener("change",sync);
e.file.addEventListener("change",ev=>loadFile(ev.target.files&&ev.target.files[0]));
["dragenter","dragover"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.add("drag")}));
["dragleave","drop"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.remove("drag")}));
e.drop.addEventListener("drop",x=>loadFile(x.dataTransfer?.files?.[0]));
e.reset.addEventListener("click",()=>{e.thickness.value=24;e.padding.value=24;e.radius.value=0;e.border.value="#1f2937";e.bg.value="#f7f5ef";e.style.value="solid";e.transparent.checked=false;document.querySelectorAll("[data-preset]").forEach(x=>x.classList.toggle("active",x.dataset.preset==="bold"));sync();e.result.hidden=true;e.download.disabled=!state.img;e.status.textContent="Configuração reposta."});
e.clear.addEventListener("click",()=>{if(state.url)URL.revokeObjectURL(state.url);state.file=null;state.img=null;state.url=null;state.result=null;e.file.value="";e.row.hidden=true;e.state.textContent="IDLE";e.status.textContent="Escolha uma imagem para começar.";e.dimension.textContent="—";e.download.disabled=true;e.reset.disabled=true;e.result.hidden=true;e.canvas.width=1;e.canvas.height=1;e.empty.hidden=false});
e.download.addEventListener("click",downloadImage);e.download2.addEventListener("click",downloadResult);
window.addEventListener("error",ev=>{if(ev?.error){console.error(ev.error);toast("Erro inesperado na ferramenta.",true)}});
sync();
})();