import { PDFDocument } from "https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm";
(()=>{"use strict";
const language=new URLSearchParams(location.search).get("lang")==="en"?"en":"pt";
const ui=language==="en"?{lead:"Combine multiple PDF files into one document, organize the order, and do everything locally in your browser.",local:"LOCAL · NO UPLOAD",drop:"Add PDFs",sub:"Tap to select documents or drag them here",docs:"Documents",pages:"Pages",size:"Size",list:"Assembly queue",listSub:"The order will be preserved in the final PDF.",clear:"Clear",empty:"Add at least two PDFs to start.",name:"PDF name",build:"Merge PDFs",ready:"Ready for documents.",privacy:"Privacy first",privacyBody:"Your documents stay on your device while the assembly happens.",addError:"Select valid PDF files.",need:"Add at least two PDF files.",loading:"Reading",processing:"Merging",done:"PDF created successfully.",error:"Could not create the PDF.",download:"Download PDF",result:"PDF created",back:"← PDF",translate:"Português",step1:"Add",step2:"Organize",step3:"Export"}:{lead:"Combine vários documentos PDF num único ficheiro, organize a ordem e faça tudo localmente no navegador.",local:"LOCAL · SEM UPLOAD",drop:"Adicionar PDFs",sub:"Toque para selecionar documentos ou arraste-os para aqui",docs:"Documentos",pages:"Páginas",size:"Tamanho",list:"Fila de montagem",listSub:"A ordem será mantida no PDF final.",clear:"Limpar",empty:"Adicione pelo menos dois PDFs para começar.",name:"Nome do PDF",build:"Juntar PDFs",ready:"Pronto para receber documentos.",privacy:"Privacidade primeiro",privacyBody:"Os documentos permanecem no seu dispositivo enquanto a montagem acontece.",addError:"Selecione ficheiros PDF válidos.",need:"Adicione pelo menos dois ficheiros PDF.",loading:"A ler",processing:"A juntar",done:"PDF criado com sucesso.",error:"Não foi possível criar o PDF.",download:"Baixar PDF",result:"PDF criado",back:"← PDF",translate:"English",step1:"Adicionar",step2:"Organizar",step3:"Exportar"};
const $=s=>document.querySelector(s),input=$("#pdfmerge-files"),drop=$("#pdfmerge-drop"),list=$("#pdfmerge-list"),build=$("#pdfmerge-build"),clear=$("#pdfmerge-clear"),status=$("#pdfmerge-status"),count=$("#pdfmerge-count"),pageCount=$("#pdfmerge-pages"),size=$("#pdfmerge-size"),name=$("#pdfmerge-name"),progress=$("#pdfmerge-progress"),result=$("#pdfmerge-result"),resultName=$("#pdfmerge-result-name"),resultSize=$("#pdfmerge-result-size"),downloadBtn=$("#pdfmerge-download");
let files=[],output=null;
const bytes=n=>{if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]};
const msg=(v,err=false)=>{status.textContent=v;status.style.color=err?"var(--danger)":"var(--muted)"};
function set(id,v){const e=$(id);if(e)e.textContent=v}
function apply(){document.documentElement.lang=language;set("#pdfmerge-lead",ui.lead);set("#pdfmerge-local",ui.local);set("#pdfmerge-drop-title",ui.drop);set("#pdfmerge-drop-sub",ui.sub);set("#pdfmerge-count-label",ui.docs);set("#pdfmerge-pages-label",ui.pages);set("#pdfmerge-size-label",ui.size);set("#pdfmerge-list-title",ui.list);set("#pdfmerge-list-sub",ui.listSub);set("#pdfmerge-clear",ui.clear);set("#pdfmerge-empty",ui.empty);set("#pdfmerge-name-label",ui.name);set("#pdfmerge-build",ui.build);set("#pdfmerge-status",ui.ready);set("#pdfmerge-privacy-title",ui.privacy);set("#pdfmerge-privacy-body",ui.privacyBody);set("#pdfmerge-step1",ui.step1);set("#pdfmerge-step2",ui.step2);set("#pdfmerge-step3",ui.step3);set("#pdfmerge-result-label",ui.result);set("#pdfmerge-download",ui.download);set("#pdfmerge-lang",ui.translate);set(".pdfmerge-back",ui.back)}
function render(){list.replaceChildren();count.textContent=String(files.length);pageCount.textContent="—";size.textContent=bytes(files.reduce((n,f)=>n+f.size,0));build.disabled=files.length<2;if(!files.length){const e=document.createElement("div");e.className="pdfmerge-empty";e.textContent=ui.empty;list.append(e);pageCount.textContent="0";return}
files.forEach((f,i)=>{const row=document.createElement("div");row.className="pdfmerge-row";const idx=document.createElement("div");idx.className="pdfmerge-index";idx.textContent=String(i+1).padStart(2,"0");const info=document.createElement("div"),b=document.createElement("strong"),s=document.createElement("small");b.textContent=f.name;s.textContent=bytes(f.size);info.append(b,s);const up=document.createElement("button");up.className="pdfmerge-move";up.type="button";up.textContent="↑";up.title="Move up";up.disabled=i===0;up.onclick=()=>{[files[i-1],files[i]]=[files[i],files[i-1]];render()};const down=document.createElement("button");down.className="pdfmerge-move";down.type="button";down.textContent="↓";down.title="Move down";down.disabled=i===files.length-1;down.onclick=()=>{[files[i+1],files[i]]=[files[i],files[i+1]];render()};const rm=document.createElement("button");rm.className="pdfmerge-remove";rm.type="button";rm.textContent="×";rm.title=language==="en"?"Remove":"Remover";rm.onclick=()=>{files.splice(i,1);render()};row.append(idx,info,up,down,rm);list.append(row)})}
function add(fileList){const a=[...fileList].filter(f=>f&&(/application\/pdf/i.test(f.type)||/\.pdf$/i.test(f.name)));if(!a.length){msg(ui.addError,true);return}files.push(...a);result.hidden=true;render();msg(ui.ready)}
async function merge(){if(files.length<2){msg(ui.need,true);return}build.disabled=true;clear.disabled=true;result.hidden=true;progress.style.width="0%";try{const out=await PDFDocument.create();for(let i=0;i<files.length;i++){msg(ui.loading+" "+(i+1)+"/"+files.length+"…");const data=await files[i].arrayBuffer();const src=await PDFDocument.load(data,{ignoreEncryption:true});const copied=await out.copyPages(src,src.getPageIndices());copied.forEach(p=>out.addPage(p));progress.style.width=Math.round((i+1)/files.length*90)+"%";await new Promise(requestAnimationFrame)}msg(ui.processing+"…");const bytesOut=await out.save({useObjectStreams:false});output=new Blob([bytesOut],{type:"application/pdf"});const safe=(name.value.trim().replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"documento-unificado")+".pdf";resultName.textContent=safe;resultSize.textContent=bytes(output.size);result.hidden=false;progress.style.width="100%";downloadBtn.onclick=()=>{const u=URL.createObjectURL(output),a=document.createElement("a");a.href=u;a.download=safe;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)};msg(ui.done)}catch(e){msg(e?.message||ui.error,true)}finally{build.disabled=files.length<2;clear.disabled=false}}
input.addEventListener("change",e=>{add(e.target.files);input.value=""});drop.addEventListener("click",e=>{if(e.target!==input)input.click()});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");add(e.dataTransfer.files)});clear.addEventListener("click",()=>{files=[];output=null;result.hidden=true;progress.style.width="0%";render();msg(ui.ready)});apply();render();
})();