const $=s=>document.querySelector(s);
const e={file:$("#file"),cameraFile:$("#cameraFile"),choose:$("#choose"),camera:$("#camera"),drop:$("#drop"),queue:$("#queue"),preview:$("#previewCanvas"),previewEmpty:$("#previewEmpty"),layout:$("#layout"),columns:$("#columns"),columnsField:$("#columnsField"),columnsOut:$("#columnsOut"),gap:$("#gap"),gapOut:$("#gapOut"),padding:$("#padding"),paddingOut:$("#paddingOut"),background:$("#background"),format:$("#format"),quality:$("#quality"),qualityOut:$("#qualityOut"),build:$("#build"),download:$("#download"),copy:$("#copy"),clear:$("#clear"),status:$("#status"),spinner:$("#spinner"),state:$("#state"),previewMeta:$("#previewMeta"),countStat:$("#countStat"),layoutStat:$("#layoutStat"),sizeStat:$("#sizeStat"),formatStat:$("#formatStat"),result:$("#result"),resultDims:$("#resultDims"),resultSize:$("#resultSize"),resultCount:$("#resultCount"),resultFormat:$("#resultFormat")};
const state={items:[],result:null};let processing=false,previewTimer=0;
const revoke=u=>{if(u)try{URL.revokeObjectURL(u)}catch{}};const bytes=n=>{if(!Number.isFinite(n)||n<=0)return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]};const ext=()=>e.format.value==="image/jpeg"?"jpg":e.format.value==="image/webp"?"webp":"png";const valid=()=>state.items.filter(x=>x.img&&!x.error);
function status(t,error=false){e.status.textContent=t;e.status.className="status"+(error?" error":"")}
function setBusy(on){processing=on;e.spinner.classList.toggle("on",on);e.build.disabled=on||valid().length<2}
function sanitize(v){return(v||"").replace(/[^a-z0-9_-]+/gi,"-").replace(/^-+|-+$/g,"")||"images"}
function metrics(items,layout,cols,gap){
 if(layout==="vertical"){let y=0;const places=items.map(it=>{const p={x:0,y,w:it.w,h:it.h};y+=it.h+gap;return p});return{w:Math.max(...items.map(x=>x.w)),h:y-gap,places}}
 if(layout==="horizontal"){let x=0;const places=items.map(it=>{const p={x,y:0,w:it.w,h:it.h};x+=it.w+gap;return p});return{w:x-gap,h:Math.max(...items.map(x=>x.h)),places}}
 const rows=[];for(let i=0;i<items.length;i+=cols)rows.push(items.slice(i,i+cols));const colW=Array.from({length:cols},(_,c)=>Math.max(1,...rows.map(r=>r[c]?.w||0)));const rowH=rows.map(r=>Math.max(1,...r.map(x=>x.h)));const places=[];let y=0;for(let r=0;r<rows.length;r++){let x=0;for(let c=0;c<rows[r].length;c++){const it=rows[r][c];places.push({x,y,w:it.w,h:it.h});x+=colW[c]+gap}y+=rowH[r]+gap}return{w:colW.reduce((a,b)=>a+b,0)+gap*(Math.min(cols,items.length)-1),h:rowH.reduce((a,b)=>a+b,0)+gap*(rows.length-1),places}
}
function draw(canvas,items,m,pad,scale){
 canvas.width=Math.max(1,Math.round((m.w+pad*2)*scale));canvas.height=Math.max(1,Math.round((m.h+pad*2)*scale));const ctx=canvas.getContext("2d");if(!ctx)throw Error("The browser could not start image composition.");ctx.fillStyle=e.background.value;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";m.places.forEach((p,i)=>ctx.drawImage(items[i].img,(pad+p.x)*scale,(pad+p.y)*scale,p.w*scale,p.h*scale));return canvas
}
function updateStats(m){e.countStat.textContent=String(valid().length);e.layoutStat.textContent=e.layout.value==="vertical"?"Vertical":e.layout.value==="horizontal"?"Horizontal":"Grid";e.sizeStat.textContent=m?m.w+" × "+m.h:"—";e.formatStat.textContent=ext().toUpperCase();e.previewMeta.textContent=m?m.w+" × "+m.h+" px · "+valid().length+" images":"No output yet";e.columnsField.hidden=e.layout.value!=="grid";e.columnsOut.textContent=e.columns.value;e.gapOut.textContent=e.gap.value+" px";e.paddingOut.textContent=e.padding.value+" px";e.qualityOut.textContent=e.format.value==="image/png"?"Lossless":e.quality.value+"%"}
function renderPreview(){
 const items=valid();if(!items.length){e.preview.width=e.preview.height=1;e.previewEmpty.hidden=false;updateStats();return}
 const m=metrics(items,e.layout.value,Number(e.columns.value)||2,Number(e.gap.value)||0),pad=Number(e.padding.value)||0,scale=Math.min(1,1400/Math.max(m.w+pad*2,m.h+pad*2));draw(e.preview,items,m,pad,scale);e.previewEmpty.hidden=true;updateStats(m);e.build.disabled=processing||items.length<2
}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderQueue(){
 if(!state.items.length){e.queue.innerHTML='<div class="empty">Add at least two images to build a composition.</div>';e.clear.disabled=true;return}
 e.queue.innerHTML=state.items.map((it,i)=>'<div class="item" data-id="'+it.id+'"><img class="thumb" src="'+(it.url||"")+'" alt=""><div class="info"><b>'+escapeHtml(it.name)+'</b><small>'+(!it.img?"Loading…":it.error?"Unsupported image":it.w+" × "+it.h+" · "+bytes(it.file.size))+'</small></div><div class="item-actions"><button type="button" data-a="up" aria-label="Move image up" '+(i===0?"disabled":"")+'>↑</button><button type="button" data-a="down" aria-label="Move image down" '+(i===state.items.length-1?"disabled":"")+'>↓</button><button type="button" data-a="remove" aria-label="Remove image">×</button></div></div>').join("");e.clear.disabled=false
}
function loadImage(file,id){return new Promise(resolve=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({id,img,w:img.naturalWidth||img.width,h:img.naturalHeight||img.height,url,error:false});img.onerror=()=>{revoke(url);resolve({id,img:null,w:0,h:0,url:"",error:true})};img.src=url})}
async function addFiles(files){
 const list=[...files].filter(f=>f?.type.startsWith("image/"));if(!list.length){status("Choose supported image files.",true);return}
 const pending=list.map(file=>{const id=crypto.randomUUID?.()||Date.now()+"-"+Math.random();state.items.push({id,file,name:file.name,url:URL.createObjectURL(file),img:null,w:0,h:0,error:false});return{id,file}});renderQueue();e.state.textContent="LOADING";status("Loading "+list.length+" image"+(list.length===1?"":"s")+"…");
 const loaded=await Promise.all(pending.map(x=>loadImage(x.file,x.id)));loaded.forEach(v=>{const it=state.items.find(x=>x.id===v.id);if(it){revoke(it.url);Object.assign(it,v)}});renderQueue();e.state.textContent=valid().length>=2?"READY":"WAITING";status(valid().length>=2?"Images ready. Adjust the composition, then generate.":"Add at least two valid images to continue.");renderPreview()
}
async function build(){
 const items=valid();if(items.length<2){status("Add at least two valid images first.",true);return}
 setBusy(true);e.state.textContent="PROCESS";status("Rendering the full-resolution composition…");
 try{
  const m=metrics(items,e.layout.value,Number(e.columns.value)||2,Number(e.gap.value)||0),pad=Number(e.padding.value)||0,totalW=m.w+pad*2,totalH=m.h+pad*2;
  if(totalW*totalH>30000000)throw Error("The resulting canvas is too large for this device. Reduce source dimensions or spacing.");
  const c=document.createElement("canvas");draw(c,items,m,pad,1);
  const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error("The browser could not export the image.")),e.format.value,e.format.value==="image/png"?undefined:Number(e.quality.value)/100));
  state.result=blob;e.resultDims.textContent=totalW+" × "+totalH;e.resultSize.textContent=bytes(blob.size);e.resultCount.textContent=String(items.length);e.resultFormat.textContent=ext().toUpperCase();e.result.hidden=false;e.download.disabled=e.copy.disabled=false;e.state.textContent="READY";status("Full-resolution image generated successfully.");e.result.scrollIntoView({behavior:"smooth",block:"start"})
 }catch(err){state.result=null;e.download.disabled=e.copy.disabled=true;e.state.textContent="ERROR";status(err?.message||"Could not generate the image.",true)}
 finally{setBusy(false)}
}
function download(){if(!state.result){status("Generate the image first.",true);return}const base=sanitize((valid()[0]?.name||"images").replace(/\.[^.]+$/,""));NexaurenImage.download(state.result,"nexauren-"+base+"-combined."+ext())}
async function copySummary(){if(!state.result){status("Generate the image first.",true);return}const t=["NEXAUREN IMAGE COMBINER","Images: "+valid().length,"Layout: "+e.layout.value,"Canvas: "+e.resultDims.textContent,"Format: "+e.resultFormat.textContent,"Size: "+e.resultSize.textContent].join("\\n");try{await navigator.clipboard.writeText(t);status("Summary copied.")}catch{status("Could not copy the summary.",true)}}
function clear(){state.items.forEach(x=>revoke(x.url));state.items=[];state.result=null;e.result.hidden=true;e.download.disabled=e.copy.disabled=true;e.state.textContent="IDLE";status("Add at least two images to start.");renderQueue();renderPreview()}
e.choose.onclick=()=>e.file.click();e.camera.onclick=()=>e.cameraFile.click();e.file.onchange=ev=>{void addFiles(ev.target.files);ev.target.value=""};e.cameraFile.onchange=ev=>{void addFiles(ev.target.files);ev.target.value=""};
["dragenter","dragover"].forEach(t=>e.drop.addEventListener(t,ev=>{ev.preventDefault();e.drop.style.borderColor="var(--cyan)"}));["dragleave","drop"].forEach(t=>e.drop.addEventListener(t,ev=>{ev.preventDefault();e.drop.style.borderColor="#42536f"}));e.drop.ondrop=ev=>{void addFiles(ev.dataTransfer.files)};e.drop.onkeydown=ev=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();e.file.click()}};
e.queue.onclick=ev=>{const b=ev.target.closest("button[data-a]");if(!b)return;const row=b.closest(".item"),id=row?.dataset.id,i=state.items.findIndex(x=>x.id===id);if(i<0)return;const a=b.dataset.a;if(a==="remove"){revoke(state.items[i].url);state.items.splice(i,1)}else if(a==="up"&&i>0)[state.items[i-1],state.items[i]]=[state.items[i],state.items[i-1]];else if(a==="down"&&i<state.items.length-1)[state.items[i+1],state.items[i]]=[state.items[i],state.items[i+1]];state.result=null;e.download.disabled=e.copy.disabled=true;e.result.hidden=true;renderQueue();renderPreview()};
[e.layout,e.columns,e.gap,e.padding,e.background,e.format,e.quality].forEach(x=>x.addEventListener("input",()=>{clearTimeout(previewTimer);previewTimer=setTimeout(renderPreview,40)}));e.build.onclick=build;e.download.onclick=download;e.copy.onclick=copySummary;e.clear.onclick=clear;renderPreview();