const video=document.querySelector("#camera"),canvas=document.querySelector("#scan-canvas"),ctx=canvas.getContext("2d",{willReadFrequently:true}),placeholder=document.querySelector("#scan-placeholder"),state=document.querySelector("#scan-state"),status=document.querySelector("#status"),resultEmpty=document.querySelector("#result-empty"),resultContent=document.querySelector("#result-content"),resultText=document.querySelector("#result-text"),resultType=document.querySelector("#result-type"),openButton=document.querySelector("#open"),startButton=document.querySelector("#start-camera"),stopButton=document.querySelector("#stop-camera"),imageInput=document.querySelector("#image-input"),copyButton=document.querySelector("#copy"),clearButton=document.querySelector("#clear-result");
let stream=null,scanning=false,animationId=0,lastResult="";
const setStatus=(m,e=false)=>{status.textContent=m;status.style.color=e?"#ff9e9e":"#b6fffb"};
function classify(v){try{const u=new URL(v);if(u.protocol==="http:"||u.protocol==="https:")return"URL"}catch{}if(/^WIFI:/i.test(v))return"WI-FI";if(/^BEGIN:VCARD/i.test(v))return"CONTACTO";return"TEXTO"}
function clearResult(){lastResult="";resultEmpty.hidden=false;resultContent.hidden=true;openButton.hidden=true;openButton.dataset.url="";clearButton.hidden=true;resultText.textContent=""}
function showResult(v){lastResult=v;resultEmpty.hidden=true;resultContent.hidden=false;resultText.textContent=v;resultType.textContent=classify(v);clearButton.hidden=false;let safe="";try{const u=new URL(v);if(u.protocol==="http:"||u.protocol==="https:")safe=u.href}catch{}openButton.hidden=!safe;openButton.dataset.url=safe;setStatus("QR Code detetado com sucesso.");stopCamera()}
function scanFrame(){if(!scanning)return;if(video.readyState>=2&&video.videoWidth){const max=900,s=Math.min(1,max/video.videoWidth);canvas.width=Math.max(1,Math.round(video.videoWidth*s));canvas.height=Math.max(1,Math.round(video.videoHeight*s));ctx.drawImage(video,0,0,canvas.width,canvas.height);const d=ctx.getImageData(0,0,canvas.width,canvas.height);if(typeof window.jsQR!=="function"){stopCamera();setStatus("O motor de leitura não ficou disponível. Verifique a ligação e tente novamente.",true);return}const code=window.jsQR(d.data,d.width,d.height,{inversionAttempts:"attemptBoth"});if(code?.data){showResult(code.data);return}}animationId=requestAnimationFrame(scanFrame)}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){setStatus("Este navegador não disponibiliza acesso à câmara.",true);return}if(typeof window.jsQR!=="function"){setStatus("O motor de leitura ainda não ficou disponível. Verifique a ligação e tente novamente.",true);return}stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();scanning=true;placeholder.hidden=true;video.style.display="block";startButton.disabled=true;stopButton.disabled=false;state.textContent="A procurar um QR Code…";setStatus("Câmara ativa. Aponte para o código.");scanFrame()}catch(err){const denied=err?.name==="NotAllowedError"||err?.name==="SecurityError";setStatus(denied?"Permissão da câmara recusada. Autorize a câmara nas definições do navegador.":"Não foi possível iniciar a câmara. Tente selecionar uma imagem.",true)}}
function stopCamera(){scanning=false;cancelAnimationFrame(animationId);animationId=0;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.pause();video.srcObject=null;video.style.display="none";placeholder.hidden=false;startButton.disabled=false;stopButton.disabled=true;state.textContent="A aguardar câmara…"}
async function readImage(file){if(!file)return;if(typeof window.jsQR!=="function"){setStatus("O motor de leitura não ficou disponível. Verifique a ligação e tente novamente.",true);return}stopCamera();setStatus("A analisar a imagem…");state.textContent="A analisar imagem…";const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const max=1800,s=Math.min(1,max/img.naturalWidth,max/img.naturalHeight);canvas.width=Math.max(1,Math.round(img.naturalWidth*s));canvas.height=Math.max(1,Math.round(img.naturalHeight*s));ctx.drawImage(img,0,0,canvas.width,canvas.height);const d=ctx.getImageData(0,0,canvas.width,canvas.height),code=window.jsQR(d.data,d.width,d.height,{inversionAttempts:"attemptBoth"});if(code?.data)showResult(code.data);else{setStatus("Não foi encontrado nenhum QR Code nesta imagem.",true);state.textContent="Nenhum QR detetado"}}catch{setStatus("Não foi possível analisar esta imagem.",true)}finally{URL.revokeObjectURL(url)}};img.onerror=()=>{URL.revokeObjectURL(url);setStatus("Não foi possível abrir a imagem escolhida.",true)};img.src=url}
copyButton.addEventListener("click",async()=>{if(!lastResult)return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(lastResult);else{const t=document.createElement("textarea");t.value=lastResult;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}setStatus("Resultado copiado para a área de transferência.")}catch{setStatus("Não foi possível copiar automaticamente. Selecione o resultado manualmente.",true)}});
clearButton.addEventListener("click",()=>{clearResult();setStatus("Resultado limpo.")});
openButton.addEventListener("click",()=>{const u=openButton.dataset.url;if(u)window.open(u,"_blank","noopener,noreferrer")});
startButton.addEventListener("click",startCamera);stopButton.addEventListener("click",()=>{stopCamera();setStatus("Câmara parada.")});imageInput.addEventListener("change",()=>{readImage(imageInput.files?.[0]);imageInput.value=""});window.addEventListener("pagehide",stopCamera);document.querySelector("#year").textContent=new Date().getFullYear();clearResult();setStatus("Pronto. Use a câmara ou escolha uma imagem.");