import {auth,onAuthStateChanged,verifyToolAccess} from "/tool/frontend/tool-access.js?v=20260923-access-2";

(()=>{"use strict";
const TOOL_ID="jpg-to-pdf";
const language=(()=>{const q=new URLSearchParams(location.search).get("lang");if(q==="en")return "en";try{return localStorage.getItem("ns_lang")==="en"?"en":"pt"}catch{return "pt"}})();
const ui=language==="en"?{
  back:"← PDF",title:"JPG → PDF",lead:"Convert one or more JPG/JPEG images into a single PDF. Choose page size, margins, orientation, and output quality.",
  translate:"Português",choose:"Choose JPG/JPEG images",or:"or tap to select multiple images",pageSize:"Page size",a4:"A4",original:"Original image size",
  orientation:"Orientation",auto:"Auto",portrait:"Portrait",landscape:"Landscape",margin:"Margins",quality:"JPEG quality",
  outputName:"Output file name",convert:"Create PDF",clear:"Clear",status:"Ready.",none:"No images selected.",
  account:"Sign in to use this tool",accountBody:"Nexauren tools are available to authenticated users.",signIn:"Sign in or create an account",
  plan:"Checking account…",ready:"Ready to create a PDF.",count:"Images",page:"Page",size:"Page size",qualityStat:"Quality",
  originalSize:"original",processing:"Processing",done:"PDF created successfully.",error:"Could not create the PDF.",
  remove:"Remove",download:"Download PDF",hint:"Processing happens directly in your browser. Your JPG/JPEG files are not uploaded for conversion.",
  limits:"Free: up to 10 images per PDF · Pro: up to 50 images per PDF."
}:{back:"← PDF",title:"JPG → PDF",lead:"Converta uma ou várias imagens JPG/JPEG em um único PDF. Escolha tamanho de página, margens, orientação e qualidade de saída.",
  translate:"English",choose:"Escolha imagens JPG/JPEG",or:"ou toque para selecionar várias imagens",pageSize:"Tamanho da página",a4:"A4",original:"Tamanho original da imagem",
  orientation:"Orientação",auto:"Automática",portrait:"Retrato",landscape:"Paisagem",margin:"Margens",quality:"Qualidade JPEG",
  outputName:"Nome do ficheiro",convert:"Criar PDF",clear:"Limpar",status:"Pronto.",none:"Nenhuma imagem selecionada.",
  account:"Entre para usar esta ferramenta",accountBody:"As ferramentas Nexauren estão disponíveis apenas para utilizadores autenticados.",signIn:"Entrar ou criar conta",
  plan:"A verificar a conta…",ready:"Pronto para criar o PDF.",count:"Imagens",page:"Página",size:"Tamanho da página",qualityStat:"Qualidade",
  originalSize:"original",processing:"A processar",done:"PDF criado com sucesso.",error:"Não foi possível criar o PDF.",
  remove:"Remover",download:"Baixar PDF",hint:"O processamento acontece diretamente no seu navegador. Os JPG/JPEG não são enviados para conversão.",
  limits:"Free: até 10 imagens por PDF · Pro: até 50 imagens por PDF."
};

const $=s=>document.querySelector(s);
const files=$(".jpgpdf-input"),drop=$(".jpgpdf-drop"),app=$("#jpgpdf-app"),gate=$("#jpgpdf-gate"),status=$("#jpgpdf-status"),list=$("#jpgpdf-list"),convertBtn=$("#jpgpdf-convert"),clearBtn=$("#jpgpdf-clear"),count=$("#jpgpdf-count"),pageStat=$("#jpgpdf-page"),sizeStat=$("#jpgpdf-size"),qualityStat=$("#jpgpdf-quality"),quality=$("#jpgpdf-quality-input"),margin=$("#jpgpdf-margin"),pageSize=$("#jpgpdf-page-size"),orientation=$("#jpgpdf-orientation"),nameInput=$("#jpgpdf-name"),plan=$(".jpgpdf-plan"),planName=$("#jpgpdf-plan-name"),planLimit=$("#jpgpdf-plan-limit"),progress=$(".jpgpdf-progress i"),output=$("#jpgpdf-output"),outputName=$("#jpgpdf-output-name"),download=$(".jpgpdf-download"),langBtn=$("#jpgpdf-lang");
let state={files:[],pro:false,ready:false,output:null,urls:[]};

document.title="JPG → PDF — Nexauren Tools";

langBtn.textContent=ui.translate;
langBtn.addEventListener("click",()=>{try{localStorage.setItem("ns_lang",language==="en"?"pt":"en")}catch{}const u=new URL(location.href);if(language==="en")u.searchParams.delete("lang");else u.searchParams.set("lang","en");location.href=u.pathname+u.search});

function setGate(title,body,action,href){gate.classList.remove("jpgpdf-hide");gate.innerHTML='<div class="icon">⌁</div><h2>'+esc(title)+'</h2><p>'+esc(body)+'</p><a class="jpgpdf-btn primary" href="'+esc(href)+'">'+esc(action)+'</a>';app.classList.add("jpgpdf-hide")}
function openApp(){gate.classList.add("jpgpdf-hide");app.classList.remove("jpgpdf-hide")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function msg(v,error=false){status.textContent=v;status.style.color=error?"var(--danger)":"var(--muted)"}
function limits(){return state.pro?50:10}
function refreshPlan(){plan.classList.toggle("pro",state.pro);planName.textContent=state.pro?"NEXAUREN PRO":"NEXAUREN FREE";planLimit.textContent=ui.limits}
function cleanUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function add(fs){const incoming=[...(fs||[])].filter(f=>/\.jpe?g$/i.test(f.name)||f.type==="image/jpeg");state.files=[...state.files,...incoming].slice(0,limits());cleanUrls();state.urls=state.files.map(f=>URL.createObjectURL(f));renderList();msg(state.files.length?ui.ready:ui.none)}
function renderList(){count.textContent=state.files.length;list.replaceChildren();if(!state.files.length){list.innerHTML='<div class="jpgpdf-empty">'+esc(ui.none)+'</div>';return}state.files.forEach((f,i)=>{const row=document.createElement("div");row.className="jpgpdf-item";const im=document.createElement("img");im.className="jpgpdf-thumb";im.src=state.urls[i];im.alt=f.name;const info=document.createElement("div");const b=document.createElement("b");b.textContent=f.name;const s=document.createElement("small");s.textContent=Math.round(f.size/1024)+" KB";info.append(b,s);const rm=document.createElement("button");rm.className="jpgpdf-remove";rm.type="button";rm.textContent=ui.remove;rm.onclick=()=>{state.files.splice(i,1);cleanUrls();state.urls=state.files.map(x=>URL.createObjectURL(x));renderList();msg(state.files.length?ui.ready:ui.none)};row.append(im,info,rm);list.append(row)})}
function loadImage(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file);const im=new Image();im.onload=()=>{URL.revokeObjectURL(u);resolve(im)};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("Invalid JPG/JPEG"))};im.src=u})}
function canvasJpeg(image,quality){const maxEdge=7200;let w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;const scale=Math.min(1,maxEdge/Math.max(w,h));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:false});if(!ctx)throw new Error("Canvas is not available in this browser.");ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(image,0,0,w,h);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve({blob:b,w,h}):reject(new Error("Could not encode JPG.")),"image/jpeg",quality))}
function bytes(n){if(!Number.isFinite(n))return "—";const units=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+units[i]}
function u8(v){return v instanceof Uint8Array?v:new Uint8Array(v)}
function textBytes(s){return new TextEncoder().encode(s)}
function cat(parts){const total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function pdfFromImages(images){const objects=[];objects.push({text:"<< /Type /Catalog /Pages 2 0 R >>"});const pageIds=[];let next=3;for(const img of images){const pageId=next++,imgId=next++,contentId=next++;pageIds.push(pageId);const mb=img.mediaBox;const content=`q\\n${img.draw.w.toFixed(2)} 0 0 ${img.draw.h.toFixed(2)} ${img.draw.x.toFixed(2)} ${img.draw.y.toFixed(2)} cm\\n/Im0 Do\\nQ\\n`;objects.push({text:`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${mb.w.toFixed(2)} ${mb.h.toFixed(2)}] /Resources << /XObject << /Im0 ${imgId} 0 R >> >> /Contents ${contentId} 0 R >>`});objects.push({image:img.jpeg});objects.push({stream:content,text:`<< /Length ${textBytes(content).length} >>`})}objects.push({at2:true,text:`<< /Type /Pages /Kids [${pageIds.map(x=>x+" 0 R").join(" ")}] /Count ${pageIds.length} >>`});
const ordered=[objects[0],objects[objects.length-1],...objects.slice(1,-1)]; /* unused; rebuilt below for stable ids */
const real=[];real.push(objects[0]);real.push(objects[objects.length-1]);let oi=1;while(oi<objects.length-1){real.push(objects[oi],objects[oi+1],objects[oi+2]);oi+=3}
const chunks=[];const offsets=[0];let pos=0;chunks.push(textBytes("%PDF-1.4\n%âãÏÓ\n"));pos+=chunks[0].length;let objNo=1;for(const obj of real){offsets[objNo]=pos;const head=textBytes(objNo+" 0 obj\n");chunks.push(head);pos+=head.length;if(obj.image){const pre=textBytes("/Length "+obj.image.length+"\n/Type /XObject\n/Subtype /Image\n/Width "+obj.w+"\n/Height "+obj.h+"\n/ColorSpace /DeviceRGB\n/BitsPerComponent 8\n/Filter /DCTDecode\n");const open=textBytes("<<\n");chunks.push(open,pre,textBytes(">>\nstream\n"),obj.image,textBytes("\nendstream\nendobj\n"));pos+=open.length+pre.length+3+obj.image.length+15}else if(obj.stream){const data=textBytes(obj.stream);const pre=textBytes(obj.text+"\n");chunks.push(pre,data,textBytes("endstream\nendobj\n"));pos+=pre.length+data.length+15}else{const b=textBytes(obj.text+"\nendobj\n");chunks.push(b);pos+=b.length}objNo++}
const xrefPos=pos;const size=objNo;let xref="xref\n0 "+size+"\n0000000000 65535 f \n";for(let i=1;i<size;i++)xref+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";xref+="trailer\n<< /Size "+size+" /Root 1 0 R >>\nstartxref\n"+xrefPos+"\n%%EOF\n";chunks.push(textBytes(xref));return new Blob([cat(chunks)],{type:"application/pdf"})}
function pageSpec(w,h){const unit=72/96;let mb;if(pageSize.value==="original"){mb={w:Math.max(72,Math.min(1440,w*unit)),h:Math.max(72,Math.min(1440,h*unit))}}else{const a4={w:595.28,h:841.89};const landscape=(orientation.value==="landscape")||(orientation.value==="auto"&&w>h);mb=landscape?{w:a4.h,h:a4.w}:a4}const m=Math.max(0,Math.min(72,+margin.value||0));const fitW=mb.w-m*2,fitH=mb.h-m*2;const scale=Math.min(fitW/w,fitH/h);return{mediaBox:mb,draw:{w:w*scale,h:h*scale,x:(mb.w-w*scale)/2,y:(mb.h-h*scale)/2}}}
function save(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function build(){if(!state.ready||!state.files.length){msg(ui.none,true);return}convertBtn.disabled=true;clearBtn.disabled=true;output.classList.remove("show");progress.style.width="0%";try{const images=[];for(let i=0;i<state.files.length;i++){msg(ui.processing+" "+(i+1)+"/"+state.files.length+"…");const im=await loadImage(state.files[i]);const enc=await canvasJpeg(im,+quality.value/100);const spec=pageSpec(enc.w,enc.h);const jpeg=new Uint8Array(await enc.blob.arrayBuffer());images.push({jpeg,w:enc.w,h:enc.h,mediaBox:spec.mediaBox,draw:spec.draw});progress.style.width=Math.round((i+1)/state.files.length*70)+"%";await new Promise(requestAnimationFrame)}const pdf=pdfFromImages(images);const filename=(String(nameInput.value||"jpg-to-pdf").replace(/[^a-z0-9_-]+/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"jpg-to-pdf")+".pdf";state.output={blob:pdf,name:filename};progress.style.width="100%";outputName.textContent=filename+" · "+bytes(pdf.size);download.onclick=()=>save(pdf,filename);output.classList.add("show");msg(ui.done);pageStat.textContent=state.files.length;sizeStat.textContent=bytes(pdf.size)}catch(e){msg((e&&e.message)||ui.error,true);progress.style.width="0%"}finally{convertBtn.disabled=false;clearBtn.disabled=false}}
files.addEventListener("change",e=>{add(e.target.files);files.value=""});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");add(e.dataTransfer.files)});quality.addEventListener("input",()=>qualityStat.textContent=quality.value+"%");convertBtn.addEventListener("click",build);clearBtn.addEventListener("click",()=>{state.files=[];cleanUrls();renderList();state.output=null;output.classList.remove("show");pageStat.textContent="0";sizeStat.textContent="—";msg(ui.none)});window.addEventListener("beforeunload",cleanUrls);
qualityStat.textContent=quality.value+"%";quality.value=90;qualityStat.textContent="90%";pageStat.textContent="0";sizeStat.textContent="—";count.textContent="0";
refreshPlan();

onAuthStateChanged(auth,async user=>{if(!user){state.ready=false;setGate(ui.account,ui.accountBody,ui.signIn,"/account");return}openApp();try{const result=await verifyToolAccess(TOOL_ID);if(result.unlocked){state.ready=true;refreshPlan();msg(ui.ready)}else if(result.requiresPro){state.ready=false;setGate(language==="en"?"Pro access required":"É necessário o Pro",language==="en"?"This tool is restricted by your current plan.":"O seu plano atual não inclui esta ferramenta.","/account","/account")}else{state.ready=false;setGate(language==="en"?"Access unavailable":"Não foi possível verificar o acesso.",ui.accountBody,ui.signIn,"/account")}}catch{state.ready=false;setGate(language==="en"?"Access unavailable":"Não foi possível verificar o acesso.",ui.accountBody,ui.signIn,"/account")}});
function refreshPlan(){planName.textContent=state.pro?"NEXAUREN PRO":"NEXAUREN FREE";planLimit.textContent=ui.limits}
})();
