import {auth,onAuthStateChanged,getPlanState} from "/tool/frontend/tool-access.js?v=20260923-access-2";

(()=>{"use strict";
const TOOL_ID="jpg-to-pdf";
const language=(()=>{const q=new URLSearchParams(location.search).get("lang");if(q==="en")return "en";try{return localStorage.getItem("ns_lang")==="en"?"en":"pt"}catch{return "pt"}})();
const ui=language==="en"?{back:"← PDF",translate:"Português",lead:"Convert one or more JPG/JPEG images into a single PDF. Choose page size, margins, orientation, and output quality.",drop:"Choose JPG/JPEG images",dropSub:"or tap to select multiple images",pageSize:"Page size",a4:"A4",original:"Original image size",orientation:"Orientation",auto:"Auto",portrait:"Portrait",landscape:"Landscape",margin:"Margins",quality:"JPEG quality",fileName:"Output file name",create:"Create PDF",clear:"Clear",status:"Ready.",none:"No images selected.",remove:"Remove",summary:"Summary",images:"Images",pages:"Pages",pdfSize:"PDF size",privacy:"Privacy",privacyBody:"Processing happens directly in the browser. JPG/JPEG files do not need to be uploaded to a server.",limits:"Free: up to 10 images per PDF.<br>Pro: up to 50 images per PDF.",ready:"Ready to create the PDF.",processing:"Processing",done:"PDF created successfully.",error:"Could not create the PDF.",output:"PDF ready",download:"Download PDF",account:"Sign in to use this tool",accountBody:"Nexauren tools are available to authenticated users.",signIn:"Sign in or create an account",proTitle:"Pro access required",proBody:"Your current plan does not include this tool.",goAccount:"Open account"}:{back:"← PDF",translate:"English",lead:"Converta uma ou várias imagens JPG/JPEG em um único PDF. Escolha tamanho de página, margens, orientação e qualidade de saída.",drop:"Escolha imagens JPG/JPEG",dropSub:"ou toque para selecionar várias imagens",pageSize:"Tamanho da página",a4:"A4",original:"Tamanho original da imagem",orientation:"Orientação",auto:"Automática",portrait:"Retrato",landscape:"Paisagem",margin:"Margens",quality:"Qualidade JPEG",fileName:"Nome do ficheiro",create:"Criar PDF",clear:"Limpar",status:"Pronto.",none:"Nenhuma imagem selecionada.",remove:"Remover",summary:"Resumo",images:"Imagens",pages:"Páginas",pdfSize:"Tamanho do PDF",privacy:"Privacidade",privacyBody:"O processamento acontece diretamente no navegador. Os JPG/JPEG não precisam ser enviados para um servidor.",limits:"Free: até 10 imagens por PDF.<br>Pro: até 50 imagens por PDF.",ready:"Pronto para criar o PDF.",processing:"A processar",done:"PDF criado com sucesso.",error:"Não foi possível criar o PDF.",output:"PDF pronto",download:"Baixar PDF",account:"Entre para usar esta ferramenta",accountBody:"As ferramentas Nexauren estão disponíveis apenas para utilizadores autenticados.",signIn:"Entrar ou criar conta",proTitle:"É necessário o Pro",proBody:"O seu plano atual não inclui esta ferramenta.",goAccount:"Abrir conta"};

const $=s=>document.querySelector(s),set=(s,v)=>{const e=$(s);if(e)e.textContent=v},esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const files=$(".jpgpdf-input"),drop=$(".jpgpdf-drop"),app=$("#jpgpdf-app"),gate=$("#jpgpdf-gate"),status=$("#jpgpdf-status"),list=$("#jpgpdf-list"),convertBtn=$("#jpgpdf-convert"),clearBtn=$("#jpgpdf-clear"),count=$("#jpgpdf-count"),pageStat=$("#jpgpdf-page"),sizeStat=$("#jpgpdf-size"),qualityField=$("#jpgpdf-quality-field"),qualityStat=$("#jpgpdf-quality-stat"),quality=$("#jpgpdf-quality-input"),margin=$("#jpgpdf-margin"),pageSize=$("#jpgpdf-page-size"),orientation=$("#jpgpdf-orientation"),nameInput=$("#jpgpdf-name"),planName=$("#jpgpdf-plan-name"),planLimit=$("#jpgpdf-plan-limit"),progress=$(".jpgpdf-progress i"),output=$("#jpgpdf-output"),outputName=$("#jpgpdf-output-name"),download=$("#jpgpdf-download"),langBtn=$("#jpgpdf-lang");
let state={files:[],pro:false,ready:false,output:null,urls:[]};

function applyLanguage(){document.documentElement.lang=language;set("#jpgpdf-back",ui.back);set("#jpgpdf-lang",ui.translate);set("#jpgpdf-lead",ui.lead);set("#jpgpdf-drop-title",ui.drop);set("#jpgpdf-drop-sub",ui.dropSub);set("#jpgpdf-page-size-label",ui.pageSize);set("#jpgpdf-page-a4",ui.a4);set("#jpgpdf-page-original",ui.original);set("#jpgpdf-orientation-label",ui.orientation);set("#jpgpdf-orientation-auto",ui.auto);set("#jpgpdf-orientation-portrait",ui.portrait);set("#jpgpdf-orientation-landscape",ui.landscape);set("#jpgpdf-margin-label",ui.margin);set("#jpgpdf-quality-label",ui.quality);set("#jpgpdf-name-label",ui.fileName);set("#jpgpdf-convert",ui.create);set("#jpgpdf-clear",ui.clear);set("#jpgpdf-status",ui.status);set("#jpgpdf-empty",ui.none);set("#jpgpdf-summary-title",ui.summary);set("#jpgpdf-count-label",ui.images);set("#jpgpdf-pages-label",ui.pages);set("#jpgpdf-size-label",ui.pdfSize);set("#jpgpdf-quality-label-side",ui.quality);set("#jpgpdf-privacy-title",ui.privacy);set("#jpgpdf-privacy-body",ui.privacyBody);$("#jpgpdf-limits-hint").innerHTML=ui.limits;set("#jpgpdf-output-title",ui.output);set("#jpgpdf-download",ui.download);const q=quality.value+"%";qualityField.textContent=q;qualityStat.textContent=q}
function setGate(title,body,action,href){gate.hidden=false;gate.classList.remove("jpgpdf-hide");gate.innerHTML='<div class="icon">⌁</div><h2>'+esc(title)+'</h2><p>'+esc(body)+'</p><a class="jpgpdf-btn primary" href="'+esc(href)+'">'+esc(action)+'</a>';app.classList.add("jpgpdf-hide")}
function openApp(){gate.hidden=true;gate.classList.add("jpgpdf-hide");app.classList.remove("jpgpdf-hide")}
function msg(v,error=false){status.textContent=v;status.style.color=error?"var(--danger)":"var(--muted)"}
function maxImages(){return state.pro?50:10}
function planUi(){planName.textContent=state.pro?"NEXAUREN PRO":"NEXAUREN FREE";planLimit.textContent=state.pro?(language==="en"?"Pro active · up to 50 images per PDF":"Pro ativo · até 50 imagens por PDF"):(language==="en"?"Free · up to 10 images per PDF":"Free · até 10 imagens por PDF")}
function cleanUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function add(fs){const incoming=[...(fs||[])].filter(f=>/\.jpe?g$/i.test(f.name)||f.type==="image/jpeg");const allowed=maxImages();state.files=[...state.files,...incoming].slice(0,allowed);cleanUrls();state.urls=state.files.map(f=>URL.createObjectURL(f));renderList();msg(state.files.length?ui.ready:ui.none)}
function renderList(){count.textContent=String(state.files.length);list.replaceChildren();if(!state.files.length){list.innerHTML='<div class="jpgpdf-empty">'+esc(ui.none)+'</div>';return}state.files.forEach((f,i)=>{const row=document.createElement("div");row.className="jpgpdf-item";const im=document.createElement("img");im.className="jpgpdf-thumb";im.src=state.urls[i];im.alt=f.name;const info=document.createElement("div"),b=document.createElement("b"),s=document.createElement("small");b.textContent=f.name;s.textContent=Math.max(1,Math.round(f.size/1024))+" KB";info.append(b,s);const rm=document.createElement("button");rm.className="jpgpdf-remove";rm.type="button";rm.textContent=ui.remove;rm.onclick=()=>{state.files.splice(i,1);cleanUrls();state.urls=state.files.map(x=>URL.createObjectURL(x));renderList();msg(state.files.length?ui.ready:ui.none)};row.append(im,info,rm);list.append(row)})}
function loadImage(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);resolve(im)};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error(language==="en"?"Invalid JPG/JPEG.":"JPG/JPEG inválido."))};im.src=u})}
function canvasJpeg(image,q){const maxEdge=7200;let w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h)throw new Error(language==="en"?"Could not read image dimensions.":"Não foi possível ler as dimensões da imagem.");const scale=Math.min(1,maxEdge/Math.max(w,h));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:false});if(!ctx)throw new Error(language==="en"?"Canvas is unavailable.":"O navegador não conseguiu iniciar o processamento.");ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(image,0,0,w,h);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve({blob:b,w,h}):reject(new Error(language==="en"?"Could not encode JPG.":"Não foi possível gerar o JPG.")),"image/jpeg",q))}
function bytes(n){if(!Number.isFinite(n))return "—";const units=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+units[i]}
function textBytes(s){return new TextEncoder().encode(s)}
function concat(parts){const total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total);let off=0;for(const p of parts){out.set(p,off);off+=p.length}return out}
function pdfFromImages(images){const objects=[{num:1,text:"<< /Type /Catalog /Pages 2 0 R >>"}],pageIds=[];images.forEach((img,i)=>{const pageId=3+i*3,imgId=4+i*3,contentId=5+i*3;pageIds.push(pageId);const c="q\n"+img.draw.w.toFixed(2)+" 0 0 "+img.draw.h.toFixed(2)+" "+img.draw.x.toFixed(2)+" "+img.draw.y.toFixed(2)+" cm\n/Im0 Do\nQ\n";objects.push({num:pageId,text:"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "+img.mediaBox.w.toFixed(2)+" "+img.mediaBox.h.toFixed(2)+"] /Resources << /XObject << /Im0 "+imgId+" 0 R >> >> /Contents "+contentId+" 0 R >>"});objects.push({num:imgId,image:img.jpeg,w:img.w,h:img.h});objects.push({num:contentId,stream:c})});objects.splice(1,0,{num:2,text:"<< /Type /Pages /Kids ["+pageIds.map(x=>x+" 0 R").join(" ")+"] /Count "+pageIds.length+" >>"});const chunks=[textBytes("%PDF-1.4\n%Nexauren\n")],offsets=[],header=chunks[0];let pos=header.length;for(const obj of objects){offsets[obj.num]=pos;const oh=textBytes(obj.num+" 0 obj\n");chunks.push(oh);pos+=oh.length;if(obj.image){const dict=textBytes("<<\n/Type /XObject\n/Subtype /Image\n/Width "+obj.w+"\n/Height "+obj.h+"\n/ColorSpace /DeviceRGB\n/BitsPerComponent 8\n/Filter /DCTDecode\n/Length "+obj.image.length+"\n>>\nstream\n"),tail=textBytes("\nendstream\nendobj\n");chunks.push(dict,obj.image,tail);pos+=dict.length+obj.image.length+tail.length}else if(obj.stream){const data=textBytes(obj.stream),dict=textBytes("<< /Length "+data.length+" >>\nstream\n"),tail=textBytes("endstream\nendobj\n");chunks.push(dict,data,tail);pos+=dict.length+data.length+tail.length}else{const b=textBytes(obj.text+"\nendobj\n");chunks.push(b);pos+=b.length}}const xrefPos=pos,size=objects.length+1;let xref="xref\n0 "+size+"\n0000000000 65535 f \n";for(let i=1;i<size;i++)xref+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";xref+="trailer\n<< /Size "+size+" /Root 1 0 R >>\nstartxref\n"+xrefPos+"\n%%EOF\n";chunks.push(textBytes(xref));return new Blob([concat(chunks)],{type:"application/pdf"})}
function pageSpec(w,h){const unit=72/96;let mb;if(pageSize.value==="original"){mb={w:Math.max(72,Math.min(1440,w*unit)),h:Math.max(72,Math.min(1440,h*unit))}}else{const a4={w:595.28,h:841.89},landscape=orientation.value==="landscape"||(orientation.value==="auto"&&w>h);mb=landscape?{w:a4.h,h:a4.w}:a4}const m=Math.max(0,Math.min(72,+margin.value||0)),fw=Math.max(1,mb.w-m*2),fh=Math.max(1,mb.h-m*2),scale=Math.min(fw/w,fh/h);return{mediaBox:mb,draw:{w:w*scale,h:h*scale,x:(mb.w-w*scale)/2,y:(mb.h-h*scale)/2}}}
function save(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function build(){if(!state.ready){msg(language==="en"?"Access is not ready yet.":"O acesso ainda não está pronto.",true);return}if(!state.files.length){msg(ui.none,true);return}convertBtn.disabled=true;clearBtn.disabled=true;output.hidden=true;progress.style.width="0%";try{const imgs=[];for(let i=0;i<state.files.length;i++){msg(ui.processing+" "+(i+1)+"/"+state.files.length+"…");const im=await loadImage(state.files[i]),enc=await canvasJpeg(im,+quality.value/100),spec=pageSpec(enc.w,enc.h),jpeg=new Uint8Array(await enc.blob.arrayBuffer());imgs.push({jpeg,w:enc.w,h:enc.h,mediaBox:spec.mediaBox,draw:spec.draw});progress.style.width=Math.round((i+1)/state.files.length*75)+"%";await new Promise(requestAnimationFrame)}const pdf=pdfFromImages(imgs),clean=(String(nameInput.value||"jpg-to-pdf").replace(/[^a-z0-9_-]+/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"jpg-to-pdf"),filename=clean+".pdf";state.output={blob:pdf,name:filename};progress.style.width="100%";outputName.textContent=filename+" · "+bytes(pdf.size);download.onclick=()=>save(pdf,filename);output.hidden=false;pageStat.textContent=String(state.files.length);sizeStat.textContent=bytes(pdf.size);msg(ui.done)}catch(e){msg(e?.message||ui.error,true);progress.style.width="0%"}finally{convertBtn.disabled=false;clearBtn.disabled=false}}
files.addEventListener("change",e=>{add(e.target.files);files.value=""});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");add(e.dataTransfer.files)});quality.addEventListener("input",()=>{qualityField.textContent=quality.value+"%";qualityStat.textContent=quality.value+"%"});convertBtn.addEventListener("click",build);clearBtn.addEventListener("click",()=>{state.files=[];cleanUrls();renderList();state.output=null;output.hidden=true;pageStat.textContent="0";sizeStat.textContent="—";msg(ui.none)});window.addEventListener("beforeunload",cleanUrls);
applyLanguage();planUi();
onAuthStateChanged(auth,async user=>{if(!user){state.ready=false;convertBtn.disabled=true;setGate(ui.account,ui.accountBody,ui.signIn,"/account");return}openApp();state.ready=true;convertBtn.disabled=false;try{const plan=await getPlanState();state.pro=plan?.pro===true;planUi()}catch{}renderList();msg(ui.ready)});
langBtn.addEventListener("click",()=>{try{localStorage.setItem("ns_lang",language==="en"?"pt":"en")}catch{}const u=new URL(location.href);if(language==="en")u.searchParams.delete("lang");else u.searchParams.set("lang","en");location.href=u.pathname+u.search});
})()
