(()=>{"use strict";
const $=s=>document.querySelector(s);
const state={items:[],result:null};
const e={file:$("#file-input"),drop:$("#drop"),queue:$("#queue"),state:$("#state"),preview:$("#preview"),previewEmpty:$("#preview-empty"),layout:$("#layout"),columns:$("#columns"),columnsField:$("#columns-field"),columnsValue:$("#columns-value"),gap:$("#gap"),gapValue:$("#gap-value"),padding:$("#padding"),paddingValue:$("#padding-value"),background:$("#background"),backgroundValue:$("#background-value"),format:$("#format"),quality:$("#quality"),qualityField:$("#quality-field"),qualityValue:$("#quality-value"),build:$("#build"),download:$("#download"),downloadResult:$("#download-result"),status:$("#status"),result:$("#result"),resultName:$("#result-name"),resultMeta:$("#result-meta"),outputSize:$("#output-size"),outputCount:$("#output-count"),toast:$("#toast")};
function toast(msg,error){e.toast.textContent=msg;e.toast.className="ji-toast show"+(error?" error":"");clearTimeout(window.__jiToast);window.__jiToast=setTimeout(()=>e.toast.className="ji-toast",2400)}
function bytes(n){if(!Number.isFinite(n)||n<=0)return"—";const u=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return(n/Math.pow(1024,i)).toFixed(i?2:0)+" "+u[i]}
function ext(){return e.format.value==="image/jpeg"?"jpg":e.format.value==="image/webp"?"webp":"png"}
function readImage(file,id){return new Promise(resolve=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve({id,file,img,name:file.name,w:img.naturalWidth,h:img.naturalHeight,loading:false,error:false})};img.onerror=()=>{URL.revokeObjectURL(url);resolve({id,file,img:null,name:file.name,w:0,h:0,loading:false,error:true})};img.src=url})}
function addFiles(list){const files=[...list].filter(f=>f&&f.type.startsWith("image/"));if(!files.length){toast("Escolha ficheiros de imagem.",true);return}files.forEach(file=>{const id=crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random();state.items.push({id,file,img:null,name:file.name,w:0,h:0,loading:true,error:false});renderQueue()});e.state.textContent="LOADING";e.status.textContent=files.length+" imagem"+(files.length===1?"":"s")+" adicionada"+(files.length===1?"":"s")+" à fila.";Promise.all(files.map((file,i)=>readImage(file,state.items[state.items.length-files.length+i].id))).then(loaded=>{for(const item of loaded){const target=state.items.find(x=>x.id===item.id);if(target)Object.assign(target,item)}renderQueue();e.state.textContent=state.items.some(x=>x.loading)?"LOADING":"READY";e.status.textContent=state.items.length?"Escolha a ordem e o layout.":"Adicione imagens para começar.";renderPreview()})}
function renderQueue(){if(!state.items.length){e.queue.innerHTML='<div class="ji-empty"><span>01</span><div><strong>Nenhuma imagem na fila</strong><small>Adicione pelo menos duas imagens para começar a montar.</small></div></div>';return}e.queue.innerHTML=state.items.map((item,i)=>'<div class="ji-item" data-id="'+item.id+'"><div>'+ (item.img?'<img class="ji-thumb" src="'+URL.createObjectURL(item.file)+'" alt="">':'<div class="ji-thumb"></div>') +'</div><div class="ji-item-main"><strong>'+escapeHtml(item.name)+'</strong><small>'+ (item.loading?"A carregar…":item.error?"Não suportada":item.w+" × "+item.h+" · "+bytes(item.file.size)) +'</small></div><div class="ji-item-actions"><button type="button" data-action="up" aria-label="Mover para cima" '+(i===0?"disabled":"")+'>↑</button><button type="button" data-action="down" aria-label="Mover para baixo" '+(i===state.items.length-1?"disabled":"")+'>↓</button><button type="button" data-action="remove" aria-label="Remover">×</button></div></div>').join("");e.outputCount.textContent=state.items.length+" imagem"+(state.items.length===1?"":"s")}
function escapeHtml(v){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function buildMetrics(items,layout,cols,gap,pad){if(layout==="vertical"){return{w:Math.max(...items.map(x=>x.w)),h:items.reduce((s,x)=>s+x.h,0)+gap*(items.length-1),places:items.map((x,i)=>({x:0,y:items.slice(0,i).reduce((s,n)=>s+n.h,0)+gap*i,w:x.w,h:x.h}))}}if(layout==="horizontal"){return{w:items.reduce((s,x)=>s+x.w,0)+gap*(items.length-1),h:Math.max(...items.map(x=>x.h)),places:items.map((x,i)=>({x:items.slice(0,i).reduce((s,n)=>s+n.w,0)+gap*i,y:0,w:x.w,h:x.h}))}}const rows=[];for(let i=0;i<items.length;i+=cols)rows.push(items.slice(i,i+cols));const colW=Array.from({length:cols},(_,c)=>Math.max(1,...rows.map(r=>r[c]?.w||0)));const rowH=rows.map(r=>Math.max(1,...r.map(x=>x.h)));const places=[];let y=0;for(let r=0;r<rows.length;r++){let x=0;for(let c=0;c<rows[r].length;c++){const item=rows[r][c];places.push({x,y,w:item.w,h:item.h});x+=colW[c]+gap}y+=rowH[r]+gap}return{w:colW.reduce((s,n)=>s+n,0)+gap*(Math.min(cols,items.length)-1),h:rowH.reduce((s,n)=>s+n,0)+gap*(rows.length-1),places}}
function renderPreview(){const items=state.items.filter(x=>x.img&&!x.error);const ctx=e.preview.getContext("2d");if(!items.length){ctx.clearRect(0,0,e.preview.width,e.preview.height);e.previewEmpty.hidden=false;e.outputSize.textContent="—";e.build.disabled=true;return}e.previewEmpty.hidden=true;const layout=e.layout.value,cols=Number(e.columns.value),gap=Number(e.gap.value),pad=Number(e.padding.value),m=buildMetrics(items,layout,cols,gap,pad);const maxDim=Math.max(m.w+pad*2,m.h+pad*2),scale=Math.min(1,5000/maxDim);const W=Math.max(1,Math.round((m.w+pad*2)*scale)),H=Math.max(1,Math.round((m.h+pad*2)*scale));e.preview.width=W;e.preview.height=H;ctx.fillStyle=e.background.value;ctx.fillRect(0,0,W,H);m.places.forEach((p,i)=>{const dx=Math.round((pad+p.x)*scale),dy=Math.round((pad+p.y)*scale),dw=Math.round(p.w*scale),dh=Math.round(p.h*scale);ctx.drawImage(items[i].img,dx,dy,dw,dh)});e.outputSize.textContent=W+" × "+H+" px";e.build.disabled=items.length<1}
function renderAll(){e.gapValue.textContent=e.gap.value+" px";e.paddingValue.textContent=e.padding.value+" px";e.columnsValue.textContent=e.columns.value;e.backgroundValue.textContent=e.background.value.toUpperCase();e.columnsField.hidden=e.layout.value!=="grid";e.qualityField.style.opacity=e.format.value==="image/png"?".45":"1";e.quality.disabled=e.format.value==="image/png";e.qualityValue.textContent=e.quality.value;renderPreview()}
function exportBlob(){return new Promise((resolve,reject)=>{e.preview.toBlob(b=>b?resolve(b):reject(new Error("Falha ao gerar o ficheiro")),e.format.value,e.format.value==="image/png"?undefined:Number(e.quality.value)/100)})}
async function build(){if(!state.items.some(x=>x.img&&!x.error))return;e.build.disabled=true;e.download.disabled=true;e.state.textContent="PROCESS";e.status.textContent="A preparar a imagem…";try{renderPreview();const blob=await exportBlob();state.result=blob;const base=state.items[0]?.name?.replace(/.[^.]+$/,"")||"imagens";const filename="nexauren-"+base+"-juntas."+ext();e.resultName.textContent=filename;e.resultMeta.textContent=bytes(blob.size)+" · "+e.preview.width+" × "+e.preview.height+" px";e.result.hidden=false;e.download.disabled=false;e.downloadResult.disabled=false;e.state.textContent="READY";e.status.textContent="Ficheiro preparado e pronto para download."}catch(err){console.error(err);e.state.textContent="ERROR";e.status.textContent="Não foi possível gerar a imagem.";toast("Falha ao preparar o ficheiro.",true)}finally{e.build.disabled=state.items.filter(x=>x.img&&!x.error).length===0}}
function download(){if(!state.result)return;const url=URL.createObjectURL(state.result),a=document.createElement("a");a.href=url;a.download=e.resultName.textContent;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
e.file.addEventListener("change",x=>addFiles(x.target.files||[]));
["dragenter","dragover"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.add("drag")}));
["dragleave","drop"].forEach(ev=>e.drop.addEventListener(ev,x=>{x.preventDefault();e.drop.classList.remove("drag")}));
e.drop.addEventListener("drop",x=>addFiles(x.dataTransfer?.files||[]));
e.queue.addEventListener("click",x=>{const btn=x.target.closest("button[data-action]");if(!btn)return;const row=btn.closest(".ji-item"),id=row?.dataset.id,i=state.items.findIndex(v=>v.id===id),action=btn.dataset.action;if(i<0)return;if(action==="remove"){state.items.splice(i,1)}else if(action==="up"&&i>0){[state.items[i-1],state.items[i]]=[state.items[i],state.items[i-1]]}else if(action==="down"&&i<state.items.length-1){[state.items[i+1],state.items[i]]=[state.items[i],state.items[i+1]]}renderQueue();renderPreview()});
[e.layout,e.columns,e.gap,e.padding,e.background,e.format,e.quality].forEach(x=>x.addEventListener("input",renderAll));
$("#build").addEventListener("click",build);$("#download").addEventListener("click",download);$("#download-result").addEventListener("click",download);
window.addEventListener("error",x=>{if(x?.error){console.error(x.error);toast("Erro inesperado na ferramenta.",true)}});
renderAll();
})();