import {auth,onAuthStateChanged} from "/tool/frontend/tool-access.js?v=20260923-access-2";
const gate=document.querySelector('#account-gate'),app=document.querySelector('#tool-app'),value=document.querySelector('#value'),svg=document.querySelector('#barcode'),empty=document.querySelector('#empty'),status=document.querySelector('#status'),validation=document.querySelector('#validation');
let format='code128';
const specs={code128:{name:'Code 128',hint:'Code 128 aceita números, letras e vários símbolos.'},ean13:{name:'EAN-13',hint:'EAN-13 exige exatamente 12 ou 13 dígitos.'},ean8:{name:'EAN-8',hint:'EAN-8 exige exatamente 7 ou 8 dígitos.'},upc:{name:'UPC-A',hint:'UPC-A exige exatamente 11 ou 12 dígitos.'},code39:{name:'Code 39',hint:'Code 39 usa letras maiúsculas, números e símbolos específicos.'}};
const $=id=>document.getElementById(id);
function gateState(show){gate.hidden=!show;app.hidden=show}
function setStatus(t,error=false){status.textContent=t;status.style.color=error?'#ff9f9a':'#d6b261'}
function validAndValue(){let v=value.value.trim();if(format==='code39'){v=v.toUpperCase();value.value=v;if(!/^[0-9A-Z .$/+%-]*$/.test(v))return [null,'Há caracteres inválidos para Code 39.']}if(format==='ean13'&&!/^\d{12,13}$/.test(v))return [null,'EAN-13 precisa de 12 ou 13 dígitos.'];if(format==='ean8'&&!/^\d{7,8}$/.test(v))return [null,'EAN-8 precisa de 7 ou 8 dígitos.'];if(format==='upc'&&!/^\d{11,12}$/.test(v))return [null,'UPC-A precisa de 11 ou 12 dígitos.'];return [v,'']}
function generate(){if(!window.JsBarcode){setStatus('Motor de código de barras indisponível.',true);return}let [v,error]=validAndValue();if(error){svg.innerHTML='';empty.hidden=false;validation.textContent=error;setStatus(error,true);return}if(!v){svg.innerHTML='';empty.hidden=false;validation.textContent='Introduza um valor válido.';setStatus('Introduza um valor para gerar o código.',true);return}try{JsBarcode(svg,v,{format:format==='upc'?'upc':format,lineColor:'#111',background:'#f6f4ef',width:Number($('width').value),height:Number($('height').value),displayValue:$('show-text').checked,fontSize:13,margin:12});empty.hidden=true;validation.textContent='✓ Código válido. Pronto para gerar.';setStatus(`${specs[format].name} gerado.`);$('download').disabled=false;$('print').disabled=false}catch(e){setStatus('Não foi possível gerar este código.',true)}}
function selectFormat(next){format=next;document.querySelectorAll('.format').forEach(b=>b.classList.toggle('active',b.dataset.format===format));$('format-hint').textContent=specs[format].hint;value.value='';svg.innerHTML='';empty.hidden=false;validation.textContent='Aguardando conteúdo.';setStatus('Pronto para gerar.')}
document.querySelectorAll('.format').forEach(b=>b.addEventListener('click',()=>selectFormat(b.dataset.format)));
$('generate').addEventListener('click',generate);value.addEventListener('input',()=>{if(format==='code39')value.value=value.value.toUpperCase()});$('clear').addEventListener('click',()=>{value.value='';svg.innerHTML='';empty.hidden=false;setStatus('Campos limpos.')});
$('width').addEventListener('input',()=>{$('width-out').textContent=$('width').value+'×';if(value.value.trim())generate()});$('height').addEventListener('input',()=>{$('height-out').textContent=$('height').value+' px';if(value.value.trim())generate()});$('show-text').addEventListener('change',generate);
$('download').addEventListener('click',()=>{const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nexauren-${format}.svg`;a.click()});
$('print').addEventListener('click',()=>{const printArea=document.createElement('iframe');printArea.style.position='fixed';printArea.style.width='0';printArea.style.height='0';document.body.appendChild(printArea);const doc=printArea.contentWindow.document;doc.open();doc.write(`<body>${svg.outerHTML}</body>`);doc.close();printArea.contentWindow.focus();printArea.contentWindow.print();setTimeout(()=>printArea.remove(),1000)});
$('year').textContent=new Date().getFullYear();onAuthStateChanged(auth,user=>{gateState(!user);if(user)setStatus('Pronto para gerar.')});