const value=document.querySelector("#value"),svg=document.querySelector("#barcode"),empty=document.querySelector("#empty"),status=document.querySelector("#status"),validation=document.querySelector("#validation");let format="code128",timer=0;
const specs={code128:{name:"Code 128",hint:"Code 128 aceita números, letras e vários símbolos."},ean13:{name:"EAN-13",hint:"EAN-13 exige exatamente 12 ou 13 dígitos."},ean8:{name:"EAN-8",hint:"EAN-8 exige exatamente 7 ou 8 dígitos."},upc:{name:"UPC-A",hint:"UPC-A exige exatamente 11 ou 12 dígitos."},code39:{name:"Code 39",hint:"Code 39 usa letras maiúsculas, números e símbolos específicos."}};
const $=id=>document.getElementById(id),setStatus=(t,e=false)=>{status.textContent=t;status.style.color=e?"#ff9f9a":"#d6b261"},enable=ok=>["download","download-png","copy-value","print"].forEach(id=>$(id).disabled=!ok);
function valid(){let v=value.value.trim();if(format==="code39"){v=v.toUpperCase();value.value=v;if(!/^[0-9A-Z .$/+%-]*$/.test(v))return[null,"Há caracteres inválidos para Code 39."]}if(format==="ean13"&&!/^\d{12,13}$/.test(v))return[null,"EAN-13 precisa de 12 ou 13 dígitos."];if(format==="ean8"&&!/^\d{7,8}$/.test(v))return[null,"EAN-8 precisa de 7 ou 8 dígitos."];if(format==="upc"&&!/^\d{11,12}$/.test(v))return[null,"UPC-A precisa de 11 ou 12 dígitos."];return[v,""]}
function generate(){if(!window.JsBarcode){setStatus("Motor de código de barras indisponível.",true);enable(false);return}const[v,error]=valid();if(error){svg.innerHTML="";empty.hidden=false;validation.textContent=error;setStatus(error,true);enable(false);return}if(!v){svg.innerHTML="";empty.hidden=false;validation.textContent="Introduza um valor válido.";setStatus("Introduza um valor para gerar o código.",true);enable(false);return}try{JsBarcode(svg,v,{format:format==="upc"?"upc":format,lineColor:"#111",background:"#f6f4ef",width:Number($("width").value),height:Number($("height").value),displayValue:$("show-text").checked,fontSize:13,margin:12});empty.hidden=true;validation.textContent="✓ Código válido. Pronto para utilizar.";setStatus(specs[format].name+" gerado.");enable(true)}catch{svg.innerHTML="";empty.hidden=false;validation.textContent="O valor não é compatível com este formato.";setStatus("Não foi possível gerar este código.",true);enable(false)}}
const schedule=()=>{clearTimeout(timer);timer=setTimeout(generate,160)};
document.querySelectorAll(".format").forEach(b=>b.addEventListener("click",()=>{format=b.dataset.format;document.querySelectorAll(".format").forEach(x=>x.classList.toggle("active",x===b));$("format-hint").textContent=specs[format].hint;value.value="";svg.innerHTML="";empty.hidden=false;validation.textContent="Aguardando conteúdo.";enable(false);setStatus("Pronto para gerar.");value.focus()}));
$("generate").addEventListener("click",generate);value.addEventListener("input",()=>{if(format==="code39")value.value=value.value.toUpperCase();schedule()});
$("clear").addEventListener("click",()=>{value.value="";svg.innerHTML="";empty.hidden=false;validation.textContent="Aguardando conteúdo.";enable(false);setStatus("Campos limpos.")});
$("width").addEventListener("input",()=>{$("width-out").textContent=$("width").value+"×";if(value.value.trim())schedule()});$("height").addEventListener("input",()=>{$("height-out").textContent=$("height").value+" px";if(value.value.trim())schedule()});$("show-text").addEventListener("change",schedule);
const svgMarkup=()=>new XMLSerializer().serializeToString(svg),downloadBlob=(blob,name)=>{const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$("download").addEventListener("click",()=>{downloadBlob(new Blob([svgMarkup()],{type:"image/svg+xml;charset=utf-8"}),`nexauren-${format}.svg`);setStatus("SVG guardado.")});
$("download-png").addEventListener("click",()=>{const u=URL.createObjectURL(new Blob([svgMarkup()],{type:"image/svg+xml;charset=utf-8"})),img=new Image();img.onload=()=>{const r=svg.getBoundingClientRect(),s=3,cv=document.createElement("canvas");cv.width=Math.max(1,Math.round(r.width*s));cv.height=Math.max(1,Math.round(r.height*s));const x=cv.getContext("2d");x.fillStyle="#f6f4ef";x.fillRect(0,0,cv.width,cv.height);x.drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(u);cv.toBlob(b=>b&&downloadBlob(b,`nexauren-${format}.png`),"image/png");};img.onerror=()=>URL.revokeObjectURL(u);img.src=u});
$("copy-value").addEventListener("click",async()=>{const v=value.value.trim();if(!v)return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(v);else{const t=document.createElement("textarea");t.value=v;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}setStatus("Valor copiado.")}catch{setStatus("Não foi possível copiar automaticamente.",true)}});
$("print").addEventListener("click",()=>{const f=document.createElement("iframe");f.style.cssText="position:fixed;width:0;height:0;border:0";document.body.appendChild(f);const d=f.contentWindow.document;d.open();d.write(`<!doctype html><html><body style="margin:40px;display:grid;place-items:center;background:white">${svg.outerHTML}</body></html>`);d.close();f.contentWindow.focus();f.contentWindow.print();setTimeout(()=>f.remove(),1000)});
$("year").textContent=new Date().getFullYear();$("format-hint").textContent=specs[format].hint;enable(false);