import {auth,onAuthStateChanged} from "/tool/frontend/tool-access.js?v=20260923-access-2";
const gate=document.querySelector('#account-gate'),app=document.querySelector('#tool-app'),value=document.querySelector('#value'),svg=document.querySelector('#barcode'),empty=document.querySelector('#empty'),status=document.querySelector('#status'),validation=document.querySelector('#validation');
let format='code128';
const specs={code128:{name:'Code 128',hint:'Code 128 aceita números, letras e vários símbolos.',validation:'Aceita texto alfanumérico e símbolos. Ideal para dados gerais.'},ean13:{name:'EAN-13',hint:'EAN-13 exige exatamente 12 ou 13 dígitos.',validation:'Introduza 12 dígitos para calcular o dígito de controlo, ou 13 para validar.'},ean8:{name:'EAN-8',hint:'EAN-8 exige exatamente 7 ou 8 dígitos.',validation:'Introduza 7 dígitos para calcular o dígito de controlo, ou 8 para validar.'},upc:{name:'UPC-A',hint:'UPC-A exige exatamente 11 ou 12 dígitos.',validation:'Introduza 11 dígitos para calcular o dígito de controlo, ou 12 para validar.'},code39:{name:'Code 39',hint:'Code 39 usa letras maiúsculas, números, espaço e - . $ / + %.',validation:'Use caracteres Code 39 válidos. A ferramenta normaliza letras para maiúsculas.'}};
const $=id=>document.getElementById(id);
function gateState(show){gate.hidden=!show;app.hidden=show}
function setStatus(t,error=false){status.textContent=t;status.style.color=error?'#ff9f9a':'#d6b261'}
function validAndValue(){let v=value.value.trim();if(format==='code39')v=v.toUpperCase();if(format==='ean13'){if(!/^\d{12,13}$/.test(v))return [null,'EAN-13 precisa de 12 ou 13 dígitos.'];if(v.length===12)return [v,''];}if(format==='ean8'){if(!/^\d{7,8}$/.test(v))return [null,'EAN-8 precisa de 7 ou 8 dígitos.'];if(v.length===7)return [v,'']}if(format==='upc'){if(!/^\d{11,12}$/.test(v))return [null,'UPC-A precisa de 11 ou 12 dígitos.'];if(v.length===11)return [v,'']}if(format==='code39'&&!/^[0-9A-Z. $/+%-]+$/.test(v))return [null,'Há caracteres que não pertencem ao Code 39.'];return [v,'']}
function generate(){if(!window.JsBarcode){setStatus('Motor de código de barras indisponível. Verifique a ligação.',true);return}let [v,error]=validAndValue();validation.textContent=specs[format].validation;if(error){svg.innerHTML='';empty.hidden=false;setStatus(error,true);$('download').disabled=true;$('print').disabled=true;return}if(!v){svg.innerHTML='';empty.hidden=false;setStatus('Introduza um valor para gerar o código.');$('download').disabled=true;$('print').disabled=true;return}try{JsBarcode(svg,v,{format:format==='upc'?'upc':format,lineColor:'#111',background:'#f6f4ef',width:Number($('width').value),height:Number($('height').value),displayValue:$('show-text').checked,fontSize:13,margin:12});empty.hidden=true;setStatus(`${specs[format].name} gerado.`);$('download').disabled=false;$('print').disabled=false}catch(e){svg.innerHTML='';empty.hidden=false;$('download').disabled=true;$('print').disabled=true;setStatus('Não foi possível gerar este código. Verifique o valor.',true);console.error('Barcode generator',e)}}
function selectFormat(next){format=next;document.querySelectorAll('.format').forEach(b=>b.classList.toggle('active',b.dataset.format===format));$('format-hint').textContent=specs[format].hint;value.value='';svg.innerHTML='';empty.hidden=false;$('download').disabled=true;$('print').disabled=true;setStatus('Pronto para gerar.');validation.textContent=specs[format].validation}
document.querySelectorAll('.format').forEach(b=>b.addEventListener('click',()=>selectFormat(b.dataset.format)));$('generate').addEventListener('click',generate);value.addEventListener('input',()=>{if(value.value.trim())generate()});$('clear').addEventListener('click',()=>{value.value='';svg.innerHTML='';empty.hidden=false;$('download').disabled=true;$('print').disabled=true;setStatus('Campos limpos.')});$('width').addEventListener('input',()=>{$('width-out').textContent=$('width').value+'×';if(value.value.trim())generate()});$('height').addEventListener('input',()=>{$('height-out').textContent=$('height').value+' px';if(value.value.trim())generate()});$('show-text').addEventListener('change',generate);
$('download').addEventListener('click',()=>{if($('download').disabled)return;const source=new XMLSerializer().serializeToString(svg),blob=new Blob([source],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nexauren-${format}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)});
$('print').addEventListener('click',()=>{if($('print').disabled)return;const source=new XMLSerializer().serializeToString(svg),w=window.open('','_blank','noopener,noreferrer');if(!w){setStatus('O navegador bloqueou a janela de impressão.',true);return}w.document.write(`<!doctype html><title>Nexauren Barcode</title><body style="margin:40px;display:grid;place-items:center">${source}<script>window.onload=()=>window.print()<\/script></body>`);w.document.close()});
$('year').textContent=new Date().getFullYear();onAuthStateChanged(auth,user=>{gateState(!user);if(user)setStatus('Pronto para gerar.')});