(()=>{"use strict";
function boot(){
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={file:null,url:"",buffer:null,peaks:null,duration:0,start:0,end:0,format:"wav",result:null,resultUrl:"",busy:false,cancel:false,lang:"pt"};
const TXT={pt:{audioTools:"Ferramentas de áudio",title:"Audio Trimmer",lead:"Corte exatamente o trecho que precisa. Arraste os marcadores, faça preview do recorte e exporte sem sair do navegador.",loadAudio:"Carregar áudio",choose:"Escolher ficheiro",supported:"WAV, MP3, FLAC, OGG, M4A e outros formatos suportados",noFile:"Nenhum ficheiro",selectRegion:"Selecione a região",start:"START",selection:"SELECTION",end:"END",markStart:"Marcar início",markEnd:"Marcar fim",processing:"Processamento",local:"LOCAL",startTime:"Início",endTime:"Fim",fadeIn:"Fade in",fadeOut:"Fade out",gain:"Gain",normalize:"Normalize",normalizeHint:"Peak control",format:"Export format",clipLength:"Duração do recorte",trimButton:"Cortar áudio",cancel:"Cancelar",readyHint:"Escolha um áudio para começar.",result:"Resultado",download:"Download"},en:{audioTools:"Audio tools",title:"Audio Trimmer",lead:"Cut exactly the section you need. Drag the markers, preview the selection, and export without leaving your browser.",loadAudio:"Load audio",choose:"Choose file",supported:"WAV, MP3, FLAC, OGG, M4A and other supported formats",noFile:"No file",selectRegion:"Select the region",start:"START",selection:"SELECTION",end:"END",markStart:"Mark start",markEnd:"Mark end",processing:"Processing",local:"LOCAL",startTime:"Start",endTime:"End",fadeIn:"Fade in",fadeOut:"Fade out",gain:"Gain",normalize:"Normalize",normalizeHint:"Peak control",format:"Export format",clipLength:"Clip duration",trimButton:"Trim audio",cancel:"Cancel",readyHint:"Choose an audio file to begin.",result:"Result",download:"Download"}};
const t=k=>TXT[state.lang]?.[k]||TXT.pt[k]||k;
function notify(m,e){const x=$("#toast");x.textContent=m;x.className="at-toast show"+(e?" error":"");clearTimeout(notify.t);notify.t=setTimeout(()=>x.className="at-toast",2600)}
function time(s){s=Math.max(0,Number(s)||0);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(Math.floor(s%60)).padStart(2,"0")}
function parse(v){v=String(v||"").trim();if(!v)return null;if(/^\d+(?:\.\d+)?$/.test(v))return Number(v);const p=v.split(":").map(Number);return p.length===2&&p.every(Number.isFinite)?p[0]*60+p[1]:null}
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return(v>=100||i===0?v.toFixed(0):v.toFixed(1))+" "+u[i]}
function base(n){return String(n||"audio").replace(/\.[^/.]+$/,"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,65)||"audio"}
function draw(data,p=0){const c=$("#wave"),r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(280,Math.floor(r.width*d)),h=Math.max(100,Math.floor(c.height*d));c.width=w;c.height=h;const x=c.getContext("2d");x.clearRect(0,0,w,h);for(let i=1;i<4;i++){x.strokeStyle="rgba(255,255,255,.04)";x.beginPath();x.moveTo(0,h*i/4);x.lineTo(w,h*i/4);x.stroke()}const g=x.createLinearGradient(0,0,w,0);g.addColorStop(0,"#ffb84f");g.addColorStop(1,"#74f0be");x.strokeStyle=g;x.lineWidth=Math.max(1,d);const a=data||new Float32Array([.04,.08,.06,.1]),mid=h/2,amp=h*.42,step=Math.max(1,Math.floor(a.length/w));x.beginPath();for(let px=0;px<w;px++){let mn=0,mx=0,s=px*step,e=Math.min(a.length,s+step);for(let i=s;i<e;i++){const v=a[i];if(v<mn)mn=v;if(v>mx)mx=v}x.moveTo(px,mid+mn*amp);x.lineTo(px,mid+mx*amp)}x.stroke()}
function peakData(buf,n=2200){const out=new Float32Array(n),st=Math.max(1,Math.floor(buf.length/n));for(let i=0;i<n;i++){const s=i*st,e=Math.min(buf.length,s+st);let p=0;for(let c=0;c<buf.numberOfChannels;c++){const a=buf.getChannelData(c);for(let j=s;j<e;j++){const q=Math.abs(a[j]);if(q>p)p=q}}out[i]=p}return out}
function refreshSelection(){const d=state.duration||0,start=state.start,end=state.end||d,s= d?start/d:0,e=d?end/d:1;$("#start-handle").style.left=(s*100)+"%";$("#end-handle").style.left=(e*100)+"%";$("#selection-band").style.left=(s*100)+"%";$("#selection-band").style.width=((e-s)*100)+"%";$("#start-readout").textContent=time(start);$("#end-readout").textContent=time(end);$("#total-readout").textContent="/ "+time(d);$("#clip-duration").textContent=time(Math.max(0,end-start));$("#start-input").value=time(start);$("#end-input").value=time(end)}
function setSelection(a,b){const d=state.duration;if(!d)return;state.start=Math.max(0,Math.min(d,a));state.end=Math.max(state.start+.01,Math.min(d,b));refreshSelection()}
function loadFile(file){if(!file)return;const ok=file.type.startsWith("audio/")||/\.(wav|mp3|flac|ogg|m4a|aac|opus|webm)$/i.test(file.name);if(!ok)return notify("Escolha um ficheiro de áudio válido",true);if(file.size>180*1024*1024)return notify("Ficheiro demasiado grande (máx. 180 MB)",true);if(state.url)URL.revokeObjectURL(state.url);state.file=file;state.url=URL.createObjectURL(file);$("#file-name").textContent=file.name;$("#file-meta").textContent=bytes(file.size)+" · "+(file.type||"audio");$("#clear-file").hidden=false;$("#player").src=state.url;$("#status").textContent="Áudio carregado";$("#state-badge").textContent="READY";$("#trim").disabled=false;const title=base(file.name).replace(/-/g," ");setTimeout(()=>{if(!$("#start-input").value)$("#start-input").value="0:00"},0);(async()=>{try{const C=window.AudioContext||window.webkitAudioContext;if(!C)throw 0;const ctx=new C(),b=await ctx.decodeAudioData(await file.arrayBuffer());await ctx.close().catch(()=>{});state.buffer=b;state.duration=b.duration;state.end=b.duration;state.peaks=peakData(b);draw(state.peaks);refreshSelection()}catch(e){const dur=Number($("#player").duration)||0;state.duration=dur;state.end=dur;draw(new Float32Array([.08,.12,.18,.1,.2,.14]));refreshSelection()}})();$("#meta-title")?.setAttribute("value",title)}
function clearFile(){if(state.url)URL.revokeObjectURL(state.url);if(state.resultUrl)URL.revokeObjectURL(state.resultUrl);state.file=null;state.url="";state.resultUrl="";state.buffer=null;state.duration=0;state.start=0;state.end=0;state.peaks=null;$("#file-name").textContent=t("noFile");$("#file-meta").textContent="—";$("#clear-file").hidden=true;$("#trim").disabled=true;$("#status").textContent=t("readyHint");$("#player").removeAttribute("src");$("#player").load();$("#result").hidden=true;draw(new Float32Array([.03,.05,.04]));refreshSelection()}
function setFormat(f){state.format=f;$$("[data-format]").forEach(b=>b.classList.toggle("active",b.dataset.format===f));$("#out-format").textContent=f.toUpperCase()}
function applyLang(){document.documentElement.lang=state.lang;$$("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));$("#lang-toggle").textContent=state.lang==="pt"?"EN":"PT"}
function int16(v){return Math.max(-32768,Math.min(32767,Math.round(v*32767)))}
function wav(buf){const ch=buf.numberOfChannels,sr=buf.sampleRate,n=buf.length,size=n*ch*2,a=new ArrayBuffer(44+size),v=new DataView(a);const str=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};str(0,"RIFF");v.setUint32(4,36+size,true);str(8,"WAVE");str(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,sr,true);v.setUint32(28,sr*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);str(36,"data");v.setUint32(40,size,true);let p=44;for(let i=0;i<n;i++)for(let c=0;c<ch;c++){v.setInt16(p,int16(buf.getChannelData(c)[i]),true);p+=2}return new Blob([a],{type:"audio/wav"})}
async function loadLame(){if(window.lamejs)return;await new Promise((res,rej)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@breezystack/lamejs@1.2.7/dist/lamejs.iife.js";s.onload=res;s.onerror=()=>rej(new Error("encoder")) ;document.head.appendChild(s)})}
async function mp3(buf){await loadLame();const ch=Math.min(2,buf.numberOfChannels),enc=new lamejs.Mp3Encoder(ch,buf.sampleRate,192),L=new Int16Array(buf.length),R=ch===2?new Int16Array(buf.length):null;for(let i=0;i<buf.length;i++){L[i]=int16(buf.getChannelData(0)[i]);if(R)R[i]=int16(buf.getChannelData(1)[i])}const out=[];for(let i=0;i<L.length;i+=1152){if(state.cancel)throw new Error("cancel");const m=enc.encodeBuffer(L.subarray(i,i+1152),R?R.subarray(i,i+1152):undefined);if(m.length)out.push(m);if(i%46080===0)setProgress(30+60*i/L.length,"MP3",true);await new Promise(r=>setTimeout(r,0))}const fin=enc.flush();if(fin.length)out.push(fin);return new Blob(out,{type:"audio/mpeg"})}
function setProgress(p,l,c){$("#progress").hidden=false;$("#progress-fill").style.width=Math.min(100,p)+"%";$("#progress-pct").textContent=Math.round(p)+"%";$("#progress-label").textContent=l;$("#cancel").hidden=!c}
function resetProgress(){$("#progress").hidden=true;$("#progress-fill").style.width="0%";$("#cancel").hidden=true}
async function process(){if(!state.buffer||state.busy)return notify("Carregue um áudio primeiro",true);state.busy=true;state.cancel=false;$("#trim").disabled=true;setProgress(8,"Rendering",true);try{const start=state.start,end=state.end||state.duration,off=new OfflineAudioContext(state.buffer.numberOfChannels,Math.ceil((end-start)*state.buffer.sampleRate),state.buffer.sampleRate),src=off.createBufferSource();src.buffer=state.buffer;src.connect(off.destination);src.start(0,start,end-start);let b=await off.startRendering();if(state.cancel)throw new Error("cancel");const gain=Math.pow(10,(Number($("#gain").value)||0)/20),fi=Number($("#fade-in").value)||0,fo=Number($("#fade-out").value)||0;let peak=0;for(let c=0;c<b.numberOfChannels;c++){const a=b.getChannelData(c);for(let i=0;i<a.length;i++){a[i]*=gain;peak=Math.max(peak,Math.abs(a[i]))}}if($("#normalize").checked&&peak){const g=Math.min(1,.89125/peak);for(let c=0;c<b.numberOfChannels;c++){const a=b.getChannelData(c);for(let i=0;i<a.length;i++)a[i]*=g}}for(let c=0;c<b.numberOfChannels;c++){const a=b.getChannelData(c),n=a.length,fiN=Math.min(n,Math.floor(fi*b.sampleRate)),foN=Math.min(n,Math.floor(fo*b.sampleRate));for(let i=0;i<fiN;i++)a[i]*=i/Math.max(1,fiN);for(let i=0;i<foN;i++)a[n-1-i]*=i/Math.max(1,foN)}setProgress(30,"Encoding",true);const blob=state.format==="wav"?wav(b):await mp3(b);if(state.cancel)throw new Error("cancel");state.result=blob;if(state.resultUrl)URL.revokeObjectURL(state.resultUrl);state.resultUrl=URL.createObjectURL(blob);$("#result-name").textContent=base(state.file.name)+"_trimmed."+state.format;$("#result-meta").textContent=state.format.toUpperCase()+" · "+bytes(blob.size)+" · "+time(b.duration);$("#result-player").src=state.resultUrl;$("#result").hidden=false;setProgress(100,"Complete",false);$("#status").textContent="Concluído";$("#state-badge").textContent="DONE";notify("Áudio cortado com sucesso");fetch("/api/tools/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tool_id:"audio-trimmer"})}).catch(()=>{})}catch(e){resetProgress();$("#status").textContent=e.message==="cancel"?"Cancelado":"Falha no processamento";notify($("#status").textContent,true)}finally{state.busy=false;state.cancel=false;$("#trim").disabled=!state.buffer}}
function pointerToTime(ev){const r=$(".at-wave-wrap")?.getBoundingClientRect();if(!r)return 0;return Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width))*state.duration}
function drag(which){return ev=>{ev.preventDefault();const move=e=>{const t=pointerToTime(e);if(which==="start")setSelection(Math.min(t,state.end-.01),state.end);else setSelection(state.start,Math.max(t,state.start+.01))};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);}}
$("#start-handle").addEventListener("pointerdown",drag("start"));$("#end-handle").addEventListener("pointerdown",drag("end"));
$("#wave-hit").addEventListener("pointerdown",e=>{const r=$("#wave-hit").getBoundingClientRect(),t=((e.clientX-r.left)/r.width)*state.duration;if(Math.abs(t-state.start)<Math.abs(t-state.end))setSelection(t,state.end);else setSelection(state.start,t)});
$("#start-input").addEventListener("change",()=>{const a=parse($("#start-input").value);if(a!=null)setSelection(a,state.end)});$("#end-input").addEventListener("change",()=>{const b=parse($("#end-input").value);if(b!=null)setSelection(state.start,b)});
$$("[data-mark]").forEach(b=>b.addEventListener("click",()=>{const p=$("#player").currentTime;if(b.dataset.mark==="start")setSelection(p,state.end);else setSelection(state.start,p)}));
$$("[data-preset]").forEach(b=>b.addEventListener("click",()=>{if(!state.duration)return;const d=state.duration;if(b.dataset.preset==="first10")setSelection(0,Math.min(10,d));else if(b.dataset.preset==="last10")setSelection(Math.max(0,d-10),d);else setSelection(0,d)}));
$$("[data-format]").forEach(b=>b.addEventListener("click",()=>setFormat(b.dataset.format)));
$("#file-input").addEventListener("change",e=>loadFile(e.target.files?.[0]));$("#clear-file").addEventListener("click",clearFile);$("#trim").addEventListener("click",process);$("#cancel").addEventListener("click",()=>{state.cancel=true;$("#status").textContent="A cancelar…"});
$("#download").addEventListener("click",()=>{if(!state.result)return;const a=document.createElement("a");a.href=state.resultUrl;a.download=base(state.file.name)+"_trimmed."+state.format;document.body.appendChild(a);a.click();a.remove()});
$("#player").addEventListener("timeupdate",()=>{$("#start-readout").textContent=time(state.start);$("#end-readout").textContent=time(state.end);draw(state.peaks||new Float32Array([.03]),state.duration?$("#player").currentTime/state.duration:0)});
$("#gain").addEventListener("input",()=>{$("#gain-val").textContent=Number($("#gain").value).toFixed(1)+" dB"});$("#lang-toggle").addEventListener("click",()=>{state.lang=state.lang==="pt"?"en":"pt";applyLang()});window.addEventListener("resize",()=>draw(state.peaks||new Float32Array([.03])));
applyLang();draw(new Float32Array([.03,.05,.08,.04]));
}
window.addEventListener("error",e=>{console.error("Audio Trimmer boot error:",e.error||e.message);const s=document.querySelector("#status");if(s)s.textContent="Erro ao iniciar a ferramenta";});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();