const $=s=>document.querySelector(s);let direction="json-csv";
const source=$("#source"),output=$("#output"),delimiter=$("#delimiter"),headers=$("#headers"),pretty=$("#pretty"),message=$("#message"),sourceLabel=$("#source-label"),outputLabel=$("#output-label"),outputStatus=$("#output-status"),sourceCount=$("#source-count");
const isEnglish=()=>new URLSearchParams(location.search).get("lang")==="en"||(()=>{try{return localStorage.getItem("ns_lang")==="en"}catch{return false}})();
function setMessage(text,type="idle"){message.textContent=text;message.className="message "+type}
function updateLabels(){const jsonToCsv=direction==="json-csv";sourceLabel.textContent=jsonToCsv?"01 · JSON DE ENTRADA":"01 · CSV DE ENTRADA";outputLabel.textContent=jsonToCsv?"02 · CSV DE SAÍDA":"02 · JSON DE SAÍDA";$("#jsonToCsv").classList.toggle("active",jsonToCsv);$("#csvToJson").classList.toggle("active",!jsonToCsv)}
function quoteCsv(value,delim){let s=value==null?"":String(value);if(/[\r\n"]/.test(s)||s.includes(delim))s='"'+s.replace(/"/g,'""')+'"';return s}
function jsonCell(value){if(value===null||value===undefined)return "";if(typeof value==="object")return JSON.stringify(value);return String(value)}
function jsonToCsv(){let data;try{data=JSON.parse(source.value)}catch(e){throw new Error((isEnglish()?"Invalid JSON: ":"JSON inválido: ")+e.message)}if(!Array.isArray(data))throw new Error(isEnglish()?"JSON must be an array of objects.":"O JSON precisa ser um array de objetos.");if(data.length===0)return "";if(data.some(v=>v===null||typeof v!=="object"||Array.isArray(v)))throw new Error(isEnglish()?"Use an array containing objects, for example [{\"name\":\"Nexauren\"}].":"Use um array contendo objetos, por exemplo [{\"nome\":\"Nexauren\"}].");const cols=[];data.forEach(row=>Object.keys(row).forEach(k=>{if(!cols.includes(k))cols.push(k)}));const delim=delimiter.value==="auto"?",":delimiter.value;const rows=[cols.map(c=>quoteCsv(c,delim)).join(delim)];data.forEach(row=>rows.push(cols.map(c=>quoteCsv(jsonCell(row[c]),delim)).join(delim)));return rows.join("\n")}
function parseCsv(csv,delim){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<csv.length;i++){const ch=csv[i];if(quoted){if(ch==='"'){if(csv[i+1]==='"'){field+='"';i++}else quoted=false}else field+=ch}else{if(ch==='"'&&field===""){quoted=true}else if(ch===delim){row.push(field);field=""}else if(ch==="\n"){row.push(field);rows.push(row);row=[];field=""}else if(ch==="\r"){if(csv[i+1]==="\n")i++;row.push(field);rows.push(row);row=[];field=""}else field+=ch}}if(quoted)throw new Error(isEnglish()?"Invalid CSV: unclosed quotes.":"CSV inválido: aspas não fechadas.");row.push(field);if(row.length>1||row[0]!=="")rows.push(row);return rows}
function detectDelimiter(csv){const first=(csv.split(/\r?\n/).find(Boolean)||"");const candidates=[",",";","\t"];let best=",",score=-1;candidates.forEach(d=>{const n=first.split(d).length-1;if(n>score){score=n;best=d}});return score>0?best:","}
function infer(v){const s=v.trim();if(s==="")return "";if(s==="true")return true;if(s==="false")return false;if(s==="null")return null;const n=Number(s);if(Number.isFinite(n)&&s===String(n))return n;if((s.startsWith("{")&&s.endsWith("}"))||(s.startsWith("[")&&s.endsWith("]"))){try{return JSON.parse(s)}catch{}}return v}
function csvToJson(){const delim=delimiter.value==="auto"?detectDelimiter(source.value):delimiter.value;const rows=parseCsv(source.value,delim);if(!rows.length)throw new Error(isEnglish()?"Empty CSV.":"CSV vazio.");let cols;if(headers.checked){cols=rows.shift();if(!cols.length)throw new Error(isEnglish()?"Could not read the header.":"Não foi possível ler o cabeçalho.")}else cols=(rows[0]||[]).map((_,i)=>"coluna_"+(i+1));const used=new Set();cols=cols.map((c,i)=>{let base=c.trim()||"coluna_"+(i+1),name=base,n=2;while(used.has(name))name=base+"_"+n++;used.add(name);return name});const result=rows.filter(r=>r.some(v=>v!=="")).map(r=>Object.fromEntries(cols.map((c,i)=>[c,infer(r[i]??"")])));return JSON.stringify(result,null,pretty.checked?2:0)}
function convert(){sourceCount.textContent=source.value.length+" "+(isEnglish()?"characters":"caracteres");try{const out=direction==="json-csv"?jsonToCsv():csvToJson();output.value=out;outputStatus.textContent=out?"Concluído":"Vazio";setMessage(out?"Conversão concluída localmente.":"Nenhum dado para converter.","ok")}catch(e){output.value="";outputStatus.textContent="Erro";setMessage(e.message,"error")}}
function copyResult(){if(!output.value)return;navigator.clipboard?.writeText(output.value).then(()=>setMessage("Resultado copiado para a área de transferência.","ok")).catch(()=>setMessage("Não foi possível copiar automaticamente.","error"))}
function sampleData(){if(direction==="json-csv"){source.value=JSON.stringify(isEnglish()?[{name:"Ana",age:27,city:"Maputo"},{name:"John",age:31,city:"Beira"},{name:"Mia",age:24,city:"Nampula"}]:[{nome:"Ana",idade:27,cidade:"Maputo"},{nome:"João",idade:31,cidade:"Beira"},{nome:"Mia",idade:24,cidade:"Nampula"}],null,2)}else source.value="nome,idade,cidade\nAna,27,Maputo\nJoão,31,Beira\nMia,24,Nampula";sourceCount.textContent=source.value.length+" caracteres";convert()}
function swap(){direction=direction==="json-csv"?"csv-json":"json-csv";updateLabels();source.value="";output.value="";setMessage("Direção alterada. Insira os dados e converta.")}
$("#jsonToCsv").addEventListener("click",()=>{direction="json-csv";updateLabels();setMessage("Direção JSON → CSV selecionada.")});
$("#csvToJson").addEventListener("click",()=>{direction="csv-json";updateLabels();setMessage("Direção CSV → JSON selecionada.")});
$("#convert").addEventListener("click",convert);$("#copy").addEventListener("click",copyResult);$("#sample").addEventListener("click",sampleData);$("#swap").addEventListener("click",swap);
$("#clear").addEventListener("click",()=>{source.value="";output.value="";sourceCount.textContent="0 "+(isEnglish()?"characters":"caracteres");outputStatus.textContent="Aguardando";setMessage("Campos limpos.")});source.addEventListener("input",()=>sourceCount.textContent=source.value.length+" caracteres");
pretty.addEventListener("change",()=>{if(direction==="csv-json"&&source.value.trim())convert()});headers.addEventListener("change",()=>{if(direction==="csv-json"&&source.value.trim())convert()});
updateLabels();sourceCount.textContent=source.value.length+" caracteres";