import {auth,onAuthStateChanged} from "/account/account-client.js?v=20260922-3";
const TOOL_ID="gerador-de-orcamentos";const gate=document.getElementById("gate"),app=document.getElementById("app"),unlock=document.getElementById("unlock"),msg=document.getElementById("gate-msg");
const q=s=>document.querySelector(s),money=n=>"$"+Number(n||0).toFixed(2),esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function row(){const d=document.createElement("div");d.className="item";d.innerHTML='<input class="desc" placeholder="Descrição do serviço/produto"><input class="qty" type="number" min="0" step="0.01" value="1"><input class="unit" type="number" min="0" step="0.01" value="0"><button type="button" aria-label="Remover">×</button>';d.querySelectorAll("input").forEach(x=>x.addEventListener("input",calc));d.querySelector("button").onclick=()=>{d.remove();calc()};q("#items").appendChild(d)}
function calc(){let sub=0;document.querySelectorAll(".item").forEach(r=>sub+=Number(r.querySelector(".qty").value||0)*Number(r.querySelector(".unit").value||0));const disc=Math.min(100,Math.max(0,Number(q("#discount").value||0))),tax=Math.max(0,Number(q("#tax").value||0)),d=sub*disc/100,base=sub-d,t=base*tax/100;q("#subtotal").textContent=money(sub);q("#discountOut").textContent=money(d);q("#taxOut").textContent=money(t);q("#total").textContent=money(base+t)}
async function api(path,options={}){const u=auth.currentUser;if(!u)throw Error("Inicie sessão para continuar.");const token=await u.getIdToken();const r=await fetch(path,{...options,headers:{"Authorization":"Bearer "+token,"content-type":"application/json",...(options.headers||{})}});const x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||"Não foi possível concluir.");return x}
async function openApp(){gate.hidden=true;app.hidden=false;row();row();q("#date").value=new Date().toISOString().slice(0,10);calc()}
async function start(){try{const r=await api("/api/tool/unlock?tool_id="+encodeURIComponent(TOOL_ID));if(r.unlocked){openApp();return}msg.textContent="Esta ferramenta está disponível apenas para contas com o plano Pro ativo."}catch(e){msg.textContent=e.message}}
unlock.onclick=()=>{location.href="/account/upgrade/"};
q("#add").onclick=row;q("#discount").oninput=calc;q("#tax").oninput=calc;q("#print").onclick=()=>window.print();q("#year").textContent=new Date().getFullYear();onAuthStateChanged(auth,user=>{if(user)start();else msg.textContent="Inicie sessão na Conta Nexauren para desbloquear por $0,50.";});
