const state={user:null,view:"dashboard",media:[],toolRegistry:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const slugify=v=>String(v||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/['’"]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-{2,}/g,"-").slice(0,180);
const date=v=>{if(!v)return"—";try{return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}catch{return v;}};
const local=v=>{if(!v)return"";const d=new Date(v),p=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+"T"+p(d.getHours())+":"+p(d.getMinutes());};
const toast=(m,k="ok")=>{const e=document.createElement("div");e.className="toast "+k;e.textContent=m;$("#toast-root").append(e);setTimeout(()=>e.remove(),2800)};
async function api(path,o={}){const x=Object.assign({credentials:"same-origin"},o);if(x.body&&!(x.body instanceof FormData))x.headers=Object.assign({"content-type":"application/json"},x.headers||{});const r=await fetch(path,x),d=await r.json().catch(()=>({ok:false,error:"Resposta inválida"}));if(!r.ok)throw new Error(d.error||"Pedido falhou");return d;}
function show(v){
  state.view=v;
  document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));
  const root=$("#view-"+v);if(root)root.classList.add("active-view");
  document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));
  $("#top-title").textContent={dashboard:"Painel central",tools:"Ferramentas",users:"Utilizadores",stats:"Estatísticas",media:"Multimédia",settings:"Definições",activity:"Atividade"}[v]||"Nexauren";
  if(v==="dashboard")dashboard();
  if(v==="tools")toolsAdmin();
  if(v==="users")usersAdmin();
  if(v==="stats")statsAdmin();
  if(v==="media")media();
  if(v==="settings")settings();
  if(v==="activity")activity();
  $(".sidebar")?.classList.remove("open");
}
function enterLogin(){$("#login-view").classList.remove("hidden");$("#app-shell").classList.add("hidden");}
async function enterApp(){$("#login-view").classList.add("hidden");$("#app-shell").classList.remove("hidden");$("#user-pill").textContent=state.user.display_name+" · "+state.user.role;try{await loadShared()}catch(e){console.warn("Admin dados partilhados:",e)}finally{await show("dashboard")}}
async function loadShared(){const d=await api("/api/media");state.media=d.media||[];}
$("#login-form").onsubmit=async e=>{e.preventDefault();$("#login-error").textContent="";try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("#login-email").value,password:$("#login-password").value})});state.user=d.user;enterApp();toast("Sessão iniciada.");}catch(x){$("#login-error").textContent=x.message;}};
$("#logout-btn").onclick=async()=>{try{await api("/api/auth/logout",{method:"POST"})}finally{location.reload()}};
$("#mobile-menu").onclick=()=>$(".sidebar").classList.add("open");$("#sidebar-close").onclick=()=>$(".sidebar").classList.remove("open");Array.from(document.querySelectorAll(".nav-item")).forEach(b=>b.onclick=()=>show(b.dataset.view));
const badge=s=>'<span class="badge '+s+'">'+esc(s)+"</span>";
async function dashboard(){
  try{
    const stats=await api("/api/stats"),activityData=await api("/api/activity"),x=stats.stats||{};
    $("#view-dashboard").innerHTML='<div class="view-header"><div><div class="eyebrow">Centro de administração</div><h1>O centro das ferramentas Nexauren.</h1><p>Gerir ferramentas, utilizadores, multimédia e desempenho num só painel.</p></div></div>'+
      '<div class="admin-hub"><button class="hub-card hub-tools" data-hub="tools"><span class="hub-icon">✦</span><span><strong>Ferramentas</strong><small>Gerir catálogo, acesso, destaques, populares e ordem.</small></span><b>→</b></button><button class="hub-card hub-users" data-hub="users"><span class="hub-icon">◎</span><span><strong>Utilizadores</strong><small>Ver contas e acessos administrativos.</small></span><b>→</b></button><button class="hub-card hub-stats" data-hub="stats"><span class="hub-icon">▥</span><span><strong>Estatísticas</strong><small>Acompanhar uso das ferramentas e atividade.</small></span><b>→</b></button></div>'+
      '<div class="stats"><div class="stat"><div class="value">'+x.tools+'</div><div class="label">Ferramentas</div></div><div class="stat"><div class="value">'+x.publicUsers+'</div><div class="label">Utilizadores</div></div><div class="stat"><div class="value">'+x.toolViews30d+'</div><div class="label">Visitas / 30d</div></div><div class="stat"><div class="value">'+x.media+'</div><div class="label">Multimédia</div></div></div>'+
      '<div class="dashboard-grid"><div class="panel"><div class="panel-pad"><div class="panel-title">Última atividade</div></div><div class="list">'+(activityData.activity||[]).slice(0,6).map(x=>'<div class="list-row"><div><div class="row-title">'+esc(x.action)+'</div><div class="row-meta">'+date(x.created_at)+'</div></div></div>').join("")+'</div></div></div>';
    document.querySelectorAll("[data-hub]").forEach(b=>b.onclick=()=>show(b.dataset.hub));
  }catch(e){$("#view-dashboard").innerHTML='<div class="empty-state"><h2>Painel temporariamente indisponível.</h2><p>'+esc(e.message)+'</p></div>'}
}
async function toolsAdmin(){
  try{
    const d=await api("/api/admin/tools");state.toolRegistry=d.registry||{categories:[],tools:[]};
    const r=state.toolRegistry,tools=r.tools||[],cats=r.categories||[];
    $("#view-tools").innerHTML='<div class="view-header"><div><div class="eyebrow">Centro de ferramentas</div><h1>Ferramentas</h1><p>Controle catálogo, categorias, destaques, populares, acesso e apresentação.</p></div><div class="header-actions"><button class="secondary" id="tool-refresh">↻ Atualizar</button></div></div>'+
      '<div class="stats tool-admin-stats"><div class="stat"><div class="value">'+tools.length+'</div><div class="label">Ferramentas</div></div><div class="stat"><div class="value">'+tools.filter(t=>t.status==="active").length+'</div><div class="label">Ativas</div></div><div class="stat"><div class="value">'+tools.filter(t=>t.featured).length+'</div><div class="label">Destaques</div></div><div class="stat"><div class="value">'+tools.filter(t=>t.popular).length+'</div><div class="label">Populares</div></div></div>'+
      '<div class="setting-card add-tool-card"><h3>Adicionar ferramenta</h3><p>Registe uma nova ferramenta no catálogo sem mexer no código da página pública.</p>'+
      '<div class="admin-form-grid"><input id="nt-name" placeholder="Nome da ferramenta"><input id="nt-id" placeholder="ID / slug"><input id="nt-path" placeholder="/tool/categoria/ferramenta/"><select id="nt-cat">'+cats.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join("")+'</select><input id="nt-icon" placeholder="Ícone" value="✦"><input id="nt-version" placeholder="Versão" value="1.0.0"><select id="nt-status"><option value="active">Ativa</option><option value="draft">Rascunho</option><option value="disabled">Desativada</option></select><select id="nt-access"><option value="public">Pública</option><option value="account">Conta</option><option value="premium">Premium</option></select></div>'+
      '<textarea id="nt-desc" class="compact-area" placeholder="Descrição curta"></textarea><input id="nt-tags" placeholder="Etiquetas separadas por vírgula"><div class="check-row"><label class="check"><input id="nt-featured" type="checkbox"> Destaque</label><label class="check"><input id="nt-popular" type="checkbox"> Popular</label></div><button class="primary" id="tool-add">Adicionar ao catálogo</button></div>'+
      '<div class="tool-admin-list">'+tools.map(t=>'<article class="tool-admin-card" data-tool="'+esc(t.id)+'"><div class="tool-admin-card-head"><div><div class="eyebrow">'+esc(t.category||"sem categoria")+'</div><h3>'+esc(t.name)+'</h3><small>'+esc(t.path)+'</small></div><div class="tool-badges">'+(t.featured?'<span class="badge featured">DESTAQUE</span>':"")+(t.popular?'<span class="badge popular">POPULAR</span>':"")+'</div></div>'+
        '<div class="admin-form-grid"><label><span>Nome</span><input data-f="name" value="'+esc(t.name)+'"></label><label><span>ID</span><input data-f="id" value="'+esc(t.id)+'"></label><label><span>Categoria</span><select data-f="category">'+cats.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===t.category?"selected":"")+'>'+esc(x.name)+'</option>').join("")+'</select></label><label><span>Caminho</span><input data-f="path" value="'+esc(t.path)+'"></label><label><span>Versão</span><input data-f="version" value="'+esc(t.version||"1.0.0")+'"></label><label><span>Acesso</span><select data-f="access"><option value="public" '+(t.access==="public"?"selected":"")+'>Público</option><option value="account" '+(t.access==="account"?"selected":"")+'>Conta</option><option value="premium" '+(t.access==="premium"?"selected":"")+'>Premium</option></select></label><label><span>Estado</span><select data-f="status"><option value="active" '+(t.status==="active"?"selected":"")+'>Ativa</option><option value="draft" '+(t.status==="draft"?"selected":"")+'>Rascunho</option><option value="disabled" '+(t.status==="disabled"?"selected":"")+'>Desativada</option></select></label><label><span>Ordem</span><input data-f="sortOrder" type="number" value="'+Number(t.sortOrder||0)+'"></label></div>'+
        '<label class="full-field"><span>Descrição</span><textarea data-f="description" class="compact-area">'+esc(t.description||"")+'</textarea></label><label class="full-field"><span>Etiquetas</span><input data-f="tags" value="'+esc((t.tags||[]).join(", "))+'"></label><div class="check-row"><label class="check"><input data-f="featured" type="checkbox" '+(t.featured?"checked":"")+'> Mostrar em destaque</label><label class="check"><input data-f="popular" type="checkbox" '+(t.popular?"checked":"")+'> Marcar como popular</label></div><div class="admin-card-actions"><span class="usage-note">'+Number(t.usageCount||0)+' visitas únicas / 30 dias</span><div><button class="secondary" data-save-tool>Guardar alterações</button><button class="danger-btn" data-disable-tool>'+ (t.status==="disabled"?"Ativar":"Desativar") +'</button></div></div></article>').join("")+'</div>'+
      '<div class="setting-card"><h3>Categorias do catálogo</h3><p>As categorias continuam alinhadas com os diretórios existentes; o catálogo usa estes dados para a navegação.</p><div class="chip-list">'+cats.map(x=>'<span class="chip">'+esc(x.icon||"✦")+' '+esc(x.name)+'</span>').join("")+'</div></div>';
    $("#tool-refresh").onclick=()=>toolsAdmin();
    $("#nt-name").oninput=()=>{if(!$("#nt-id").dataset.edited)$("#nt-id").value=slugify($("#nt-name").value)};
    $("#nt-id").oninput=()=>$("#nt-id").dataset.edited="1";
    $("#tool-add").onclick=async()=>{
      const id=slugify($("#nt-id").value||$("#nt-name").value);if(!$("#nt-name").value.trim()||!id||!$("#nt-path").value.trim())return toast("Nome, ID e caminho são obrigatórios.","error");
      const next={...r,tools:[...tools,{id,name:$("#nt-name").value.trim(),description:$("#nt-desc").value.trim(),category:$("#nt-cat").value,icon:$("#nt-icon").value.trim()||"✦",version:$("#nt-version").value.trim()||"1.0.0",status:$("#nt-status").value,access:$("#nt-access").value,path:$("#nt-path").value.trim(),tags:$("#nt-tags").value.split(",").map(x=>x.trim()).filter(Boolean),featured:$("#nt-featured").checked,popular:$("#nt-popular").checked,sortOrder:(tools.length+1)*10}]};
      try{state.toolRegistry=(await api("/api/admin/tools",{method:"PUT",body:JSON.stringify(next)})).registry;toast("Ferramenta adicionada.");toolsAdmin()}catch(e){toast(e.message,"error")}
    };
    $("#view-tools").onclick=async e=>{
      const card=e.target.closest("[data-tool]");if(!card)return;const id=card.dataset.tool,t=tools.find(x=>x.id===id);if(!t)return;
      if(e.target.dataset.disableTool!==undefined){t.status=t.status==="disabled"?"active":"disabled";try{state.toolRegistry=(await api("/api/admin/tools",{method:"PUT",body:JSON.stringify(r)})).registry;toast(t.status==="disabled"?"Ferramenta desativada.":"Ferramenta ativada.");toolsAdmin()}catch(x){toast(x.message,"error")}return}
      if(e.target.dataset.saveTool!==undefined){const v={...t};card.querySelectorAll("[data-f]").forEach(el=>{const k=el.dataset.f;if(k==="tags")v.tags=el.value.split(",").map(x=>x.trim()).filter(Boolean);else if(k==="sortOrder")v[k]=Number(el.value||0);else if(el.type==="checkbox")v[k]=el.checked;else v[k]=el.value;});v.id=slugify(v.id||v.name);if(!v.id)return toast("ID inválido.","error");const next={...r,tools:tools.map(x=>x.id===id?v:x)};try{state.toolRegistry=(await api("/api/admin/tools",{method:"PUT",body:JSON.stringify(next)})).registry;toast("Ferramenta atualizada.");toolsAdmin()}catch(x){toast(x.message,"error")}}
    };
  }catch(e){$("#view-tools").innerHTML='<div class="empty-state"><h2>Não foi possível abrir as ferramentas.</h2><p>'+esc(e.message)+'</p></div>'}
}
async function usersAdmin(){
  try{
    const d=await api("/api/admin/users");
    const statusPill=s=>'<span class="badge '+(s==="active"?"published":"archived")+'">'+(s==="active"?"ATIVO":"SUSPENSO")+'</span>';
    const adminRows=(d.admins||[]).map(u=>{
      const action=u.id===state.user.id?"":'<button class="tiny-btn" data-user-kind="admin" data-user-id="'+esc(u.id)+'" data-user-status="'+(u.status==="active"?"suspended":"active")+'">'+(u.status==="active"?"Suspender":"Ativar")+'</button>';
      return '<div class="list-row user-row"><div><div class="row-title">'+esc(u.display_name)+' <span class="mini-role">'+esc(u.role)+'</span></div><div class="row-meta">'+esc(u.email)+' · '+(u.last_login_at?date(u.last_login_at):"Nunca entrou")+'</div></div><div class="actions">'+statusPill(u.status)+action+'</div></div>';
    }).join("");
    const accountRows=(d.accounts||[]).map(u=>'<div class="list-row user-row"><div><div class="row-title">'+esc(u.display_name||"Utilizador")+'</div><div class="row-meta">'+esc(u.email)+' · '+(u.last_seen_at?date(u.last_seen_at):"Sem atividade")+'</div></div><div class="actions">'+statusPill(u.status)+'<button class="tiny-btn" data-user-kind="account" data-user-id="'+esc(u.id)+'" data-user-status="'+(u.status==="active"?"suspended":"active")+'">'+(u.status==="active"?"Suspender":"Ativar")+'</button></div></div>').join("");
    $("#view-users").innerHTML='<div class="view-header"><div><div class="eyebrow">Acesso e comunidade</div><h1>Utilizadores</h1><p>Administradores do painel e contas Nexauren usam áreas separadas.</p></div></div><div class="dashboard-grid user-admin-grid"><div class="panel"><div class="panel-pad"><div class="panel-title">Equipe administrativa</div><div class="panel-subtitle">Contas com acesso ao centro de administração.</div></div><div class="list">'+(adminRows||'<div class="panel-pad muted">Nenhum administrador.</div>')+'</div></div><div class="panel"><div class="panel-pad"><div class="panel-title">Contas Nexauren</div><div class="panel-subtitle">Utilizadores autenticados pelo Firebase.</div></div><div class="list">'+(accountRows||'<div class="panel-pad muted">Nenhuma conta Nexauren registada ou a base de contas não está ligada.</div>')+'</div></div></div>';
    $("#view-users").onclick=async e=>{
      const b=e.target.closest("[data-user-id]");if(!b)return;
      try{await api("/api/admin/users/"+b.dataset.userKind+"/"+encodeURIComponent(b.dataset.userId),{method:"PUT",body:JSON.stringify({status:b.dataset.userStatus})});toast(b.dataset.userStatus==="active"?"Utilizador ativado.":"Utilizador suspenso.");usersAdmin()}catch(x){toast(x.message,"error")}
    };
  }catch(e){$("#view-users").innerHTML='<div class="empty-state"><h2>Não foi possível carregar utilizadores.</h2><p>'+esc(e.message)+'</p></div>'}
}
async function statsAdmin(){
  try{
    const d=await api("/api/stats"),x=d.stats||{};
    $("#view-stats").innerHTML='<div class="view-header"><div><div class="eyebrow">Observabilidade</div><h1>Estatísticas</h1><p>Resumo operacional das ferramentas e utilizadores.</p></div><button class="secondary" id="stats-refresh">↻ Atualizar</button></div>'+
      '<div class="stats stats-large"><div class="stat"><div class="value">'+x.tools+'</div><div class="label">Ferramentas</div></div><div class="stat"><div class="value">'+x.media+'</div><div class="label">Multimédia</div></div><div class="stat"><div class="value">'+x.publicUsers+'</div><div class="label">Utilizadores</div></div><div class="stat"><div class="value">'+x.toolViews30d+'</div><div class="label">Visitas / 30d</div></div></div>'+
      '<div class="list">'+((x.topTools||[]).map((t,i)=>'<div class="list-row"><div><div class="row-title">'+(i+1)+'. '+esc(t.name)+'</div><div class="row-meta">'+esc(t.category||"")+'</div></div><strong>'+Number(t.usageCount||0)+'</strong></div>').join("")||'<div class="panel-pad muted">Ainda não existem dados de uso.</div>')+'</div>';
    $("#stats-refresh").onclick=()=>statsAdmin();
  }catch(e){$("#view-stats").innerHTML='<div class="empty-state"><h2>Não foi possível calcular estatísticas.</h2><p>'+esc(e.message)+'</p></div>'}
}

async function media(){const d=await api("/api/media");state.media=d.media||[];$("#view-media").innerHTML='<div class="view-header"><div><div class="eyebrow">Multimédia</div><h1>Biblioteca de multimédia</h1><p>O ImageKit armazena os ficheiros; o D1 guarda os metadados.</p></div><button class="primary" id="media-up">＋ Carregar imagens</button></div><div class="dropzone"><strong>Carregar para o ImageKit</strong><span>As imagens são enviadas diretamente para o ImageKit.</span></div><div id="media-grid" class="media-grid">'+(state.media.map(m=>'<article class="media-item"><div class="media-thumb"><img src="'+esc(m.thumbnail_url||m.url)+'" alt="'+esc(m.alt_text||m.filename)+'"></div><div class="media-info"><strong>'+esc(m.filename)+'</strong><small>'+Math.round((m.size_bytes||0)/1024)+' KB</small><div class="actions" style="margin-top:8px"><button class="tiny-btn" data-copy="'+esc(m.url)+'">Copiar URL</button><button class="tiny-btn" data-md="'+m.id+'">Eliminar</button></div></div></article>').join(""))||'<div class="empty">Ainda não há multimédia.</div>'+'</div>';$("#media-up").onclick=()=>{const i=document.createElement("input");i.type="file";i.accept="image/*";i.multiple=true;i.onchange=async()=>{for(const f of i.files)await upload(f);media()};i.click()};$("#media-grid").onclick=async e=>{if(e.target.dataset.copy){await navigator.clipboard?.writeText(e.target.dataset.copy);toast("URL copiado.")}if(e.target.dataset.md&&confirm("Eliminar this media record?")){try{await api("/api/media/"+e.target.dataset.md,{method:"DELETE"});toast("Eliminard.");media()}catch(x){toast(x.message,"error")}}};}
async function upload(f){if(f.size>25*1024*1024)return toast(f.name+" ultrapassa 25 MB.","error");try{toast("A comprimir "+f.name+"…");const original=f,f2=await compressImageForImageKit(f),kb=n=>Math.max(1,Math.round(n/1024));const a=await api("/api/media/auth"),fd=new FormData();fd.append("file",f2);fd.append("fileName",f2.name);fd.append("publicKey",a.publicKey);fd.append("signature",a.signature);fd.append("expire",a.expire);fd.append("token",a.token);fd.append("folder","/nexauren-story");fd.append("useUniqueFileName","true");const r=await fetch("https://upload.imagekit.io/api/v1/files/upload",{method:"POST",body:fd}),d=await r.json();if(!r.ok)throw new Error(d.message||"Falha no carregamento para o ImageKit");await api("/api/media",{method:"POST",body:JSON.stringify(d)});toast(f.name+" otimizado: "+kb(original.size)+" KB → "+kb(f2.size)+" KB e enviado.")}catch(x){toast(x.message,"error")}}
async function settings(){const d=await api("/api/settings"),s=d.settings||{};$("#view-settings").innerHTML='<div class="view-header"><div><div class="eyebrow">Sistema</div><h1>Definições</h1><p>Identidade do site e segurança do administrador.</p></div></div><div class="setting-grid"><div class="setting-card"><h3>Geral</h3><p>Metadados públicos do site.</p><div class="field"><label><span>Nome do site</span><input id="s-name" value="'+esc(s.site_name||"Nexauren Story")+'"></label></div><div class="field"><label><span>Descrição</span><textarea id="s-desc">'+esc(s.site_description||"")+'</textarea></label></div><div class="field"><label><span>Idioma</span><input id="s-lang" value="'+esc(s.default_language||"pt")+'"></label></div><div class="field"><label><span>Fuso horário</span><input id="s-tz" value="'+esc(s.timezone||"Africa/Maputo")+'"></label></div><button class="primary" id="s-save">Guardar</button></div><div class="setting-card"><h3>Segurança</h3><p>Alterar a palavra-passe do D1.</p><form id="pw"><div class="field"><label><span>Palavra-passe atual</span><input id="pw-c" type="password" required></label></div><div class="field"><label><span>Nova palavra-passe</span><input id="pw-n" type="password" minlength="12" required></label></div><div class="field"><label><span>Confirmar</span><input id="pw-r" type="password" minlength="12" required></label></div><button class="secondary">Alterar palavra-passe</button></form></div><div class="setting-card"><h3>Infraestrutura</h3><div class="list"><div class="list-row"><span>Cloudflare Worker</span><span class="badge published">Ligado</span></div><div class="list-row"><span>D1 · primary</span><span class="badge published">Associado</span></div><div class="list-row"><span>ImageKit</span><span id="ik" class="badge">A verificar…</span></div><div class="list-row"><span>Tradução automática</span><span id="tr" class="badge">A verificar…</span></div></div></div></div>';$("#s-save").onclick=async()=>{try{await api("/api/settings",{method:"PUT",body:JSON.stringify({site_name:$("#s-name").value,site_description:$("#s-desc").value,default_language:$("#s-lang").value,timezone:$("#s-tz").value})});toast("Guardado.")}catch(x){toast(x.message,"error")}};$("#pw").onsubmit=async e=>{e.preventDefault();if($("#pw-n").value!==$("#pw-r").value)return toast("As palavras-passe não coincidem.","error");try{await api("/api/auth/password",{method:"POST",body:JSON.stringify({current_password:$("#pw-c").value,new_password:$("#pw-n").value})});toast("Palavra-passe alterada.");e.target.reset()}catch(x){toast(x.message,"error")}};try{const h=await api("/api/health");$("#ik").textContent=h.imagekit?"Ligado":"Não configurado";$("#ik").className="badge "+(h.imagekit?"published":"archived");$("#tr").textContent=h.translation?"Ligada":"Ative o Cloudflare Workers AI";$("#tr").className="badge "+(h.translation?"published":"archived")}catch{}}
async function activity(){const d=await api("/api/activity");$("#view-activity").innerHTML='<div class="view-header"><div><div class="eyebrow">Registo de auditoria</div><h1>Atividade</h1><p>Ações importantes do administrador.</p></div></div><div class="panel">'+(d.activity||[]).map(x=>'<div class="activity-item"><div class="activity-time">'+date(x.created_at)+'</div><div><div class="activity-action">'+esc(x.action)+'</div><div class="row-meta">'+esc(x.email||"Sistema")+'</div></div><div class="activity-entity">'+esc(x.entity_type||"")+'</div></div>').join("")+'</div>';}
(async()=>{try{state.user=(await api("/api/auth/me")).user;enterApp()}catch{enterLogin()}})();
