(() => {
  "use strict";
  const grid=document.querySelector("[data-category-grid]"),search=document.querySelector("[data-tool-search]"),countEl=document.querySelector("[data-tool-count]"),liveSection=document.querySelector("[data-tool-live-results]"),resultsGrid=document.querySelector("[data-tool-results]"),resultCount=document.querySelector("[data-tool-result-count]");
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
  const norm=v=>String(v??"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"");
  const iconSvg=id=>({produtividade:"◷",texto:"Aa",imagem:"▧",tecnologia:"⌘"}[id]||"✦");
  let categories=[],tools=[],isPro=false;
  const toolCard=t=>{const locked=t.access==="premium"&&!isPro;return '<a class="tool-card cat-'+esc(t.category||"geral")+(locked?" tool-card-locked":"")+' nx-spotlight nx-reveal" data-tool-id="'+esc(t.id)+'" href="'+esc(locked?"/account/upgrade/":t.path)+'" aria-label="'+esc(t.name+(locked?" — requer Pro":""))+'"><div class="tool-card-top"><span class="tool-card-icon">'+iconSvg(t.category)+'</span><span class="tool-arrow">→</span></div><div class="tool-card-badges">'+(t.featured?'<span class="tool-card-badge featured">Destaque</span>':"")+(t.popular?'<span class="tool-card-badge popular">Popular</span>':"")+(t.access==="premium"?'<span class="tool-card-badge pro">PRO</span>':"")+'</div><h2>'+esc(t.name)+'</h2><p>'+esc(t.description||"")+'</p><small>'+esc((t.tags||[]).slice(0,4).join(" · "))+'</small>'+(locked?'<span class="tool-lock" aria-hidden="true">🔒</span>':"")+'</a>'};
  const categoryCard=c=>'<a class="tool-card category-card cat-'+esc(c.id)+' nx-spotlight nx-reveal" href="'+esc(c.path||("/tool/categories/"+c.id+"/"))+'"><div class="tool-card-top"><span class="tool-card-icon">'+iconSvg(c.id)+'</span><span class="tool-arrow">→</span></div><h2>'+esc(c.name)+'</h2><p>'+esc(c.description||"")+'</p><small>'+Number(c.count||0)+' ferramenta(s)</small></a>';
  async function getProAccess(){try{const mod=await import("/account/account-client.js?v=20260923-tool-access");if(!mod.auth?.currentUser)return false;const d=await mod.workerFetch("/api/account/billing",{method:"GET"});return String(d?.billing?.plan||"").toLowerCase()==="pro"&&["ACTIVE","APPROVED"].includes(String(d?.billing?.status||"").toUpperCase())}catch{return false}}
  function renderCategories(){if(!grid)return;grid.innerHTML=categories.length?categories.map(categoryCard).join(""):"<div class=\"tool-empty\">Nenhuma categoria encontrada.</div>";window.NexaurenUI?.refresh?.()}
  function renderResults(list){if(!liveSection||!resultsGrid)return;liveSection.hidden=!list.length;if(resultCount)resultCount.textContent=list.length+(list.length===1?" ferramenta encontrada":" ferramentas encontradas");resultsGrid.innerHTML=list.slice(0,24).map(toolCard).join("");window.NexaurenUI?.refresh?.()}
  function applySearch(raw){const q=norm(raw).trim();if(q)localStorage.setItem("nexauren-tool-search",String(raw).slice(0,100));else localStorage.removeItem("nexauren-tool-search");if(!q){renderCategories();renderResults([]);return}renderCategoriesFiltered(categories.filter(c=>norm(c.name+" "+(c.description||"")).includes(q)));renderResults(tools.filter(t=>norm([t.name,t.description,(t.tags||[]).join(" "),t.category].join(" ")).includes(q)))}
  function renderCategoriesFiltered(list){if(!grid)return;grid.innerHTML=list.length?list.map(categoryCard).join(""):"<div class=\"tool-empty\">Nenhuma categoria encontrada.</div>";window.NexaurenUI?.refresh?.()}
  async function load(){try{const registry=await window.NexaurenToolRegistry.loadRegistry();tools=registry.tools.filter(t=>t.status==="active");categories=registry.categories.map(c=>({...c,count:tools.filter(t=>t.category===c.id).length}));if(countEl)countEl.textContent=tools.length;isPro=await getProAccess();const stored=localStorage.getItem("nexauren-tool-search")||"";if(search&&stored){search.value=stored;applySearch(stored)}else renderCategories();window.NexaurenUI?.refresh?.()}catch(e){if(grid)grid.innerHTML='<div class="tool-empty">'+esc(e.message||"Não foi possível carregar o catálogo.")+'</div>'}}
  search?.addEventListener("input",()=>applySearch(search.value));
  window.addEventListener("nexauren:tool-registry-updated",()=>load());
  load();
})();
