const input=document.querySelector('#input'),gutter=document.querySelector('#gutter'),counter=document.querySelector('#counter'),validateButton=document.querySelector('#validate'),sampleButton=document.querySelector('#sample'),clearButton=document.querySelector('#clear'),diagnostic=document.querySelector('#diagnostic'),details=document.querySelector('#details'),stateLabel=document.querySelector('#state-label'),statusIcon=document.querySelector('#status-icon'),statusTitle=document.querySelector('#status-title'),statusTime=document.querySelector('#status-time'),errorCard=document.querySelector('#error-card'),errorMessage=document.querySelector('#error-message'),errorLine=document.querySelector('#error-line'),errorColumn=document.querySelector('#error-column'),errorPosition=document.querySelector('#error-position'),context=document.querySelector('#context'),objects=document.querySelector('#objects'),arrays=document.querySelector('#arrays'),keys=document.querySelector('#keys'),values=document.querySelector('#values'),copyButton=document.querySelector('#copy'),formatButton=document.querySelector('#format');
const SAMPLE='{"name":"Nexauren","category":"Tecnologia","active":true,"tools":["QR Code","UUID","Base64"]}';
function updateEditor(){const v=input.value;const lines=v? v.split(/\n/).length:1;counter.textContent=lines+' linha'+(lines===1?'':'s')+' · '+v.length+' caracteres';gutter.textContent=Array.from({length:lines},(_,i)=>i+1).join('\n')}
function positionFromError(message,source){const m=String(message).match(/position\s+(\d+)/i);if(m)return Number(m[1]);const m2=String(message).match(/at\s+position\s+(\d+)/i);if(m2)return Number(m2[1]);return Math.max(0,source.length-1)}
function loc(source,pos){const safe=Math.max(0,Math.min(pos,source.length));const before=source.slice(0,safe);const line=before.split('\n').length;const last=before.lastIndexOf('\n');const column=safe-(last+1)+1;return {line,column,pos:safe}}
function makeContext(source,pos){const start=Math.max(0,pos-48),end=Math.min(source.length,pos+48);const left=source.slice(start,pos).replace(/\n/g,'↵');const right=source.slice(pos,end).replace(/\n/g,'↵');return start>0?'…'+left+'▌'+right:(left+'▌'+right)}
function walk(value,stats){if(Array.isArray(value)){stats.arrays++;stats.values+=value.length;value.forEach(v=>walk(v,stats));return}if(value&&typeof value==='object'){stats.objects++;for(const [k,v] of Object.entries(value)){stats.keys++;stats.values++;walk(v,stats)}}}
function finishValid(parsed,started){const stats={objects:0,arrays:0,keys:0,values:0};walk(parsed,stats);objects.textContent=stats.objects;arrays.textContent=stats.arrays;keys.textContent=stats.keys;values.textContent=stats.values;errorCard.hidden=true;details.hidden=false;diagnostic.className='diagnostic ok';diagnostic.querySelector('h2').textContent='JSON válido';diagnostic.querySelector('p').textContent='A estrutura foi reconhecida sem erros de sintaxe.';stateLabel.textContent='Válido';statusIcon.textContent='✓';statusTitle.textContent='JSON válido';statusTime.textContent=Math.round(performance.now()-started)+' ms'}
function finishError(err,started){details.hidden=false;errorCard.hidden=false;diagnostic.className='diagnostic error';diagnostic.querySelector('h2').textContent='JSON inválido';diagnostic.querySelector('p').textContent='Foi encontrado um problema de sintaxe.';stateLabel.textContent='Erro';statusIcon.textContent='!';statusIcon.style.background='#4a1426';statusIcon.style.color='#ff8fa5';statusTitle.textContent='JSON inválido';statusTime.textContent=Math.round(performance.now()-started)+' ms';const pos=positionFromError(err.message,input.value);const p=loc(input.value,pos);errorMessage.textContent=err.message;errorLine.textContent='Linha '+p.line;errorColumn.textContent='Coluna '+p.column;errorPosition.textContent='Posição '+p.pos;context.textContent=makeContext(input.value,p.pos);objects.textContent='—';arrays.textContent='—';keys.textContent='—';values.textContent='—'}
function validate(){const started=performance.now();try{if(!input.value.trim()){throw new Error('Introduza um JSON para validar.')}const parsed=JSON.parse(input.value);statusIcon.style.background='';statusIcon.style.color='';finishValid(parsed,started)}catch(err){finishError(err,started)}}
input.addEventListener('input',updateEditor);input.addEventListener('scroll',()=>{gutter.scrollTop=input.scrollTop});validateButton.addEventListener('click',validate);sampleButton.addEventListener('click',()=>{input.value=JSON.stringify(JSON.parse(SAMPLE),null,2);updateEditor();validate()});clearButton.addEventListener('click',()=>{input.value='';updateEditor();details.hidden=true;diagnostic.className='diagnostic idle';diagnostic.querySelector('h2').textContent='Pronto para analisar';diagnostic.querySelector('p').textContent='O resultado da validação aparecerá aqui.';stateLabel.textContent='Aguardando validação'});copyButton.addEventListener('click',async()=>{if(!input.value)return;try{await navigator.clipboard.writeText(input.value);copyButton.textContent='Copiado ✓';setTimeout(()=>copyButton.textContent='Copiar JSON',1400)}catch{copyButton.textContent='Copie manualmente'}});formatButton.addEventListener('click',()=>{location.href='/tool/categories/tecnologia/formatador-json/'});updateEditor();