const $=s=>document.querySelector(s);
const pattern=$("#pattern"),flags=$("#flags"),text=$("#test-text"),results=$("#results"),validity=$("#validity"),matchCount=$("#match-count"),textCount=$("#text-count"),replacement=$("#replacement"),preview=$("#preview");
let lastRegex=null,lastSource="";
function safeFlags(){return[...new Set(flags.value.replace(/[^dgimsuvy]/g,"").split(""))].join("")}
function build(){const f=safeFlags();flags.value=f;try{lastRegex=new RegExp(pattern.value,f);validity.textContent="Regex válida";validity.style.color="var(--ok)";return lastRegex}catch(e){lastRegex=null;validity.textContent="Regex inválida";validity.style.color="var(--accent2)";return null}}
function esc(s){return s.replace(/[\\^$.*+?()[\]{}|]/g,"\\function esc(s){return s.split("").map(c=>"\\^$.*+?()[]{}|".includes(c)?"\\\\":c).join("")}")}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function updatePreview(re=lastRegex){if(!re){preview.textContent="Corrija a expressão para visualizar a substituição.";return}try{preview.textContent=lastSource.replace(re,replacement.value)}catch(e){preview.textContent=e.message}}
function renderMatches(){const re=build();lastSource=text.value;textCount.textContent=text.value.length+" caracteres";if(!re){results.className="results empty";results.textContent="A expressão regular contém um erro.";matchCount.textContent="0 encontradas";return}const list=[];try{if(re.global||re.sticky){for(const m of text.value.matchAll(re))list.push(m)}else{const m=re.exec(text.value);if(m)list.push(m)}}catch(e){results.className="results empty";results.textContent=e.message;return}matchCount.textContent=list.length+" encontrada"+(list.length===1?"":"s");if(!list.length){results.className="results empty";results.textContent="Nenhuma correspondência encontrada.";updatePreview(re);return}results.className="results";results.innerHTML=list.map((m,i)=>{const groups=m.groups?Object.entries(m.groups).map(([k,v])=>k+" = "+(v??"∅")).join(" · "):m.slice(1).map((v,n)=>"$"+(n+1)+" = "+(v??"∅")).join(" · ");return '<article class="match"><div class="match-top"><span>MATCH '+(i+1)+'</span><span>posição '+m.index+'</span></div><div class="match-value">'+escapeHtml(m[0])+'</div>'+(groups?'<div class="groups">'+escapeHtml(groups)+'</div>':"")+"</article>"}).join("");updatePreview(re)}
$("#test").addEventListener("click",renderMatches);pattern.addEventListener("input",build);flags.addEventListener("input",build);text.addEventListener("input",()=>{textCount.textContent=text.value.length+" caracteres";if(lastRegex)renderMatches()});replacement.addEventListener("input",()=>updatePreview());document.querySelectorAll("[data-flag]").forEach(b=>b.addEventListener("click",()=>{if(!flags.value.includes(b.dataset.flag))flags.value+=b.dataset.flag;renderMatches()}));
$("#sample").addEventListener("click",()=>{pattern.value="\\b[A-Z][a-z]+\\b";flags.value="g";text.value="Olá Nexauren. Tecnologia e produtividade para criar ferramentas melhores.";renderMatches()});
$("#escape").addEventListener("click",()=>{pattern.value=esc(text.value);flags.value="g";renderMatches()});
$("#clear").addEventListener("click",()=>{pattern.value="";text.value="";replacement.value="";results.className="results empty";results.textContent="Execute um teste para ver os resultados.";preview.textContent="A pré-visualização aparecerá aqui.";matchCount.textContent="0 encontradas";textCount.textContent="0 caracteres";validity.textContent="Aguardando";lastRegex=null});
$("#copy-preview").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(preview.textContent);$("#copy-preview").textContent="Copiado ✓";setTimeout(()=>$("#copy-preview").textContent="Copiar resultado",1200)}catch{}});
build();textCount.textContent=text.value.length+" caracteres";