const $=s=>document.querySelector(s);
const e={file:$("#file"),cameraFile:$("#cameraFile"),choose:$("#choose"),camera:$("#camera"),drop:$("#drop"),sourceCanvas:$("#sourceCanvas"),previewCanvas:$("#previewCanvas"),outputCanvas:$("#outputCanvas"),preset:$("#preset"),w:$("#w"),h:$("#h"),fit:$("#fit"),position:$("#position"),background:$("#background"),format:$("#format"),quality:$("#quality"),qualityOut:$("#qualityOut"),qualityOut2:$("#qualityOut2"),text:$("#text"),textColor:$("#textColor"),textPosition:$("#textPosition"),textSize:$("#textSize"),textSizeOut:$("#textSizeOut"),textSizeOut2:$("#textSizeOut2"),safe:$("#safe"),safeOverlay:$("#safeOverlay"),run:$("#run"),download:$("#download"),copy:$("#copy"),reset:$("#reset"),status:$("#status"),spinner:$("#spinner"),sourceStat:$("#sourceStat"),presetStat:$("#presetStat"),fitStat:$("#fitStat"),formatStat:$("#formatStat"),resultSection:$("#resultSection"),dims:$("#dims"),size:$("#size"),ratio:$("#ratio"),formatResult:$("#formatResult")};
let image=null,sourceUrl="",resultBlob=null,processing=false,previewTimer=0;
const revoke=u=>{if(u)try{URL.revokeObjectURL(u)}catch{}};const bytes=n=>{if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]};const status=(t,error=false)=>{e.status.textContent=t;e.status.className="status"+(error?" error":"")};
function dims(){return[Math.max(320,Math.min(10000,Number(e.w.value)||1080)),Math.max(320,Math.min(10000,Number(e.h.value)||1080))]}
function sourceDims(){return image?[image.width||image.naturalWidth||0,image.height||image.naturalHeight||0]:[0,0]}
function updateStats(){const [w,h]=dims();e.presetStat.textContent=w+" × "+h;e.fitStat.textContent=e.fit.value==="cover"?"Cover":"Contain";e.formatStat.textContent=e.format.value==="image/jpeg"?"JPG":e.format.value.split("/").pop().toUpperCase();e.qualityOut.textContent=e.format.value==="image/png"?"Lossless":e.quality.value+"%";e.qualityOut2.textContent=e.format.value==="image/png"?"Lossless":e.quality.value+"%";e.textSizeOut.textContent=e.textSize.value+"%";e.textSizeOut2.textContent=e.textSize.value+"%";e.sourceStat.textContent=image?sourceDims().join(" × "):"No image";e.safeOverlay.hidden=!e.safe.checked;drawLive()}
function canvasFor(w,h){const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:true});if(!ctx)throw new Error("The browser could not start image processing.");return[c,ctx]}
function fitRect(sw,sh,W,H){
 const scale=e.fit.value==="cover"?Math.max(W/sw,H/sh):Math.min(W/sw,H/sh);const dw=sw*scale,dh=sh*scale;
 let x=(W-dw)/2,y=(H-dh)/2;const p=e.position.value;if(p==="top")y=0;if(p==="bottom")y=H-dh;if(p==="left")x=0;if(p==="right")x=W-dw;return{x,y,dw,dh}
}
function drawText(ctx,W,H){
 const t=e.text.value.trim();if(!t)return;const fs=Math.max(16,Math.round(Math.min(W,H)*Number(e.textSize.value)/100)),m=Math.max(18,Math.round(Math.min(W,H)*.045));ctx.save();ctx.font="800 "+fs+"px system-ui,-apple-system,sans-serif";ctx.textBaseline="middle";ctx.fillStyle=e.textColor.value;ctx.strokeStyle="rgba(0,0,0,.55)";ctx.lineWidth=Math.max(2,fs*.08);const pos=e.textPosition.value,center=pos.endsWith("c")||pos==="c";let x=m,y=m+fs/2;if(center)x=W/2;if(pos.endsWith("r")){x=W-m;ctx.textAlign="right"}else if(center){ctx.textAlign="center"}else{ctx.textAlign="left"}if(pos.startsWith("b"))y=H-m-fs/2;if(pos==="c")y=H/2;ctx.strokeText(t,x,y);ctx.fillText(t,x,y);ctx.restore()}
function render(w,h,targetCanvas){
 const [c,ctx]=canvasFor(w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.fillStyle=e.background.value;ctx.fillRect(0,0,w,h);if(!image)return c;
 const [sw,sh]=sourceDims(),r=fitRect(sw,sh,w,h);ctx.drawImage(image,r.x,r.y,r.dw,r.dh);drawText(ctx,w,h);return c
}
function drawLive(){
 clearTimeout(previewTimer);if(!image){e.sourceCanvas.width=e.sourceCanvas.height=1;return}
 previewTimer=setTimeout(()=>{try{
   const [sw,sh]=sourceDims();const sourceScale=Math.min(1,900/Math.max(sw,sh));const [sc,sctx]=canvasFor(Math.max(1,Math.round(sw*sourceScale)),Math.max(1,Math.round(sh*sourceScale)));sctx.drawImage(image,0,0,sc.width,sc.height);e.sourceCanvas.width=sc.width;e.sourceCanvas.height=sc.height;e.sourceCanvas.getContext("2d").drawImage(sc,0,0);
   const [W,H]=dims();const scale=Math.min(1,900/Math.max(W,H));const preview=render(Math.max(1,Math.round(W*scale)),Math.max(1,Math.round(H*scale)));e.previewCanvas.width=preview.width;e.previewCanvas.height=preview.height;e.previewCanvas.getContext("2d").drawImage(preview,0,0);e.run.disabled=false
 }catch(err){status(err?.message||"Could not prepare the preview.",true)}},50)
}
async function loadFile(file){try{if(!file||(!file.type.startsWith("image/")&&!/\.(jpe?g|png|webp|avif|gif|bmp|heic|heif|tiff?)$/i.test(file.name)))throw new Error("Please choose a supported image file.");revoke(sourceUrl);sourceUrl=URL.createObjectURL(file);image=await NexaurenImage.loadImage(file);resultBlob=null;e.resultSection.classList.add("hidden");e.download.disabled=true;e.copy.disabled=true;status("Image ready. Adjust the canvas and review the live preview.");updateStats()}catch(err){image=null;status(err?.message||"Could not load this image.",true)}}
function applyPreset(value){if(value==="custom"){e.preset.value="custom";updateStats();return}const [w,h]=value.split("x").map(Number);e.w.value=w;e.h.value=h;e.preset.value=value;updateStats();status("Preset applied: "+w+" × "+h+".")}
function generate(){
 if(processing||!image){status("Choose an image first.",true);return}
 processing=true;e.spinner.classList.add("on");e.spinner.setAttribute("aria-hidden","false");e.run.disabled=true;status("Generating full-resolution image…");
 try{const [W,H]=dims();if(W*H>25000000)throw new Error("The selected canvas is too large for this device. Use smaller dimensions.");const canvas=render(W,H);canvas.toBlob(blob=>{if(!blob)throw new Error("The browser could not export the selected output format.");resultBlob=blob;e.outputCanvas.width=W;e.outputCanvas.height=H;e.outputCanvas.getContext("2d").drawImage(canvas,0,0);e.dims.textContent=W+" × "+H;e.size.textContent=bytes(blob.size);e.ratio.textContent=(W/H).toFixed(2)+":1";e.formatResult.textContent=e.format.value==="image/jpeg"?"JPG":e.format.value.split("/").pop().toUpperCase();e.resultSection.classList.remove("hidden");e.download.disabled=false;e.copy.disabled=false;status("Social image generated successfully.");e.resultSection.scrollIntoView({behavior:"smooth",block:"start"});processing=false;e.spinner.classList.remove("on");e.spinner.setAttribute("aria-hidden","true");e.run.disabled=false},e.format.value,e.format.value==="image/png"?undefined:Number(e.quality.value)/100)}catch(err){processing=false;e.spinner.classList.remove("on");e.spinner.setAttribute("aria-hidden","true");e.run.disabled=!image;status(err?.message||"Could not generate the image.",true)}}
function download(){if(!resultBlob){status("Generate the image first.",true);return}NexaurenImage.download(resultBlob,"nexauren-social-"+e.w.value+"x"+e.h.value+"."+NexaurenImage.ext(resultBlob.type));status("Image sent to download.")}
async function copySummary(){if(!resultBlob){status("Generate the image first.",true);return}const t=["NEXAUREN SOCIAL IMAGE RESIZER","Dimensions: "+e.dims.textContent,"Format: "+e.formatResult.textContent,"Size: "+e.size.textContent,"Fit: "+e.fit.value,"Preset: "+e.preset.options[e.preset.selectedIndex].text].join("\n");try{await navigator.clipboard.writeText(t);status("Summary copied.")}catch{status("Could not copy the summary.",true)}}
function reset(){revoke(sourceUrl);sourceUrl="";image=null;resultBlob=null;e.file.value="";e.cameraFile.value="";e.sourceCanvas.width=e.sourceCanvas.height=e.previewCanvas.width=e.previewCanvas.height=e.outputCanvas.width=e.outputCanvas.height=1;e.resultSection.classList.add("hidden");e.run.disabled=true;e.download.disabled=true;e.copy.disabled=true;e.w.value="1080";e.h.value="1080";e.preset.value="1080x1080";e.fit.value="cover";e.position.value="center";e.background.value="#ffffff";e.format.value="image/webp";e.quality.value="90";e.text.value="";e.textColor.value="#ffffff";e.textPosition.value="tl";e.textSize.value="6";e.safe.checked=true;updateStats();status("Choose an image to start.")}
e.choose.onclick=()=>e.file.click();e.camera.onclick=()=>e.cameraFile.click();e.file.onchange=ev=>{void loadFile(ev.target.files[0]);ev.target.value=""};e.cameraFile.onchange=ev=>{void loadFile(ev.target.files[0]);ev.target.value=""};
["dragenter","dragover"].forEach(t=>e.drop.addEventListener(t,ev=>{ev.preventDefault();e.drop.style.borderColor="var(--cyan)"}));["dragleave","drop"].forEach(t=>e.drop.addEventListener(t,ev=>{ev.preventDefault();e.drop.style.borderColor="#42536f"}));e.drop.ondrop=ev=>loadFile(ev.dataTransfer.files[0]);e.drop.onkeydown=ev=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();e.file.click()}};
e.preset.onchange=()=>applyPreset(e.preset.value);document.querySelectorAll(".preset[data-preset]").forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
[e.w,e.h,e.fit,e.position,e.background,e.format,e.quality,e.text,e.textColor,e.textPosition,e.textSize,e.safe].forEach(x=>x.addEventListener("input",()=>{if(x!==e.preset)e.preset.value="custom";updateStats()}));[e.w,e.h,e.fit,e.position,e.background,e.format,e.quality,e.text,e.textColor,e.textPosition,e.textSize,e.safe].forEach(x=>x.addEventListener("change",()=>{if(x!==e.preset&&x!==e.preset)e.preset.value="custom";updateStats()}));
e.run.onclick=generate;e.download.onclick=download;e.copy.onclick=copySummary;e.reset.onclick=reset;document.addEventListener("keydown",ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key==="Enter"){ev.preventDefault();if(image)generate()}});updateStats();