import {auth,onAuthStateChanged,getPlanState} from "/tool/frontend/tool-access.js?v=20260923-access-2";
const PDFJS="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs";
const pdfjsLib=await import(PDFJS);
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";
// Nexauren PDF → JPG v1.0.0
(()=>{"use strict";
const language=(()=>{const q=new URLSearchParams(location.search).get("lang");if(q==="en")return"en";try{return localStorage.getItem("ns_lang")==="en"?"en":"pt"}catch{return"pt"}})();
const ui=language==="en"?{back:"← PDF",translate:"Português",lead:"Convert PDF pages into JPG images, choose the pages, resolution, and quality. Everything is processed directly in your browser.",drop:"Choose a PDF",dropSub:"or tap to select a PDF file",pages:"Pages",all:"All pages",first:"First page",range:"Custom range",rangeLabel:"Range",scale:"Resolution",quality:"JPG quality",base:"Base name",create:"Create JPG",clear:"Clear",ready:"Ready.",none:"No result yet.",summary:"Summary",count:"Pages",size:"PDF",resolution:"Resolution",qualityStat:"Quality",privacy:"Privacy",privacyBody:"The PDF is processed locally in your browser. The file does not need to be uploaded to a server.",limit:"Free: up to 20 pages per conversion.",account:"Sign in to use this tool",accountBody:"Nexauren tools are available to authenticated users.",signIn:"Sign in or create an account",load:"Loading PDF…",processing:"Rendering page",done:"JPGs created successfully.",error:"Could not convert this PDF.",download:"Download JPG"}:{back:"← PDF",translate:"English",lead:"Converta páginas de um PDF em imagens JPG, escolha as páginas, a resolução e a qualidade. Tudo processado diretamente no navegador.",drop:"Escolha um PDF",dropSub:"ou toque para selecionar um ficheiro PDF",pages:"Páginas",all:"Todas",first:"Primeira página",range:"Intervalo personalizado",rangeLabel:"Intervalo",scale:"Resolução",quality:"Qualidade JPG",base:"Nome base",create:"Criar JPG",clear:"Limpar",ready:"Pronto.",none:"Nenhum resultado ainda.",summary:"Resumo",count:"Páginas",size:"PDF",resolution:"Resolução",qualityStat:"Qualidade",privacy:"Privacidade",privacyBody:"O PDF é processado localmente no seu navegador. O ficheiro não precisa de ser enviado para um servidor.",limit:"Free: até 20 páginas por conversão.",account:"Entre para usar esta ferramenta",accountBody:"As ferramentas Nexauren estão disponíveis para utilizadores autenticados.",signIn:"Entrar ou criar conta",load:"A carregar PDF…",processing:"A renderizar página",done:"JPGs criados com sucesso.",error:"Não foi possível converter este PDF.",download:"Baixar JPG"};
const $=s=>document.querySelector(s),files=$("#pdftojpg-file"),drop=$("#pdftojpg-drop"),app=$("#pdftojpg-app"),gate=$("#pdftojpg-gate"),convert=$("#pdftojpg-convert"),clear=$("#pdftojpg-clear"),status=$("#pdftojpg-status"),results=$("#pdftojpg-results"),empty=$("#pdftojpg-empty"),fileInfo=$("#pdftojpg-file-info"),fileName=$("#pdftojpg-file-name"),fileSize=$("#pdftojpg-file-size"),pages=$("#pdftojpg-pages"),range=$("#pdftojpg-range"),scale=$("#pdftojpg-scale"),scaleOut=$("#pdftojpg-scale-out"),quality=$("#pdftojpg-quality"),qualityOut=$("#pdftojpg-quality-out"),qualityStat=$("#pdftojpg-quality-stat"),count=$("#pdftojpg-count"),sizeStat=$("#pdftojpg-size"),resolution=$("#pdftojpg-resolution"),nameInput=$("#pdftojpg-name"),progress=$("#pdftojpg-progress"),planName=$("#pdftojpg-plan-name"),planLimit=$("#pdftojpg-plan-limit"),langBtn=$("#pdftojpg-lang");
let state={file:null,pro:false,ready:false,pdf:null,outputs:[],urls:[]};
function set(s,v){const e=$(s);if(e)e.textContent=v}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"": "&quot;","'":"&#39;"}[m]))}
function msg(v,error=false){status.textContent=v;status.style.color=error?"var(--danger)":"var(--muted)"}
function applyLanguage(){document.documentElement.lang=language;set("#pdftojpg-back",ui.back);set("#pdftojpg-lang",ui.translate);set("#pdftojpg-lead",ui.lead);set("#pdftojpg-drop-title",ui.drop);set("#pdftojpg-drop-sub",ui.dropSub);set("#pdftojpg-pages-label",ui.pages);set("#pdftojpg-pages-all",ui.all);set("#pdftojpg-pages-first",ui.first);set("#pdftojpg-pages-range",ui.range);set("#pdftojpg-range-label",ui.rangeLabel);set("#pdftojpg-scale-label",ui.scale);set("#pdftojpg-quality-label",ui.quality);set("#pdftojpg-name-label",ui.base);set("#pdftojpg-convert",ui.create);set("#pdftojpg-clear",ui.clear);set("#pdftojpg-status",ui.ready);set("#pdftojpg-empty",ui.none);set("#pdftojpg-summary-title",ui.summary);set("#pdftojpg-count-label",ui.count);set("#pdftojpg-size-label",ui.size);set("#pdftojpg-resolution-label",ui.resolution);set("#pdftojpg-quality-stat-label",ui.qualityStat);set("#pdftojpg-privacy-title",ui.privacy);set("#pdftojpg-privacy-body",ui.privacyBody);set("#pdftojpg-limit-hint",ui.limit);updateLabels()}
function updateLabels(){scaleOut.textContent=scale.value+"×";qualityOut.textContent=quality.value+"%";qualityStat.textContent=quality.value+"%";resolution.textContent=scale.value+"×"}
function setGate(){gate.hidden=false;gate.classList.remove("pdftojpg-hide");gate.innerHTML='<div style="text-align:center"><h2>'+esc(ui.account)+'</h2><p>'+esc(ui.accountBody)+'</p><a class="pdftojpg-btn primary" href="/account">'+esc(ui.signIn)+'</a></div>';app.classList.add("pdftojpg-hide")}
function openApp(){gate.hidden=true;gate.classList.add("pdftojpg-hide");app.classList.remove("pdftojpg-hide")}
function planUi(){planName.textContent=state.pro?"NEXAUREN PRO":"NEXAUREN FREE";planLimit.textContent=state.pro?(language==="en"?"Pro: up to 100 pages per conversion.":"Pro: até 100 páginas por conversão."):(language==="en"?"Free: up to 20 pages per conversion.":"Free: até 20 páginas por conversão.")}
function bytes(n){if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]}
function cleanUrls(){state.urls.forEach(URL.revokeObjectURL);state.urls=[]}
function parseRange(text,max){const out=new Set();for(const raw of String(text||"").split(",")){const s=raw.trim();if(!s)continue;const m=s.match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)throw Error(language==="en"?"Invalid page range.":"Intervalo de páginas inválido.");const a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<1||a>max||b>max||a>b)throw Error(language==="en"?"Page range is outside the PDF.":"O intervalo está fora das páginas do PDF.");for(let i=a;i<=b;i++)out.add(i)}return [...out].sort((a,b)=>a-b)}
function selectedPages(total){if(pages.value==="first")return[1];if(pages.value==="range")return parseRange(range.value,total);const limit=state.pro?100:20;if(total>limit)throw Error(language==="en"?`This plan allows up to ${limit} pages per conversion. Choose an interval.`:`Este plano permite até ${limit} páginas por conversão. Escolha um intervalo.`);return Array.from({length:total},(_,i)=>i+1)}
function resetResults(){cleanUrls();state.outputs=[];results.replaceChildren();results.append(empty.cloneNode(true))}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function renderResults(){cleanUrls();results.replaceChildren();if(!state.outputs.length){const d=document.createElement("div");d.className="pdftojpg-empty";d.textContent=ui.none;results.append(d);return}state.outputs.forEach(r=>{const row=document.createElement("div");row.className="pdftojpg-result";const im=document.createElement("img");im.className="pdftojpg-preview";im.src=URL.createObjectURL(r.blob);state.urls.push(im.src);const info=document.createElement("div");info.className="pdftojpg-result-info";const b=document.createElement("b"),s=document.createElement("small");b.textContent=r.name;s.textContent=`Página ${r.page} · ${r.width}×${r.height} · ${bytes(r.blob.size)}`;info.append(b,s);const bt=document.createElement("button");bt.className="pdftojpg-btn primary";bt.type="button";bt.textContent=ui.download;bt.onclick=()=>download(r.blob,r.name);row.append(im,info,bt);results.append(row)})}
function loadFile(f){if(!f||(!/application\/pdf/i.test(f.type)&&!/\.pdf$/i.test(f.name)))throw Error(language==="en"?"Select a valid PDF file.":"Selecione um ficheiro PDF válido.");state.file=f;state.outputs=[];cleanUrls();fileInfo.hidden=false;fileName.textContent=f.name;fileSize.textContent=bytes(f.size);sizeStat.textContent=bytes(f.size);renderResults();convert.disabled=!state.ready;msg(ui.ready)}
async function openPdf(){if(!state.file)throw Error(language==="en"?"Select a PDF first.":"Selecione um PDF primeiro.");msg(ui.load);const buf=await state.file.arrayBuffer();state.pdf=await pdfjsLib.getDocument({data:buf}).promise;return state.pdf}
async function run(){if(!state.ready)return msg(language==="en"?"Access is not ready yet.":"O acesso ainda não está pronto.",true);if(!state.file)return msg(language==="en"?"Select a PDF first.":"Selecione um PDF primeiro.",true);convert.disabled=true;clear.disabled=true;progress.style.width="0%";try{const pdf=state.pdf||await openPdf();const list=selectedPages(pdf.numPages);state.outputs=[];renderResults();for(let i=0;i<list.length;i++){const n=list[i],page=await pdf.getPage(n),vp=page.getViewport({scale:+scale.value});const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d",{alpha:false});if(!ctx)throw Error(language==="en"?"Canvas is unavailable.":"O navegador não conseguiu iniciar o processamento.");if(vp.width*vp.height>32000000)throw Error(language==="en"?"Resolution is too high for this device.":"A resolução escolhida é alta demais para este dispositivo.");canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:vp}).promise;const blob=await new Promise((ok,no)=>canvas.toBlob(b=>b?ok(b):no(Error(language==="en"?"Could not encode JPG.":"Não foi possível gerar o JPG.")),"image/jpeg",+quality.value/100));const base=String(nameInput.value||"pdf-to-jpg").replace(/[^a-z0-9_-]+/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"pdf-to-jpg";state.outputs.push({blob,name:`${base}-page-${String(n).padStart(3,"0")}.jpg`,page:n,width:canvas.width,height:canvas.height});renderResults();progress.style.width=Math.round((i+1)/list.length*100)+"%";msg(`${ui.processing} ${i+1}/${list.length}…`);await new Promise(requestAnimationFrame)}count.textContent=String(state.outputs.length);msg(ui.done)}catch(e){msg(e?.message||ui.error,true)}finally{convert.disabled=!state.ready;clear.disabled=false}}
files.addEventListener("change",e=>{try{loadFile(e.target.files?.[0])}catch(x){msg(x?.message||ui.error,true)}files.value=""});
drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("drag")});drop.addEventListener("dragleave",()=>drop.classList.remove("drag"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("drag");try{loadFile(e.dataTransfer.files?.[0])}catch(x){msg(x?.message||ui.error,true)}});
pages.addEventListener("change",()=>{range.disabled=pages.value!=="range"});scale.addEventListener("input",updateLabels);quality.addEventListener("input",updateLabels);
clear.addEventListener("click",()=>{state.file=null;state.pdf=null;state.outputs=[];cleanUrls();fileInfo.hidden=true;count.textContent="0";sizeStat.textContent="—";renderResults();msg(ui.none);progress.style.width="0%";convert.disabled=!state.ready});
convert.addEventListener("click",run);window.addEventListener("beforeunload",cleanUrls);
langBtn.addEventListener("click",()=>{try{localStorage.setItem("ns_lang",language==="en"?"pt":"en")}catch{}const u=new URL(location.href);if(language==="en")u.searchParams.delete("lang");else u.searchParams.set("lang","en");location.href=u.pathname+u.search});
applyLanguage();planUi();
onAuthStateChanged(auth,async user=>{if(!user){state.ready=false;convert.disabled=true;setGate();return}openApp();state.ready=true;convert.disabled=!state.file;try{const p=await getPlanState();state.pro=p?.pro===true;planUi()}catch{}});
})();