const $=s=>document.querySelector(s);
const e={file:$("#file"),cameraFile:$("#cameraFile"),choose:$("#choose"),camera:$("#camera"),text:$("#text"),size:$("#size"),sizeOut:$("#sizeOut"),opacity:$("#opacity"),opacityOut:$("#opacityOut"),position:$("#position"),angle:$("#angle"),color:$("#color"),strokeColor:$("#strokeColor"),stroke:$("#stroke"),strokeOut:$("#strokeOut"),shadow:$("#shadow"),tile:$("#tile"),format:$("#format"),quality:$("#quality"),qualityOut:$("#qualityOut"),sourcePreview:$("#sourcePreview"),preview:$("#preview"),run:$("#run"),download:$("#download"),copy:$("#copy"),reset:$("#reset"),status:$("#status"),spinner:$("#spinner"),sourceStat:$("#sourceStat"),positionStat:$("#positionStat"),opacityStat:$("#opacityStat"),formatStat:$("#formatStat"),resultSection:$("#resultSection"),output:$("#output"),dimensions:$("#dimensions"),sizeResult:$("#sizeResult"),formatResult:$("#formatResult"),watermarkResult:$("#watermarkResult")};
let source=null,sourceFile=null,resultBlob=null,sourceUrl="",previewUrl="",resultUrl="",previewTimer=0,working=false;
const bytes=n=>{if(!Number.isFinite(n))return"—";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+" "+u[i]};
const revoke=u=>{if(u)try{URL.revokeObjectURL(u)}catch{}};
const status=(t,error=false)=>{e.status.textContent=t;e.status.className="status"+(error?" error":"")};
const ext=t=>t==="image/jpeg"?"jpg":t==="image/png"?"png":"webp";
function dims(){return source?[source.width||source.naturalWidth||0,source.height||source.naturalHeight||0]:[0,0]}
function settings(){
 const [w,h]=dims(),font=Math.max(10,Math.round(Math.min(w,h)*(Number(e.size.value)/100)));
 return {w,h,text:(e.text.value||"NEXAUREN").slice(0,120),font,alpha:Number(e.opacity.value)/100,pos:e.position.value,angle:Number(e.angle.value||0)*Math.PI/180,fill:e.color.value,stroke:e.strokeColor.value,strokeWidth:Number(e.stroke.value),shadow:e.shadow.checked,tile:e.tile.checked,format:e.format.value,quality:Number(e.quality.value)/100};
}
function drawWatermark(ctx,w,h,scale=1){
 const st=settings(),font=Math.max(10,Math.round(st.font*scale)),pad=Math.max(18,w*.025),label=st.text;
 ctx.save();ctx.font="800 "+font+"px system-ui,-apple-system,sans-serif";ctx.textBaseline="middle";ctx.textAlign="center";ctx.globalAlpha=st.alpha;ctx.fillStyle=st.fill;ctx.strokeStyle=st.stroke;ctx.lineWidth=st.strokeWidth*scale;
 const one=(x,y)=>{ctx.save();ctx.translate(x,y);ctx.rotate(st.angle);if(st.shadow){ctx.shadowColor="rgba(0,0,0,.45)";ctx.shadowBlur=10*scale;ctx.shadowOffsetX=0;ctx.shadowOffsetY=4*scale}if(ctx.lineWidth>0)ctx.strokeText(label,0,0);ctx.fillText(label,0,0);ctx.restore()};
 if(st.tile){const step=Math.max(font*3,w*.22);for(let y=pad;y<h+step;y+=step)for(let x=pad;x<w+step;x+=step)one(x+(Math.floor(y/step)%2?step/2:0),y)}
 else {const tw=ctx.measureText(label).width;let x=w/2,y=h/2;if(st.pos.endsWith("r"))x=w-pad-tw/2;if(st.pos.endsWith("l"))x=pad+tw/2;if(st.pos.startsWith("t"))y=pad+font/2;if(st.pos.startsWith("b"))y=h-pad-font/2;one(x,y)}
 ctx.restore();
}
function renderCanvas(targetW,targetH,type,quality){
 const [w,h]=dims();const ratio=Math.min(1,targetW/w,targetH/h);const W=Math.max(1,Math.round(w*ratio)),H=Math.max(1,Math.round(h*ratio));const c=document.createElement("canvas");c.width=W;c.height=H;const ctx=c.getContext("2d",{alpha:true});if(!ctx)throw new Error("The browser could not start image processing.");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";if(type==="image/jpeg"){ctx.fillStyle="#ffffff";ctx.fillRect(0,0,W,H)}ctx.drawImage(source,0,0,W,H);drawWatermark(ctx,W,H,ratio);return{canvas:c,W,H}};
async function exportBlob(full=true){const st=settings();const max=full?32000000:1600000;const [w,h]=dims();let target=Math.min(max,w*h);const scale=Math.min(1,Math.sqrt(target/(w*h)));const result=renderCanvas(Math.max(1,Math.round(w*scale)),Math.max(1,Math.round(h*scale)),st.format,st.quality);return new Promise((resolve,reject)=>result.canvas.toBlob(b=>b?resolve({blob:b,W:result.W,H:result.H}):reject(new Error("The browser could not export this image format.")),st.format,st.format==="image/png"?undefined:st.quality))};
function updateUi(){e.sizeOut.textContent=e.size.value+"%";e.opacityOut.textContent=e.opacity.value+"%";e.strokeOut.textContent=e.stroke.value;e.qualityOut.textContent=e.format.value==="image/png"?"Lossless":e.quality.value+"%";const map={br:"Bottom right",bl:"Bottom left",tr:"Top right",tl:"Top left",c:"Center"};e.positionStat.textContent=e.tile.checked?"Tiled":map[e.position.value];e.opacityStat.textContent=e.opacity.value+"%";e.formatStat.textContent=ext(e.format.value).toUpperCase();if(source){const [w,h]=dims();e.sourceStat.textContent=w+" × "+h}schedulePreview()};
function schedulePreview(){if(!source)return;clearTimeout(previewTimer);previewTimer=setTimeout(()=>{try{const target=1200;const r=renderCanvas(target,target,"image/jpeg",.82);r.canvas.toBlob(b=>{if(!b)return;revoke(previewUrl);previewUrl=URL.createObjectURL(b);e.preview.src=previewUrl})}catch(err){status(err?.message||"Could not prepare preview.",true)}},70)}
function setBusy(on){working=on;e.spinner.classList.toggle("on",on);e.spinner.setAttribute("aria-hidden",on?"false":"true");e.run.disabled=on||!source;e.download.disabled=on||!resultBlob;e.copy.disabled=on||!resultBlob;e.run.textContent=on?"Generating…":"Generate watermark"}
async function loadFile(file){try{if(!file||(!file.type.startsWith("image/")&&!/\.(jpe?g|png|webp|gif|bmp|avif|heic|heif|tiff?)$/i.test(file.name)))throw new Error("Please choose a supported image file.");revoke(sourceUrl);revoke(previewUrl);revoke(resultUrl);sourceUrl=URL.createObjectURL(file);sourceFile=file;resultBlob=null;source=await NexaurenImage.loadImage(file);e.sourcePreview.src=sourceUrl;e.resultSection.classList.add("hidden");e.download.disabled=true;e.copy.disabled=true;e.run.disabled=false;status("Image ready. Adjust the watermark and review the live preview.");updateUi()}catch(err){source=null;status(err?.message||"Could not load this image.",true)}}
async function generate(){if(working||!source)return;setBusy(true);status("Rendering full-resolution watermark…");try{const r=await exportBlob(true);resultBlob=r.blob;revoke(resultUrl);resultUrl=URL.createObjectURL(resultBlob);e.output.src=resultUrl;e.resultSection.classList.remove("hidden");e.dimensions.textContent=r.W+" × "+r.H;e.sizeResult.textContent=bytes(resultBlob.size);e.formatResult.textContent=ext(resultBlob.type).toUpperCase();e.watermarkResult.textContent=(e.text.value||"NEXAUREN").slice(0,40);e.download.disabled=false;e.copy.disabled=false;status("Watermark generated successfully.");e.resultSection.scrollIntoView({behavior:"smooth",block:"start"})}catch(err){status(err?.message||"Could not generate the watermark.",true)}finally{setBusy(false)}}
function download(){if(!resultBlob)return;NexaurenImage.download(resultBlob,"nexauren-watermark."+ext(resultBlob.type));status("Watermarked image sent to download.")}
async function copySummary(){if(!resultBlob)return;const text=["NEXAUREN WATERMARK STUDIO","Text: "+(e.text.value||"NEXAUREN").slice(0,120),"Position: "+e.position.value,"Opacity: "+e.opacity.value+"%","Format: "+ext(resultBlob.type).toUpperCase(),"Size: "+bytes(resultBlob.size)].join("\n");try{await navigator.clipboard.writeText(text);status("Summary copied.")}catch{status("Could not copy the summary.",true)}}
function reset(){revoke(sourceUrl);revoke(previewUrl);revoke(resultUrl);sourceUrl="";previewUrl="";resultUrl="";source=null;sourceFile=null;resultBlob=null;e.file.value="";e.cameraFile.value="";e.sourcePreview.removeAttribute("src");e.preview.removeAttribute("src");e.output.removeAttribute("src");e.resultSection.classList.add("hidden");e.run.disabled=true;e.download.disabled=true;e.copy.disabled=true;status("Choose an image to start.");e.sourceStat.textContent="No image";updateUi()}
document.querySelectorAll(".preset").forEach(btn=>btn.addEventListener("click",()=>{const s=btn.dataset.style;if(s==="subtle"){e.size.value=5;e.opacity.value=45;e.stroke.value=0;e.shadow.checked=true;e.tile.checked=false;e.position.value="br"}if(s==="bold"){e.size.value=10;e.opacity.value=86;e.stroke.value=2;e.shadow.checked=true;e.tile.checked=false;e.position.value="c"}if(s==="tile"){e.size.value=5;e.opacity.value=38;e.stroke.value=1;e.shadow.checked=false;e.tile.checked=true;e.position.value="c"}if(s==="reset"){e.text.value="NEXAUREN";e.size.value=7;e.opacity.value=70;e.stroke.value=0;e.shadow.checked=true;e.tile.checked=false;e.position.value="br";e.angle.value="0";e.color.value="#ffffff";e.strokeColor.value="#000000";e.format.value="image/webp";e.quality.value="90"}updateUi();status("Style preset applied.")}));
[e.text,e.size,e.opacity,e.position,e.angle,e.color,e.strokeColor,e.stroke,e.shadow,e.tile,e.format,e.quality].forEach(el=>{el.addEventListener("input",updateUi);el.addEventListener("change",updateUi)});
e.choose.onclick=()=>e.file.click();e.camera.onclick=()=>e.cameraFile.click();e.file.onchange=ev=>{void loadFile(ev.target.files[0]);ev.target.value=""};e.cameraFile.onchange=ev=>{void loadFile(ev.target.files[0]);ev.target.value=""};e.run.onclick=generate;e.download.onclick=download;e.copy.onclick=copySummary;e.reset.onclick=reset;document.addEventListener("keydown",ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key==="Enter"){ev.preventDefault();if(source)void generate()}});updateUi();